# English. Strings of the download page, the guide and the versions page. HTML fragments and
# {placeholders} stay as they are; keys match tools/strings/en.py, which is the reference.
T = {
 'title_index': 'ygd-editor — download', 'title_guide': 'ygd-editor — user guide',
 'desc': 'ygd-editor: run AI coding agents in separate git worktrees, review their changes and ship them, all from one window. Free for macOS, Windows and Linux.',
 'nav_download': 'Download', 'nav_guide': 'Guide', 'nav_releases': 'All versions', 'nav_issues': 'Report a problem',
 'tagline': 'Give every task its own branch and its own AI agent — and keep an eye on all of them.',
 'hero_p': 'ygd-editor opens each task in its own git worktree, runs a coding agent inside it (Claude Code, Codex or Gemini CLI), and lets you review the changes, commit, push and open the pull request without leaving the window. Free, for macOS, Windows and Linux.',
 'dl_loading': 'Finding the latest version…', 'dl_for': 'Download for {label}', 'dl_none': 'No version published yet', 'dl_none_hint': 'The first release is on its way.',
 'dl_error': 'See all versions', 'dl_error_hint': 'Could not read the latest version ({err}). The releases page has every download.',
 'dl_others': 'Other systems:', 'dl_checksums': 'Checksums', 'dl_free': 'Free · no account needed · updates itself',
 'kinds': {'mac-arm64': 'macOS · Apple Silicon (M1 and later)', 'mac-x64': 'macOS · Intel', 'win-x64': 'Windows', 'linux-appimage': 'Linux · AppImage', 'linux-deb': 'Linux · Debian / Ubuntu'},
 'shot_console': 'The console: worktrees on the left, changes and diff in the middle, the agent session on the right.',
 'what_h': 'What you get',
 'what': [
   ('One worktree per task', 'Every branch gets its own folder, so agents never step on each other and you can switch tasks without stashing anything.'),
   ('Agents where the code is', 'Start Claude Code, Codex or Gemini CLI inside a worktree, watch it work, answer its questions, and hand a session to another worktree when plans change.'),
   ('Review and ship in place', 'Stage files, read the diff, ask the agent to explain or change a selection, commit, push and open the pull request from the same screen.'),
   ('Stays out of your way', 'One inbox for every session waiting on you and everything the app has told you, optional desktop notifications, and a daily spend meter with limits you set.'),
   ('Try it several ways', 'Run one task with two to four agents or models at once, each in its own worktree, compare what they did side by side, and keep the best.'),
   ('Undo a turn, not the day', 'Every agent turn shows what it changed and can be rolled back on its own — your edits and the other turns stay.'),
 ],
 'install_h': 'Install in a minute',
 'install_intro': 'Your computer will warn you the first time. That is expected: nobody paid Apple or Microsoft for a certificate, and the warning is about the missing paperwork, not about anything the app does. Here is how to get past it — once, and never again for that computer.',
 'install': [
   ('macOS', ['Open the downloaded <code>.dmg</code>. A window shows these steps in your language — click <em>Continue</em> — then drag <strong>ygd-editor</strong> into Applications.', 'Open it. macOS says it <em>could not verify</em> the app and offers <em>Move to Trash</em> or <em>Done</em>: click <strong>Done</strong>.', 'Open <strong>System Settings › Privacy &amp; Security</strong>, scroll down to <em>Security</em> and click <strong>Open Anyway</strong> next to ygd-editor. Confirm with your password. That is it — macOS will not ask again.', 'On macOS 14 or older, <strong>right-click the app › Open</strong> does the same in one step.', 'Not sure which Mac you have? Apple menu › About This Mac: “Apple M…” is Apple Silicon, anything with “Intel” is Intel.']),
   ('Windows', ['Run the installer. When SmartScreen says “Windows protected your PC”, click <strong>More info</strong>, then <strong>Run anyway</strong>.', 'The publisher shown is <em>ygd-editor release signing</em> — that is us. Pick the install folder if you like and finish.', 'The app appears in the Start menu as ygd-editor.']),
   ('Linux', ['<strong>AppImage:</strong> make it executable (<code>chmod +x ygd-editor-*.AppImage</code>) and run it. If it complains about FUSE, run it with <code>--appimage-extract-and-run</code>.', '<strong>Debian / Ubuntu:</strong> <code>sudo apt install ./ygd-editor-*.deb</code>, then find it in your applications menu.']),
 ],
 'cli_h': 'Skip the warning: install from Terminal.',
 'cli_p': 'Paste this into Terminal (Applications › Utilities). It downloads the latest version for your Mac, checks that its checksums carry the project’s signature, that the download matches them and that the app is signed with the project’s certificate, and puts it in Applications. If any check fails, it installs nothing. macOS asks nothing, because nothing came through a browser. Run it again any time to reinstall.',
 'cli_copy': 'Copy', 'cli_copied': 'Copied',
 'cli_or': 'Or, with the disk image from the button above:',
 'need_h': 'What you need', 'need_p': 'Git on your computer and an account with at least one provider. <a href="https://github.com/openai/codex">Codex</a> and <a href="https://github.com/google-gemini/gemini-cli">Gemini CLI</a> are not inside the installer — that is what keeps it small — the app downloads the one you pick the first time you ask for it (about 130–150 MB for Codex, 20 MB for Gemini CLI) and checks it against the version this release was built with before running it; for <a href="https://docs.anthropic.com/en/docs/claude-code">Claude Code</a>, whose licence does not allow shipping it, Settings › AI providers offers one click that runs Anthropic’s official installer for you. Connecting a provider opens its sign-in page in your browser. For pull requests, GitHub’s <code>gh</code> or GitLab’s <code>glab</code>. The app runs on 64-bit Windows 10 or 11, and on x86-64 Linux with glibc 2.34 or newer (Ubuntu 22.04, Debian 12, Fedora 35 and later).',
 'updates_h': 'Updates take care of themselves',
 'updates_p': 'Shortly after launch, and every six hours while it stays open, the app checks for a new version and tells you when there is one. One click downloads it, and you choose when it installs: restart now, or the next time you quit. An update installs only when the release’s checksums carry the project’s signature; anything else is refused. Settings › About &amp; updates has a “Check for updates” button and can download new versions by itself. After an update, “What’s new” shows what changed without leaving the app.',
 'genuine_h': 'Is my download genuine?',
 'genuine_p': 'Two independent checks, neither of which relies on trusting a name. You do not need to run them; they are here for the people who want to.',
 'genuine_sums': '<strong>Signed checksums.</strong> Every version since 0.17.2 comes with <code>SHA256SUMS.txt</code> and its signature, <code>SHA256SUMS.txt.sig</code>, made with the project’s key — the one behind its certificate, <a href="{pem}"><code>release-signing.pem</code></a>. Put both next to your download and check the certificate’s fingerprint against this one first: that is the step that proves the rest, because whoever could replace an installer could replace a certificate next to it. The signature then vouches for the checksums, and the checksums for every file. Only <code>openssl</code> is needed (macOS and Linux have it; on Windows, use Git Bash). Expect <code>Verified OK</code>, then <code>OK</code> for your file:',
 'genuine_prov': '<strong>Older versions.</strong> 0.6.0 to 0.17.1 come with an unsigned <code>SHA256SUMS.txt</code>, and the code signature below is what vouches for them. 0.1.0 to 0.4.0 were built by the project’s release workflow on GitHub and carry its <a href="https://www.sigstore.dev/">Sigstore</a> signature instead, <code>SHA256SUMS.txt.sigstore.json</code>. With <code>cosign</code> installed:',
 'genuine_sig': '<strong>Code signature.</strong> The macOS app and the Windows installer are signed with the project’s certificate (<a href="{pem}">public key</a>). Compare the fingerprint, not the name — anyone can name a certificate anything.',
 'guide_cta_h': 'New here?', 'guide_cta_p': 'The <a href="{prefix}guide.html">user guide</a> walks through the first ten minutes: opening a repository, creating a worktree, starting an agent, reviewing and shipping the result.',
 'footer_made': 'Made by Manu Hurtado. The app is free to use; the source code is private.',
 # guide
 'g_h1': 'User guide', 'g_lead': 'Everything you need for the first afternoon with ygd-editor, in plain words. Ten minutes to read, and you can come back to any section from the list.',
 'g_toc': 'On this page',
 'g_sections': [
  ('idea', 'The idea in one minute', [
    'A git <em>worktree</em> is a second folder for the same repository, checked out on another branch. Instead of switching branches in one folder — and stashing, rebuilding and losing your place every time — you keep one folder per task.',
    'ygd-editor is built around that: the left panel lists your worktrees, the middle shows what changed in the one you picked, and the right runs an AI agent inside it. Two agents on two tasks work in two folders and never collide. When one is waiting for an answer, the header inbox tells you.',
    '<img src="{img}start.png" alt="The start page: recent repositories and the start actions" loading="lazy">',
  ]),
  ('first', 'Your first ten minutes', [
    'On a fresh install the start page shows a <em>Get set up</em> checklist: git, an AI provider, a repository, a first worktree and a first session. Each step has the button that does it and ticks itself when it is done; <em>Hide this checklist</em> puts it away for good. Here are the same steps in more words.',
    '<ol>'
    '<li><strong>Open a repository.</strong> On the start page choose <em>Open repository</em> and pick a folder that already has git in it, or <em>Clone repository</em> with a GitHub, GitLab or any git URL. Recent repositories stay on the start page.</li>'
    '<li><strong>Create a worktree.</strong> <em>New worktree</em> (⌘N) suggests a branch name from the task and a folder to put it in; both are yours to rename to whatever convention you use. Git does not allow spaces in a branch name, so they become dashes and the dialog shows you the result before creating anything. Where worktrees go on disk, and an optional suggested prefix, are Settings › Git.</li>'
    '<li><strong>Start a session.</strong> <em>+ Session</em> in the right panel picks an agent and a model; the default agent is Settings › Default agent. Type what you want in the composer. <code>@</code> attaches files or context such as the current diff, <code>/</code> runs the agent’s commands, <code>#</code> its skills. ⌘↵ sends.</li>'
    '<li><strong>Let it work — or stop it.</strong> The transcript shows every tool the agent uses. When it needs permission for something you have not pre-approved, the session turns to <em>waiting</em>, the header inbox counts it, and you allow or deny — “Always allow” remembers your choice for that worktree. <em>Stop</em> interrupts; prompts you type while it works are queued.</li>'
    '<li><strong>Review the changes.</strong> The Changes tab lists every touched file with who changed it. Click a file for the diff; select lines and choose <em>Explain</em> or <em>Ask to change</em> to send them back to the agent. A warning marks files another worktree of the same repository also touches.</li>'
    '<li><strong>Commit, push, open the PR.</strong> Tick the files to stage, write the message or <em>Draft with AI</em>, <em>Commit</em>. <em>Push</em> sets the upstream; <em>Open pull request</em> fills title, body (drafted from the diff if you want), draft flag, reviewers and labels, and hands off to <code>gh</code> or <code>glab</code>. The worktree card then shows the PR and its checks.</li>'
    '</ol>',
    '<img src="{img}console.png" alt="The console with a diff open and a Claude Code session running" loading="lazy">',
  ]),
  ('daily', 'Day to day', [
    '<p><strong>The main worktree</strong> — the folder you opened the repository at — is listed with the others and is the one new worktrees branch from. Select it and click its branch name in the header: a search box drops down over every branch — yours, or one that only exists on the remote, which it checks out as a new tracking branch. Type to narrow it, arrow keys and Enter to switch. A branch another worktree already holds is listed but greyed out, because git allows a branch in one worktree at a time.</p>'
    '<p><strong>Update from base</strong> on a worktree fetches and rebases it on the base branch; conflicts stop with the files listed, you resolve them, stage and <em>Continue</em>. <strong>Fetch</strong> refreshes ahead/behind counts. The Terminal tab is a real shell in the worktree folder; Activity is the timeline of what happened there — commits, pushes, sessions — and survives restarts.</p>'
    '<p><strong>Handing off.</strong> A session can move to another worktree from its menu, transcript included, when you realise the work belongs on another branch.</p>'
    '<p><strong>Removing a worktree</strong> ends its sessions, archives their logs and forgets its permission rules; the branch stays unless you delete it. Settings › Git can delete the worktree by itself after its PR merges.</p>'
    '<p><strong>Multiple repositories.</strong> Open as many as you like; the header switches between them, and the inbox counts waiting sessions across all of them.</p>',
  ]),
  ('git', 'Git without a terminal', [
   '<strong>Pull and Update from base are two things.</strong> <em>Pull</em> brings in what was pushed to your own branch — a teammate’s commit, say — so your next push goes through; when both sides have new commits it rebases or merges as Settings › Git says, or asks. <em>Update from base</em>, in the <code>···</code> menu, is the other job: catching up with the base branch.',
   '<strong>Conflicts.</strong> When a rebase, merge, revert or cherry-pick stops on conflicts, open the file and resolve it block by block: keep one side, the other, or <em>Keep both</em> — or take a whole file, or <em>Ask the agent</em>. The two sides are named for what is happening, so you never have to guess which one is “ours”. <em>Mark resolved</em>, then <em>Continue</em> on the banner.',
   '<strong>Amend.</strong> The commit box has an <em>Amend</em> switch. A commit you have not pushed is simply rewritten. One you have pushed is never force-pushed: the app puts it on a new branch, pushes that, opens a new pull request and closes the old one with a link to the new one.',
   '<strong>History.</strong> Right-click a commit in Activity to <em>Copy SHA</em>, <em>Show changes</em>, <em>Revert</em> it, or <em>Cherry-pick into…</em> another worktree.',
   '<strong>Pull requests.</strong> The PR card lists every check, each reviewer’s verdict and the review comments with their file and line. <em>Address review</em> hands the open comments to the agent; <em>Merge</em> offers the methods the repository allows and says why when it cannot merge yet. When work has landed, <em>Clean up merged worktrees…</em> removes every finished worktree in one go and names the ones it left alone.',
   '<strong>Forks.</strong> In a fork, <code>origin</code> is your copy and <code>upstream</code> the project. The app reads the base branch from <code>upstream</code> whenever there is one, so a new worktree starts from <code>upstream/main</code> rather than your fork’s stale copy, while pushes and pull requests still go to your fork; <em>Fetch</em> fetches both. Settings › Git › <em>Base remote</em> picks another remote, and the Remotes dialog tags it <em>base</em>.',
   '<strong>Bare repositories.</strong> A repository opens whole from any of its folders: the main one, a linked worktree, a bare <code>api.git</code> with its worktrees beside it, or a <code>proj/.bare</code> layout. Every worktree is listed. A bare repository has no main worktree, so any worktree can be removed, new ones go beside the bare folder (<code>api--fix</code>), and <em>Make current</em> and switching the main worktree’s branch are not offered.',
  ]),
  ('review', 'Reviewing what an agent did', [
   '<strong>One turn at a time.</strong> Every turn that changes files ends with a line under it in the transcript — <em>Changed 4 files · +120 −8</em>. Click it and the Changes tab shows only what that turn did. <em>Undo this turn…</em> lists what will happen to each file first, then takes the turn’s changes out: a file nobody touched since goes back to how it was, a file you or a later turn edited keeps those edits, and where both changed the same lines you get conflict markers to resolve. The undo is a turn of its own, so it can be undone too.',
   '<strong>Hunk by hunk.</strong> Each block of a diff has <em>Stage</em> and <em>Discard</em> (<em>Unstage</em> once staged); select some lines to stage or discard just those. A file that is partly staged gets a <em>Staged / Unstaged</em> switch above its diff.',
   '<strong>Finding an old conversation.</strong> <em>Search sessions</em>, at the top of the sessions panel, looks through what was said in this worktree, the repository or the workspace — and, if you tick <em>archived</em>, in worktrees you have since removed. A result opens the session at that message. Right-click a session for <em>Export transcript…</em>: a Markdown file with the prompts, the answers and the tool calls. Nothing in it is hidden, so read it before you share it.',
   '<strong>Reading a long change.</strong> The Changes list groups files by folder — the folder button beside the filter switches to a flat list — and the filter keeps the paths that contain every word you type. Tick <em>Viewed</em> (V) on each file you have read: the tick goes away by itself if the agent changes that file again, and <em>Next unviewed</em> (⇧N) takes you to the next one. In the diff, N and P jump from hunk to hunk and W wraps long lines. Changed words are highlighted inside a line, code is coloured by language, side by side turns unified when the panel is narrow, images show before and after, and a Markdown file can be shown <em>Rendered</em>.',
   '<strong>Discarded by mistake?</strong> <em>Discard</em>, <em>Discard all changes</em>, discarding a hunk or a few lines, and force-removing a worktree all keep what they throw away. The toast’s <em>Undo</em> brings it back; later, <em>Stashes › Recently discarded</em> has <em>Restore</em>, and <em>Save as stash</em> turns an entry into an ordinary stash — the way back to the changes of a worktree you removed. <em>Stash all changes</em> offers an Undo too.',
   '<strong>Big repositories.</strong> With more than 2,000 untracked files the list shows the first 2,000 and a line per folder counting the rest; <em>Stage all</em>, <em>Commit</em> and <code>.gitignore</code> still cover every one. Untracked files over 10 MB are left out of turn checkpoints, and the turn’s footer says how many. If reading the worktree takes more than 5 seconds the turn gets no checkpoint at all, and its footer says it cannot be opened or undone. Changes inside <code>node_modules</code>, <code>dist</code>, <code>.next</code> and <code>target</code> no longer refresh the list, and edits made outside the app show up even during a long push or fetch.',
  ]),
  ('sessions', 'Agents at work', [
   '<strong>Reading the transcript.</strong> Answers show as formatted text, and every code block has a <em>Copy</em> button. Three or more tool calls in a row fold into one line that opens to show them. A path to a file of the worktree is a link: a changed file opens its diff, any other opens in your editor. Scroll up to read and the transcript stops following; <em>Jump to latest</em> takes you back. If a session was stopped while it was asking for permission, the transcript says so.',
   '<strong>Long sessions.</strong> A session opens on its latest messages, and <em>Show earlier messages</em> loads the rest when you want it. To keep the history from growing for ever, Settings › Default agent has <em>Keep sessions for</em> (days) and <em>Session storage limit</em> (MB): when the app starts, it deletes what is older or over the limit. Both are off until you set them.',
   '<strong>Stopping really stops.</strong> <em>Stop</em>, removing a worktree and quitting the app also end whatever the agent started — a dev server, say. Changing the model does not, and neither does the idle limit: Settings › Default agent › <em>End idle agents after</em> (30 minutes unless you change it; empty means never) ends an agent that has been idle that long, to give back its memory, and your next prompt picks the conversation up again. If the app crashed with agents still running, the next launch offers to <em>Stop</em> them or <em>Leave running</em>.',
   '<strong>Your shell’s environment.</strong> Agents get what your <code>.zshrc</code> or <code>.bashrc</code> exports — a proxy, API keys, <code>AWS_PROFILE</code> — just as if you had started them from a terminal, even when the app itself was opened from the Dock or a menu rather than a terminal. Settings › Editor &amp; terminal › <em>Use my shell environment</em> turns it off, and lists the names of the variables it brings, never their values. Windows does not need it: apps there get your variables already.',
  ]),
  ('setup', 'Worktrees that are ready to run', [
   'A new worktree has none of your ignored files — no <code>.env</code>, no <code>node_modules</code>. <strong>Settings › Worktree setup</strong> fixes that once: files to copy from the main worktree (<code>.env*</code>, say), commands to run in the new worktree’s terminal (<code>pnpm install</code>), and a port base, so each worktree gets its own port as <code>YGD_PORT</code> and two dev servers stop fighting over the same one. The worktree’s terminal and its agents also get <code>YGD_WORKTREE</code> and <code>YGD_BRANCH</code>. The New worktree dialog shows what setup will do; <em>Run setup again</em> is in the <code>···</code> menu.',
   'A repository can carry the same recipe in <code>.ygd/worktree.json</code>. Its commands come from whoever wrote the branch, so the app shows them and asks before running them the first time — and again whenever the file changes.',
  ]),
  ('terminals', 'Terminals', [
   '<strong>Several terminals.</strong> <code>+</code> in the Terminal tab opens another shell beside the worktree’s own; double-click a tab to rename it. <em>Run ▾</em> in the toolbar starts saved commands — <code>dev: pnpm dev</code> — each in a terminal named after it, with <em>Restart</em> and <em>Stop</em>. <code>@terminal:dev</code> in a prompt attaches what that terminal printed.',
   '<strong>They keep running.</strong> A terminal keeps its program and its history while Settings, the start page or the compare view is open, so <code>vim</code>, <code>htop</code> or a dev server is exactly as you left it. ⌘F (Ctrl+Shift+F on Windows and Linux), or the magnifier at the end of the tabs, searches the scrollback. ⌘-click (Ctrl+click) opens a link in your browser. ⌘⇧] and ⌘⇧[ (Ctrl+PageDown and Ctrl+PageUp) go to the next and previous terminal. Closing a terminal that is still running something asks first, and names the program.',
  ]),
  ('tryn', 'Try it several ways', [
   'Not sure which agent or model will do a task best? Tick <em>Try it N ways</em> in the New worktree dialog and pick two to four attempts — Claude Code, Codex and Gemini CLI, or one model three times. Each gets its own worktree from the same base (<code>login-a</code>, <code>login-b</code>…), setup runs in each, and the same first prompt goes to all of them. Every attempt counts against your budget, and the dialog says so.',
   'The attempts sit together in the sidebar. Click their entry to compare them side by side: status, files and lines changed, cost, turns and time, a quick diff, and your check command — <code>pnpm test</code>, say, from Settings › Worktree setup — run in each on demand. <em>Keep this one</em> removes the others after listing them, can give the winner the plain branch name, and can go straight on to Make current or a pull request.',
  ]),
  ('workspaces', 'Working on several repositories: workspaces', [
    'A <em>workspace</em> is a named set of folders the app holds open together. A gateway, a web console and a folder of notes are often one piece of work, and a question about one of them is usually answered in another — a workspace is how you tell the app they belong together.',
    '<img src="{img}workspace.png" alt="A workspace of two repositories: the sidebar groups worktrees by repository" loading="lazy">',
    '<strong>Making one.</strong> Open a second repository while one is already open and the app asks where it goes: add it to what you are working in, start a new workspace with both, or open it on its own. Escape means “on its own”. You can also start one from the start page with <em>New workspace</em>, and add or remove folders later from the workspaces button in the header. Removing a folder from a workspace never deletes anything — only the set changes.',
    '<strong>From VS Code.</strong> If your team already keeps a <code>.code-workspace</code> file, <em>Open workspace file…</em> reads it: the same folders, in the same order, named the way VS Code names them. Comments and trailing commas in the file are fine. Folders that are not git repositories are kept — they just have no worktrees — and a folder that has gone missing is reported rather than quietly dropped. <em>Save to file</em> writes it back, leaving the parts the app does not use untouched, so the same file keeps working in both tools.',
    '<strong>What the sidebar shows.</strong> Worktrees grouped by repository, each group foldable, with the filter matching a branch or a repository name so you can find a branch without remembering where it lives. A folded group still shows what is running inside it, and still says when a session is waiting. One repository shows no groups at all.',
    '<strong>What the agents can see.</strong> A session still runs <em>in</em> its worktree — that is where git and every relative path belong — but it can read the workspace’s other folders too, so “where does this call end up?” can be answered from either side. A session that only reads is still only allowed to read, everywhere. There is also a row above the groups, <em>Across the workspace</em>, for sessions that belong to no single worktree: ask those the questions that span the whole stack. They have no branch, no changes and no terminal, because those belong to a worktree.',
    '<strong>Settings.</strong> Three levels now: Global, the workspace, then a single repository. The default agent, the permission preset and the base branch are usually a property of the stack rather than of each repository in it, so set them once on the workspace; a repository that needs something different still overrides it. The scope selector in Settings picks the level, and a section that is not overriding says where its values are coming from.',
    'The app remembers each workspace separately: come back to one and you land on the repository, worktree and panel layout you left it in.',
  ]),
  ('current', 'Testing a worktree in the default one', [
    'The place to try a change is the repository\'s own folder — the <em>default worktree</em> — because that is where <code>node_modules</code>, <code>.env</code>, the build cache and the running dev server already are. The work happens in the other worktrees. <strong>Make current</strong> brings one of them into the default worktree: its commits, what it has not committed yet and its new files, on top of the default worktree\'s branch. From then on the header says, on every screen, what the default worktree is running — <code>DEFAULT · feat-a + feat-b · 1 edit</code> — and the sidebar tags the <em>default</em> worktree and the <em>current</em> ones.',
    '<img src="{img}current.png" alt="The header strip, open: where the default worktree came from, the two current worktrees and what can be done next" loading="lazy">',
    '<strong>Swap</strong> puts another worktree in its place. <strong>Add</strong> stacks another one on top, to try two changes together; where both touch the same lines the load stops on a conflict in the default worktree, and for each file you keep the default side, take the incoming one, or edit it and mark it resolved — then <em>Continue</em>, or <em>Abort</em> back to what was running before.',
    '<strong>Fixes made while testing go home.</strong> If you — or an agent in the default worktree — fix something while trying a change, <em>Send edits back</em> returns it to the worktree it belongs to, as uncommitted changes there, to review and commit; <em>Undo</em> takes it back until the next step. A file that belongs to several current worktrees, or to none, is asked about rather than guessed. Swap, Add, Refresh and End send the edits back first, so nothing done in the default worktree is lost to them. <em>Send edits back</em>, <em>End</em> and <em>Undo this turn</em> write files the way a checkout would — Git LFS, git-crypt and Windows line endings included; if a filter the repository needs is missing (<code>git-lfs</code> not installed, say), they stop with git’s message instead of leaving pointer files behind.',
    '<strong>End</strong> gives the default worktree back exactly as it was: its branch, and its own changes, staged and not staged. Every step opens a short preview first — what comes in, what is kept aside, which files would conflict, and anything that stops it right now with the way out. You find them in the <code>···</code> menu of a worktree, on a right-click in the sidebar, in the header strip, and on ⌘⇧D / ⌘⇧E.',
    'Settings › Git can refresh a current worktree by itself when its agent keeps working, and run a command after each load — <code>pnpm install</code> when <code>pnpm-lock.yaml</code> changed, say — in the default worktree\'s terminal, where you see it. Your own <code>git stash</code> is never touched. It needs git 2.40 or newer.',
  ]),
  ('find', 'Getting around, and what it cost', [
   '<strong>⌘K</strong> opens the command palette: every action in the app — with its shortcut, or the reason it cannot run right now — plus your worktrees across the workspace, your sessions, the pages of Settings and your recent repositories. Start with <code>&gt;</code> for actions, <code>@</code> for worktrees, <code>#</code> for sessions; arrows and Enter do the rest.',
   '<strong>What it cost.</strong> Settings › Budget has a <em>Usage report</em>: a bar per day split by agent, and what each repository and branch spent, over the last 7, 30 or 90 days or any dates you pick, with <em>Export CSV</em>. The figures are the budget’s own, so they always match the spend meter.',
  ]),
  ('providers', 'Agents and providers', [
    '<p>ygd-editor does not talk to any AI service itself. It runs the command-line tools you already have — <a href="https://docs.anthropic.com/en/docs/claude-code">Claude Code</a>, <a href="https://github.com/openai/codex">Codex</a>, <a href="https://github.com/google-gemini/gemini-cli">Gemini CLI</a> — with your own accounts, so your usage, billing and data terms are exactly the ones you agreed with those providers.</p>'
    '<p>Settings › AI providers connects each provider with your own account: <em>Connect</em> opens the provider’s sign-in page in your browser, and the card then shows the account, the plan and <em>Switch account</em> / <em>Disconnect</em> / <em>Test connection</em>. Codex and Gemini CLI are downloaded by the app the first time you pick them — the card says the version and the size, shows the progress, and <em>Remove download</em> takes it away again; if you have your own copy installed, the app uses that one. Claude Code’s licence does not allow shipping it, so its card offers <em>Install Claude Code</em>, which runs Anthropic’s official installer in the card’s terminal, into your home folder, without an administrator password. The default agent and model, and the permission preset, can differ per repository.</p>',
    '<p>A card also says when the installed CLI is newer or older than the versions this release was checked with. Sessions still run; the note is there so that an incomplete report has an explanation. When Codex loses its connection and retries, the transcript shows a short <em>Reconnecting…</em> note rather than an error.</p>',
  ]),
  ('permissions', 'Permissions', [
    '<p>Agents ask before doing things you have not pre-approved. Settings › Permissions has three presets — <em>strict</em> (read only), <em>balanced</em> (read and edit files, ask for anything else) and <em>yolo</em> (also run commands, use the web and push) — plus individual switches for reading, editing, running commands, web access, pushing and deleting. Whatever the preset, an agent can never delete without asking unless you turn that on.</p>'
    '<p>When a request comes in, <em>Approve</em> and <em>Deny</em> answer once; <em>Always allow</em> remembers that tool for that worktree, and the rule goes away with the worktree.</p>',
    '<p>When an agent asks for several things at once, the requests queue on the session card and in the inbox — <em>1 of 3</em> — and you answer them in order. Settings › Permissions › <em>Allowed rules</em> lists every “Always allow” by worktree, with the date it was added; <em>Revoke</em> takes effect at once, in a running session too. <em>Auto-deny after</em> (minutes, off by default) refuses a request nobody answers and tells the agent why. Codex and Gemini CLI cannot ask, so their agent bar shows the sandbox mode your switches give them; a click on it opens Settings › Permissions.</p>',
  ]),
  ('notifications', 'Notifications, inbox and budget', [
    '<p>Settings › Notifications chooses when the app pings you: when a session is waiting, when one finishes, and when a pull request changes — checks done, approved, changes requested, merged. Pull requests are watched for every worktree in the background, so you hear about them within about five minutes even for one you are not looking at; a merge found that way keeps its offer to remove the worktree until you answer it. Notifications only show while the window is not in front, a click on one jumps to the session, and the dock or taskbar badge can count waiting sessions.</p>',
    '<p>The header inbox has two tabs. <em>Needs input</em> is the sessions waiting on you. <em>Activity</em> is everything the app has told you — finished turns, pull request changes, failures with git’s full output, the toasts you might have missed — and a click on a row takes you to its session or worktree. Unread rows are counted, <em>Mark all read</em> clears them, and the latest 200 are kept across restarts.</p>',
    '<p>The budget bar at the bottom of the left panel is today’s spend across every session. When an agent reports its own cost, that is the figure; otherwise its tokens are priced at the model’s list price, and the rates in Settings › Budget are only for models that have none. The usage popover and a session’s cost tooltip say which it is. Settings › Budget also sets a daily and a per-session limit and a warning threshold; with <em>Pause sessions at the limit</em> on, reaching the daily limit also stops turns that are still running, and a toast says how many.</p>',
  ]),
  ('settings', 'Settings', [
    '<p>Settings (⌘,) are grouped by topic. Appearance sets theme, accent colour, density and fonts; Language switches the interface between English, Spanish, Italian, Polish, French, German and Turkish. Several sections carry a <em>per repo</em> badge: with a repository selected at the top you can override those for that repository only. Dates, times, numbers and costs follow the language you choose, not the system’s.</p>'
    '<p>Everything saves automatically to <code>settings.json</code> in the app’s folder in your home directory; <em>Open settings.json</em> edits the raw file with validation, and the header shows when it was last written. The file names its <a href="https://mhguitarte.github.io/ygd-editor/settings.schema.json">schema</a>, so an editor such as VS Code completes and checks it when you edit it by hand. Every save keeps the previous file as <code>settings.json.bak</code>; if the file is ever damaged, the app runs on that copy and tells you. An older version of the app never overwrites a file a newer one wrote: it runs on defaults and refuses to save settings until you update again. Workspaces, the inbox and the session lists are kept the same way.</p>',
    '<p><em>Search settings</em>, at the top, finds any row by what it is called or what it does — type “budget limit” and Budget opens with the cursor in Daily limit; ⌘K finds settings too. A row you have changed shows a dot and its own <em>Reset</em>. Number fields refuse a value the app could not use, say why, and keep the saved one.</p>',
    '<img src="{img}settings.png" alt="Settings › Appearance" loading="lazy">',
  ]),
  ('layout', 'Small windows and the keyboard', [
   '<strong>Small windows.</strong> The window goes down to 900 × 680, so the app fits beside an editor on a 13- or 14-inch laptop. Narrower than about 1,180 pixels the sessions panel folds into a rail, and narrower than about 1,000 the worktree list does too. Click a rail to open its panel over the middle; Escape, or a click beside it, puts it away. Your saved layout is left alone: widen the window and the panels are back as they were.',
   '<strong>From the keyboard.</strong> Each list — worktrees, sessions, terminal tabs, Settings sections, recent repositories — is a single Tab stop. ↑ and ↓ (← and → on terminal tabs), Home and End move along it, Enter or Space picks a row, the Menu key or Shift+F10 opens the row’s menu, and F2 renames a terminal tab.',
   '<strong>Questions are the app’s own.</strong> Anything that needs a yes — discarding, dropping a stash, merging a pull request — asks in a dialog of the app, in your language, with the action written on the button; Escape means no. Clone, Hand off and Remotes ask before throwing away what you have typed in them.',
  ]),
  ('updates', 'Updates', [
    '<p>Shortly after launch, and every six hours while it stays open, the app checks this site’s releases and tells you when there is a new version. One click downloads it; with Settings › About &amp; updates › <em>Download updates automatically</em> on, it downloads as soon as it is found. Nothing installs until you choose: <em>Restart &amp; update</em> now, <em>Restart later</em> — it then installs when you quit — or <em>Discard</em>.</p>',
    '<p>An update installs only if the release’s signed checksums list it, checked against the certificate built into the app. If they do not, the app says the update is not signed by the project and installs nothing. Settings › About &amp; updates also has <em>Offer updates</em>, which turns the checks off, and <em>Check for updates</em> with the time of the last check.</p>',
    '<p>The first launch after an update says which version you are on, and its <em>What’s new</em> opens the release notes inside the app. Settings › About &amp; updates and the command palette open them too.</p>',
  ]),
  ('shortcuts', 'Keyboard shortcuts', [
    '<table><tr><td>⌘O</td><td>Open repository</td></tr><tr><td>⇧⌘C</td><td>Clone repository</td></tr><tr><td>⌘N</td><td>New worktree</td></tr><tr><td>⌘K</td><td>Command palette</td></tr><tr><td>⌘,</td><td>Settings</td></tr><tr><td>⌘↵</td><td>Send the prompt</td></tr><tr><td>⌘F</td><td>Find in the terminal</td></tr><tr><td>⌘⇧] ⌘⇧[</td><td>Next / previous terminal</td></tr><tr><td>⇧N</td><td>Next unviewed file</td></tr></table>'
    '<p>On Windows and Linux read ⌘ as Ctrl — except in the terminal, where find is Ctrl+Shift+F and Ctrl+PageDown / Ctrl+PageUp switch terminals. Most shortcuts can be changed under Settings › Keyboard shortcuts.</p>',
  ]),
  ('trouble', 'When something goes wrong', [
    '<p><strong>macOS says it could not verify the app (Move to Trash / Done).</strong> Click Done, then System Settings › Privacy &amp; Security › scroll to Security › <em>Open Anyway</em>, and confirm with your password. On macOS 14 or older, right-click › Open does it in one step. If it still refuses, in Terminal: <code>xattr -d com.apple.quarantine /Applications/ygd-editor.app</code>. If it says the app is <em>damaged</em>, the download was corrupted: download it again and compare it against <code>SHA256SUMS.txt</code>.</p>'
    '<p><strong>Avoiding the prompt altogether.</strong> Install from Terminal instead: <code>curl -fsSL https://mhguitarte.github.io/ygd-editor/install.sh | bash</code>. It checks the download the way macOS would have and puts the app in Applications; see the download page.</p>'
    '<p><strong>Windows blocks the installer.</strong> SmartScreen › More info › Run anyway. The publisher should read <em>ygd-editor release signing</em>.</p>'
    '<p><strong>The AppImage does not start.</strong> Run it with <code>--appimage-extract-and-run</code>, or install <code>libfuse2</code>.</p>'
    '<p><strong>A provider shows “Not installed”.</strong> Codex and Gemini CLI are downloaded on request: click <em>Download</em> on the card, and if the download fails the card says why (offline, or a file that did not match its checksum and was discarded). For Claude Code, click <em>Install Claude Code</em> on its card; if you installed it yourself, open a terminal, check that <code>claude --version</code> works, then Settings › AI providers › Rescan.</p>'
    '<p><strong>Git errors.</strong> The app explains the usual ones in one sentence — credentials, a remote that moved on, a lock file, a dirty tree, conflicts — and keeps the full output in the worktree terminal.</p>'
    '<p><strong>No update appears.</strong> Check Settings › About &amp; updates › Offer updates, then Check for updates; the app needs to reach github.com.</p>'
    '<p><strong>An update was refused as not signed by the project.</strong> Nothing was installed. Download the installer from <a href="{prefix}releases.html">All versions</a> and check it as <a href="{prefix}index.html#genuine">Is my download genuine?</a> explains.</p>'
    '<p><strong>Settings will not save after going back to an older version.</strong> The older app leaves files written by the newer one alone, runs on defaults and says which file it is. Update again and everything is where you left it.</p>'
    '<p><strong>Reporting a problem.</strong> Settings › Diagnostics shows what a bug report needs: the versions of the app, git and each agent CLI, the PATH agents get, the running agent processes and a live log you can filter. <em>Log levels</em> sets how much is logged — <code>info, git=debug</code> logs git in detail. <em>Prepare bundle…</em> gathers it all in a zip and lists every file for you to read before <em>Save zip…</em>: tokens and API keys are masked, what you typed to agents and terminals is left out, and your home folder shows as <code>~</code>. Attach it to <a href="https://github.com/{repo}/issues">an issue</a> with what you did, what you expected and what happened.</p>',
  ]),
  ('uninstall', 'Uninstalling', [
    '<strong>Before you remove it</strong> — both optional. If a worktree is <em>current</em> in the default one, <em>End</em> it, so the default worktree has its own branch and changes back. To sign out of a provider, use <em>Disconnect</em> on its card in Settings › AI providers: the sign-ins belong to Claude Code, Codex and Gemini CLI rather than to the app, so removing the app does not end them. Then quit ygd-editor.',
    '<strong>macOS.</strong> Drag <strong>ygd-editor</strong> from Applications to the Trash — from <code>~/Applications</code> if the Terminal install put it there.',
    '<strong>Windows.</strong> Settings › Apps › Installed apps › ygd-editor › <em>Uninstall</em>, or Control Panel › Programs and Features.',
    '<strong>Linux.</strong> Delete the AppImage file. For the Debian / Ubuntu package: <code>sudo apt remove ygd-editor</code>.',
    '<strong>What stays behind.</strong> Your settings, workspaces, session history and the Codex and Gemini CLI downloads live in the <code>.ygd-editor</code> folder in your home directory, and uninstalling keeps them, so a reinstall picks up where you left off. To remove them too, with the app’s caches, run this after uninstalling:',
    '<p>macOS:</p><pre>rm -rf ~/.ygd-editor ~/Library/Application\\ Support/ygd-editor ~/Library/Caches/ygd-editor-updater ~/Library/Caches/com.mhguitarte.ygd-editor* ~/Library/HTTPStorages/com.mhguitarte.ygd-editor ~/Library/Preferences/com.mhguitarte.ygd-editor.plist</pre>',
    '<p>Windows (PowerShell):</p><pre>Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\\.ygd-editor", "$env:APPDATA\\ygd-editor", "$env:LOCALAPPDATA\\ygd-editor-updater"</pre>',
    '<p>Linux:</p><pre>rm -rf ~/.ygd-editor ~/.config/ygd-editor ~/.cache/ygd-editor-updater</pre>',
    '<strong>What is never touched.</strong> Your repositories and the worktrees you created are ordinary git folders and stay where they are; <code>git worktree remove &lt;folder&gt;</code> removes one. If the app installed Claude Code for you, it stays in your home folder — <a href="https://docs.anthropic.com/en/docs/claude-code">Anthropic’s documentation</a> explains how to remove it.',
  ]),
  ('privacy', 'Privacy and security', [
    '<p>Everything runs on your computer. The app itself connects to the internet for two things: checking this site’s releases for updates, and once a day fetching the public list of models and their prices from models.dev. Agents talk to their providers with your accounts; git talks to your remotes with your credentials. Provider tokens the app keeps are stored in the operating system’s keychain. The interface runs sandboxed, every request that names a path is checked against the repositories you actually opened, and no command is ever built from a shell string. The diagnostics bundle is saved where you choose and sent nowhere.</p>'
    '<p>To check that a download is really ours, see <a href="{prefix}index.html#genuine">Is my download genuine?</a> on the download page.</p>',
  ]),
 ],
 # versions page and small shared strings
 'dl_version': 'version {v}',
 'genuine_details': 'the technical details',
 'lang_label': 'Language',
 'title_releases': 'ygd-editor — all versions',
 'r_h1': 'All versions',
 'r_lead': 'Every version of ygd-editor that has been published. First the newest one for each system, then the whole history, system by system. The download page always offers the newest complete version; this list is for anyone who needs a particular one.',
 'r_latest_h': 'Newest for each system',
 'r_all_h': 'Every version, by system',
 'r_systems': {'mac': 'macOS', 'win': 'Windows', 'linux': 'Linux'},
 'r_loading': 'Loading the versions…',
 'r_error': 'Could not read the list of versions ({err}).',
 'r_github': 'The releases on GitHub',
 'r_none': 'No version published yet.',
 'r_notes': 'What changed',
 'r_checksums': 'Checksums',
 'r_updates': 'Installed apps update themselves to the newest complete version; nothing here needs downloading by hand unless you want a specific one.',
}
