# Français. Strings of the download page, the guide and the versions page. HTML fragments and
# {placeholders} stay as they are; keys match tools/strings/en.py, which is the reference.
T = {
 'title_index': 'ygd-editor — téléchargement', 'title_guide': 'ygd-editor — guide d’utilisation',
 'desc': 'ygd-editor : exécutez des agents de programmation IA dans des worktrees git séparés, relisez leurs modifications et livrez-les, le tout depuis une seule fenêtre. Gratuit pour macOS, Windows et Linux.',
 'nav_download': 'Télécharger', 'nav_guide': 'Guide', 'nav_releases': 'Toutes les versions', 'nav_issues': 'Signaler un problème',
 'tagline': 'Donnez à chaque tâche sa propre branche et son propre agent IA, et gardez-les tous à l’œil.',
 'hero_p': 'ygd-editor ouvre chaque tâche dans son propre worktree git, y exécute un agent de programmation (Claude Code, Codex ou Gemini CLI) et vous laisse relire les modifications, faire le commit, le push et ouvrir la pull request sans quitter la fenêtre. Gratuit, pour macOS, Windows et Linux.',
 'dl_loading': 'Recherche de la dernière version…', 'dl_for': 'Télécharger pour {label}', 'dl_none': 'Aucune version publiée pour l’instant', 'dl_none_hint': 'La première est en route.',
 'dl_error': 'Voir toutes les versions', 'dl_error_hint': 'Impossible de lire la dernière version ({err}). La page des versions contient tous les téléchargements.',
 'dl_others': 'Autres systèmes :', 'dl_checksums': 'Sommes de contrôle', 'dl_free': 'Gratuit · sans compte · se met à jour tout seul',
 'kinds': {'mac-arm64': 'macOS · Apple Silicon (M1 et suivants)', 'mac-x64': 'macOS · Intel', 'win-x64': 'Windows', 'linux-appimage': 'Linux · AppImage', 'linux-deb': 'Linux · Debian / Ubuntu'},
 'shot_console': 'La console : les worktrees à gauche, les modifications et le diff au centre, la session de l’agent à droite.',
 'what_h': 'Ce que vous obtenez',
 'what': [
   ('Un worktree par tâche', 'Chaque branche a son propre dossier : les agents ne se marchent jamais sur les pieds et vous changez de tâche sans rien mettre de côté.'),
   ('Les agents là où est le code', 'Lancez Claude Code, Codex ou Gemini CLI dans un worktree, regardez-le travailler, répondez à ses questions et transférez une session vers un autre worktree quand les plans changent.'),
   ('Relire et livrer sur place', 'Indexez des fichiers, lisez le diff, demandez à l’agent d’expliquer ou de modifier une sélection, faites le commit, le push et ouvrez la pull request depuis le même écran.'),
   ('Ne vous dérange pas', 'Une seule boîte de réception pour toutes les sessions qui vous attendent et tout ce que l’application vous a dit, des notifications de bureau facultatives et un compteur de dépenses du jour avec les limites que vous fixez.'),
   ('Essayez de plusieurs façons', 'Lancez une tâche avec deux à quatre agents ou modèles à la fois, chacun dans son worktree, comparez ce qu’ils ont fait et gardez le meilleur.'),
   ('Annulez un tour, pas la journée', 'Chaque tour de l’agent montre ce qu’il a modifié et peut être annulé seul — vos modifications et les autres tours restent.'),
 ],
 'install_h': 'Installation en une minute',
 'install_intro': 'Votre ordinateur vous avertira la première fois. C’est normal : personne n’a payé Apple ni Microsoft pour un certificat, et l’avertissement concerne cette paperasse manquante, pas ce que fait l’application. Voici comment passer outre, une seule fois et plus jamais sur cet ordinateur.',
 'install': [
   ('macOS', ['Ouvrez le <code>.dmg</code> téléchargé. Une fenêtre affiche ces étapes dans votre langue — cliquez sur <em>Continuer</em> — puis glissez <strong>ygd-editor</strong> dans Applications.', 'Ouvrez-la. macOS dit qu’il <em>n’a pas pu vérifier</em> l’application et propose <em>Placer dans la corbeille</em> ou <em>Terminé</em> : cliquez sur <strong>Terminé</strong>.', 'Ouvrez <strong>Réglages Système › Confidentialité et sécurité</strong>, descendez jusqu’à <em>Sécurité</em> et cliquez sur <strong>Ouvrir quand même</strong> à côté de ygd-editor. Confirmez avec votre mot de passe. C’est tout : macOS ne redemandera plus.', 'Sous macOS 14 ou antérieur, <strong>clic droit sur l’application › Ouvrir</strong> fait la même chose en une étape.', 'Vous ne savez pas quel Mac vous avez ? Menu Pomme › À propos de ce Mac : « Apple M… » est un Apple Silicon, tout ce qui mentionne « Intel » est un Intel.']),
   ('Windows', ['Lancez l’installateur. Quand SmartScreen dit « Windows a protégé votre ordinateur », cliquez sur <strong>Informations complémentaires</strong>, puis sur <strong>Exécuter quand même</strong>.', 'L’éditeur affiché est <em>ygd-editor release signing</em> : c’est nous. Choisissez le dossier d’installation si vous le souhaitez et terminez.', 'L’application apparaît dans le menu Démarrer sous le nom ygd-editor.']),
   ('Linux', ['<strong>AppImage :</strong> rendez-le exécutable (<code>chmod +x ygd-editor-*.AppImage</code>) et lancez-le. S’il se plaint de FUSE, lancez-le avec <code>--appimage-extract-and-run</code>.', '<strong>Debian / Ubuntu :</strong> <code>sudo apt install ./ygd-editor-*.deb</code>, puis retrouvez-le dans votre menu d’applications.']),
 ],
 'cli_h': 'Sans l’avertissement : installez-la depuis le Terminal.',
 'cli_p': 'Collez ceci dans le Terminal (Applications › Utilitaires). Il télécharge la dernière version pour votre Mac, vérifie que ses sommes de contrôle portent la signature du projet, que le téléchargement leur correspond et que l’application est signée avec le certificat du projet, puis la place dans Applications. Si une vérification échoue, il n’installe rien. macOS ne demande rien, car rien n’est passé par un navigateur. Relancez-le quand vous voulez pour réinstaller.',
 'cli_copy': 'Copier', 'cli_copied': 'Copié',
 'cli_or': 'Ou, avec l’image disque du bouton ci-dessus :',
 'need_h': 'Ce dont vous avez besoin', 'need_p': 'Git sur votre ordinateur et un compte chez au moins un fournisseur. <a href="https://github.com/openai/codex">Codex</a> et <a href="https://github.com/google-gemini/gemini-cli">Gemini CLI</a> ne sont pas dans l’installeur — c’est ce qui le garde léger — : l’application télécharge celui que vous choisissez la première fois que vous le demandez (environ 130–150 Mo pour Codex, 20 Mo pour Gemini CLI) et le vérifie contre la version avec laquelle cette release a été construite avant de l’exécuter ; pour <a href="https://docs.anthropic.com/en/docs/claude-code">Claude Code</a>, dont la licence ne permet pas de l’inclure, Réglages › Fournisseurs d’IA propose un clic qui exécute pour vous l’installateur officiel d’Anthropic. Connecter un fournisseur ouvre sa page de connexion dans votre navigateur. Pour les pull requests, <code>gh</code> de GitHub ou <code>glab</code> de GitLab. L’application fonctionne sous Windows 10 ou 11 en 64 bits, et sous Linux x86-64 avec glibc 2.34 ou plus récent (Ubuntu 22.04, Debian 12, Fedora 35 et suivantes).',
 'updates_h': 'Les mises à jour se font toutes seules',
 'updates_p': 'Peu après le lancement, puis toutes les six heures tant qu’elle reste ouverte, l’application cherche une nouvelle version et vous prévient quand il y en a une. Un clic la télécharge, et c’est vous qui choisissez quand elle s’installe : en redémarrant maintenant ou la prochaine fois que vous quittez. Une mise à jour ne s’installe que si les sommes de contrôle de la version portent la signature du projet ; toute autre est refusée. Réglages › À propos et mises à jour a un bouton « Rechercher des mises à jour » et peut télécharger les nouvelles versions tout seul. Après une mise à jour, « Nouveautés » montre ce qui a changé sans quitter l’application.',
 'genuine_h': 'Mon téléchargement est-il authentique ?',
 'genuine_p': 'Deux vérifications indépendantes, dont aucune ne repose sur la confiance en un nom. Vous n’êtes pas obligé de les faire ; elles sont là pour ceux qui le souhaitent.',
 'genuine_sums': '<strong>Sommes de contrôle signées.</strong> Chaque version depuis la 0.17.2 est accompagnée de <code>SHA256SUMS.txt</code> et de sa signature, <code>SHA256SUMS.txt.sig</code>, faite avec la clé du projet : celle qui se trouve derrière son certificat, <a href="{pem}"><code>release-signing.pem</code></a>. Placez les deux à côté de votre téléchargement et comparez d’abord l’empreinte du certificat avec celle-ci : c’est l’étape qui prouve tout le reste, car quiconque pourrait remplacer un installateur pourrait aussi remplacer le certificat à côté. La signature garantit alors les sommes de contrôle, et les sommes chaque fichier. Seul <code>openssl</code> est nécessaire (macOS et Linux l’ont ; sous Windows, utilisez Git Bash). Vous devez obtenir <code>Verified OK</code>, puis <code>OK</code> pour votre fichier :',
 'genuine_prov': '<strong>Versions plus anciennes.</strong> Les versions 0.6.0 à 0.17.1 sont accompagnées d’un <code>SHA256SUMS.txt</code> non signé, et c’est la signature du code ci-dessous qui s’en porte garante. Les versions 0.1.0 à 0.4.0 ont été produites par le workflow de publication du projet sur GitHub et portent à la place sa signature <a href="https://www.sigstore.dev/">Sigstore</a>, <code>SHA256SUMS.txt.sigstore.json</code>. Avec <code>cosign</code> installé :',
 'genuine_sig': '<strong>Signature du code.</strong> L’application macOS et l’installateur Windows sont signés avec le certificat du projet (<a href="{pem}">clé publique</a>). Comparez l’empreinte, pas le nom : n’importe qui peut donner n’importe quel nom à un certificat.',
 'guide_cta_h': 'Première visite ?', 'guide_cta_p': 'Le <a href="{prefix}guide.html">guide d’utilisation</a> parcourt les dix premières minutes : ouvrir un dépôt, créer un worktree, lancer un agent, relire et livrer le résultat.',
 'footer_made': 'Réalisé par Manu Hurtado. L’application est gratuite ; le code source est privé.',
 # guide
 'g_h1': 'Guide d’utilisation', 'g_lead': 'Tout ce qu’il vous faut pour le premier après-midi avec ygd-editor, en termes simples. Dix minutes de lecture, et vous pouvez revenir à n’importe quelle section depuis la liste.',
 'g_toc': 'Sur cette page',
 'g_sections': [
  ('idea', 'L’idée en une minute', [
    'Un <em>worktree</em> git est un second dossier du même dépôt, sur une autre branche. Au lieu de changer de branche dans un seul dossier — en mettant de côté, en recompilant et en perdant le fil à chaque fois — vous gardez un dossier par tâche.',
    'ygd-editor est construit autour de cela : le panneau de gauche liste vos worktrees, celui du centre montre ce qui a changé dans celui que vous avez choisi, et celui de droite y exécute un agent IA. Deux agents sur deux tâches travaillent dans deux dossiers et ne se heurtent jamais. Quand l’un attend une réponse, la boîte de réception de l’en-tête vous le signale.',
    '<img src="{img}start.png" alt="La page d’accueil : dépôts récents et actions de démarrage" loading="lazy">',
  ]),
  ('first', 'Vos dix premières minutes', [
    'Après une nouvelle installation, la page d’accueil affiche une liste <em>Pour commencer</em> : git, un fournisseur d’IA, un dépôt, un premier worktree et une première session. Chaque étape a le bouton qui la fait et se coche toute seule une fois faite ; <em>Masquer cette liste</em> la range pour de bon. Voici les mêmes étapes, plus en détail.',
    '<ol>'
    '<li><strong>Ouvrez un dépôt.</strong> Sur la page d’accueil, choisissez <em>Ouvrir un dépôt</em> et sélectionnez un dossier qui contient déjà git, ou <em>Cloner un dépôt</em> avec une URL GitHub, GitLab ou n’importe quelle URL git. Les dépôts récents restent sur la page d’accueil.</li>'
    '<li><strong>Créez un worktree.</strong> <em>Nouveau worktree</em> (⌘N) propose un nom de branche tiré de la tâche et un dossier où la placer ; vous pouvez renommer les deux selon la convention que vous utilisez. Git n’accepte pas les espaces dans un nom de branche, ils deviennent donc des tirets et la boîte de dialogue vous montre le résultat avant de créer quoi que ce soit. L’emplacement des worktrees sur le disque, et un préfixe suggéré facultatif, se trouvent dans Réglages › Git.</li>'
    '<li><strong>Lancez une session.</strong> <em>+ Session</em> dans le panneau de droite choisit un agent et un modèle ; l’agent par défaut est dans Réglages › Agent par défaut. Tapez ce que vous voulez dans le compositeur. <code>@</code> joint des fichiers ou du contexte comme le diff actuel, <code>/</code> exécute les commandes de l’agent, <code>#</code> ses skills. ⌘↵ envoie.</li>'
    '<li><strong>Laissez-le travailler, ou arrêtez-le.</strong> La transcription montre chaque outil que l’agent utilise. Quand il a besoin d’une permission pour quelque chose que vous n’avez pas pré-approuvé, la session passe <em>en attente</em>, la boîte de réception de l’en-tête la compte, et vous autorisez ou refusez ; « Toujours autoriser » mémorise votre choix pour ce worktree. <em>Arrêter</em> interrompt ; ce que vous tapez pendant qu’il travaille est mis en file d’attente.</li>'
    '<li><strong>Relisez les modifications.</strong> L’onglet Modifications liste chaque fichier touché et qui l’a modifié. Cliquez sur un fichier pour le diff ; sélectionnez des lignes et choisissez <em>Expliquer</em> ou <em>Demander une modification</em> pour les renvoyer à l’agent. Un avertissement marque les fichiers qu’un autre worktree du même dépôt touche aussi.</li>'
    '<li><strong>Commit, push, ouvrez la PR.</strong> Cochez les fichiers à indexer, écrivez le message ou <em>Rédiger avec l’IA</em>, <em>Commit</em>. <em>Push</em> configure l’upstream ; <em>Ouvrir une pull request</em> remplit le titre, le corps (rédigé à partir du diff si vous le souhaitez), l’état de brouillon, les relecteurs et les étiquettes, et passe la main à <code>gh</code> ou <code>glab</code>. La carte du worktree affiche ensuite la PR et ses checks.</li>'
    '</ol>',
    '<img src="{img}console.png" alt="La console avec un diff ouvert et une session Claude Code en cours" loading="lazy">',
  ]),
  ('daily', 'Au quotidien', [
    '<p><strong>Le worktree principal</strong> — le dossier avec lequel vous avez ouvert le dépôt — figure avec les autres et c’est de lui que partent les nouveaux worktrees. Sélectionnez-le et cliquez sur le nom de sa branche dans l’en-tête : un champ de recherche se déplie sur toutes les branches — les vôtres, ou une qui n’existe que sur le dépôt distant, qu’il extrait comme nouvelle branche de suivi. Tapez pour filtrer, flèches et Entrée pour changer. Une branche déjà tenue par un autre worktree est listée mais grisée, parce que git n’autorise une branche que dans un seul worktree à la fois.</p>'
    '<p><strong>Mettre à jour depuis la base</strong> sur un worktree fait un fetch et un rebase sur la branche de base ; les conflits s’arrêtent avec la liste des fichiers, vous les résolvez, vous indexez et <em>Continuer</em>. <strong>Fetch</strong> rafraîchit les compteurs d’avance/retard. L’onglet Terminal est un vrai shell dans le dossier du worktree ; Activité est la chronologie de ce qui s’y est passé — commits, pushes, sessions — et survit aux redémarrages.</p>'
    '<p><strong>Transférer une session.</strong> Une session peut être transférée vers un autre worktree depuis son menu, transcription comprise, quand vous réalisez que le travail appartient à une autre branche.</p>'
    '<p><strong>Supprimer un worktree</strong> termine ses sessions, archive leurs journaux et oublie ses règles de permissions ; la branche reste sauf si vous la supprimez. Réglages › Git peut supprimer le worktree tout seul une fois sa PR fusionnée.</p>'
    '<p><strong>Plusieurs dépôts.</strong> Ouvrez-en autant que vous voulez ; l’en-tête passe de l’un à l’autre, et la boîte de réception compte les sessions en attente de tous.</p>',
  ]),
  ('git', 'Git sans terminal', [
   '<strong>Pull et Mettre à jour depuis la base sont deux choses.</strong> <em>Pull</em> récupère ce qui a été poussé sur votre propre branche — le commit d’un collègue, par exemple — pour que votre prochain push passe ; si les deux côtés ont de nouveaux commits, il fait un rebase ou un merge selon Réglages › Git, ou vous demande. <em>Mettre à jour depuis la base</em>, dans le menu <code>···</code>, est l’autre travail : rattraper la branche de base.',
   '<strong>Conflits.</strong> Quand un rebase, un merge, un revert ou un cherry-pick s’arrête sur des conflits, ouvrez le fichier et résolvez-le bloc par bloc : gardez un côté, l’autre ou <em>Garder les deux</em> — ou prenez un fichier entier, ou <em>Demander à l’agent</em>. Les deux côtés sont nommés d’après ce qui se passe, pour ne jamais avoir à deviner lequel est « le nôtre ». <em>Marquer comme résolu</em>, puis <em>Continuer</em> sur le bandeau.',
   '<strong>Amender.</strong> La zone de commit a un interrupteur <em>Amender</em>. Un commit que vous n’avez pas poussé est simplement réécrit. Un commit déjà poussé n’est jamais forcé : l’app le met sur une nouvelle branche, la pousse, ouvre une nouvelle pull request et ferme l’ancienne avec un lien vers la nouvelle.',
   '<strong>Historique.</strong> Clic droit sur un commit dans Activité pour <em>Copier le SHA</em>, <em>Afficher les modifications</em>, <em>Annuler (revert)</em> ou faire un <em>Cherry-pick dans…</em> un autre worktree.',
   '<strong>Pull requests.</strong> La carte de la PR liste chaque check, l’avis de chaque relecteur et les commentaires de la revue avec leur fichier et leur ligne. <em>Traiter la revue</em> transmet les commentaires ouverts à l’agent ; <em>Fusionner</em> propose les méthodes que le dépôt autorise et dit pourquoi quand ce n’est pas encore possible. Une fois le travail intégré, <em>Nettoyer les worktrees fusionnés…</em> supprime d’un coup tous les worktrees terminés et nomme ceux qu’il laisse.',
   '<strong>Forks.</strong> Dans un fork, <code>origin</code> est votre copie et <code>upstream</code> le projet. L’application lit la branche de base sur <code>upstream</code> dès qu’il existe : un nouveau worktree part donc de <code>upstream/main</code> et non de la copie périmée de votre fork, tandis que les push et les pull requests vont toujours vers votre fork ; <em>Fetch</em> récupère les deux. Réglages › Git › <em>Remote de base</em> en choisit un autre, et la fenêtre Dépôts distants le marque <em>base</em>.',
   '<strong>Dépôts bare.</strong> Un dépôt s’ouvre en entier depuis n’importe lequel de ses dossiers : le principal, un worktree lié, un <code>api.git</code> bare avec ses worktrees à côté, ou une structure <code>proj/.bare</code>. Tous les worktrees sont listés. Un dépôt bare n’a pas de worktree principal : n’importe quel worktree peut être supprimé, les nouveaux vont à côté du dossier bare (<code>api--fix</code>), et <em>Rendre courant</em> ainsi que le changement de branche du worktree principal ne sont pas proposés.',
  ]),
  ('review', 'Relire ce qu’un agent a fait', [
   '<strong>Un tour à la fois.</strong> Chaque tour qui modifie des fichiers se termine par une ligne sous lui dans la transcription — <em>4 fichiers modifiés · +120 −8</em>. Cliquez dessus et l’onglet Modifications montre seulement ce que ce tour a fait. <em>Annuler ce tour…</em> liste d’abord ce qui arrivera à chaque fichier, puis retire les modifications du tour : un fichier que personne n’a touché depuis revient à son état d’avant, un fichier que vous ou un tour suivant avez modifié garde ces modifications, et là où les deux ont changé les mêmes lignes restent des marqueurs de conflit à résoudre. L’annulation est un tour à part entière, on peut donc l’annuler aussi.',
   '<strong>Bloc par bloc.</strong> Chaque bloc d’un diff a <em>Indexer</em> et <em>Abandonner</em> (<em>Désindexer</em> une fois indexé) ; sélectionnez quelques lignes pour indexer ou abandonner seulement celles-ci. Un fichier indexé en partie a un sélecteur <em>Indexé / Non indexé</em> au-dessus de son diff.',
   '<strong>Retrouver une ancienne conversation.</strong> <em>Rechercher dans les sessions</em>, en haut du panneau des sessions, cherche dans ce qui a été dit dans ce worktree, le dépôt ou l’espace de travail — et, si vous cochez <em>archivées</em>, dans les worktrees supprimés depuis. Un résultat ouvre la session sur ce message. Clic droit sur une session pour <em>Exporter la transcription…</em> : un fichier Markdown avec les prompts, les réponses et les appels d’outils. Rien n’y est masqué, relisez-le donc avant de le partager.',
   '<strong>Lire une longue modification.</strong> La liste des Modifications regroupe les fichiers par dossier — le bouton dossier à côté du filtre passe à une liste à plat — et le filtre garde les chemins qui contiennent tous les mots que vous tapez. Cochez <em>Vu</em> (V) sur chaque fichier lu : la coche s’enlève toute seule si l’agent modifie à nouveau ce fichier, et <em>Suivant non vu</em> (⇧N) vous emmène au suivant. Dans le diff, N et P sautent de bloc en bloc et W renvoie les longues lignes à la ligne. Les mots modifiés sont surlignés dans la ligne, le code est coloré selon le langage, la vue côte à côte passe en vue unifiée quand le panneau est étroit, les images s’affichent avant et après, et un fichier Markdown peut être affiché <em>Rendu</em>.',
   '<strong>Abandonné par erreur ?</strong> <em>Abandonner</em>, <em>Abandonner tous les changements</em>, l’abandon d’un bloc ou de quelques lignes et la suppression forcée d’un worktree gardent ce qu’ils jettent. Le bouton <em>Annuler</em> du message le remet en place ; plus tard, <em>Remises › Abandonnés récemment</em> propose <em>Restaurer</em>, et <em>Remiser</em> transforme une entrée en remise ordinaire — le chemin du retour vers les changements d’un worktree supprimé. <em>Remiser tous les changements</em> propose aussi Annuler.',
   '<strong>Gros dépôts.</strong> Au-delà de 2 000 fichiers non suivis, la liste montre les 2 000 premiers et une ligne par dossier qui compte le reste ; <em>Tout indexer</em>, <em>Commit</em> et <code>.gitignore</code> les couvrent quand même tous. Les fichiers non suivis de plus de 10 Mo sont laissés hors des points de restauration des tours, et le pied du tour dit combien. Si la lecture du worktree prend plus de 5 secondes, le tour n’a pas de point de restauration, et son pied indique qu’il ne peut être ni ouvert ni annulé. Les changements dans <code>node_modules</code>, <code>dist</code>, <code>.next</code> et <code>target</code> ne rafraîchissent plus la liste, et les modifications faites hors de l’application apparaissent même pendant un long push ou fetch.',
  ]),
  ('sessions', 'Les agents au travail', [
   '<strong>Lire la transcription.</strong> Les réponses s’affichent en texte mis en forme, et chaque bloc de code a un bouton <em>Copier</em>. Trois appels d’outils ou plus à la suite se replient en une ligne qui s’ouvre pour les montrer. Un chemin vers un fichier du worktree est un lien : un fichier modifié ouvre son diff, les autres s’ouvrent dans votre éditeur. Remontez pour lire et la transcription cesse de suivre ; <em>Aller aux derniers</em> vous ramène en bas. Si une session a été arrêtée pendant qu’elle demandait une autorisation, la transcription le signale.',
   '<strong>Longues sessions.</strong> Une session s’ouvre sur ses derniers messages, et <em>Afficher les messages précédents</em> charge le reste quand vous le voulez. Pour que l’historique ne grossisse pas sans fin, Réglages › Agent par défaut a <em>Conserver les sessions pendant</em> (jours) et <em>Espace maximal des sessions</em> (Mo) : au lancement, l’application supprime ce qui est plus ancien ou dépasse la limite. Les deux sont désactivés tant que vous ne les réglez pas.',
   '<strong>Arrêter, c’est vraiment arrêter.</strong> <em>Arrêter</em>, supprimer un worktree et quitter l’application terminent aussi ce que l’agent a lancé — un serveur de développement, par exemple. Changer de modèle, non, et la limite d’inactivité non plus : Réglages › Agent par défaut › <em>Arrêter les agents inactifs après</em> (30 minutes sauf si vous changez ; vide veut dire jamais) arrête un agent resté inactif aussi longtemps pour libérer sa mémoire, et votre prochain prompt reprend la conversation. Si l’application a planté alors que des agents tournaient encore, le lancement suivant propose de les <em>Arrêter</em> ou de les <em>Laisser tourner</em>.',
   '<strong>L’environnement de votre shell.</strong> Les agents reçoivent ce qu’exporte votre <code>.zshrc</code> ou votre <code>.bashrc</code> — un proxy, des clés d’API, <code>AWS_PROFILE</code> — comme si vous les aviez lancés depuis un terminal, même quand l’application a été ouverte depuis le Dock ou un menu. Réglages › Éditeur et terminal › <em>Utiliser l’environnement de mon shell</em> le désactive et liste les noms des variables apportées, jamais leurs valeurs. Windows n’en a pas besoin : les applications y reçoivent déjà vos variables.',
  ]),
  ('setup', 'Des worktrees prêts à démarrer', [
   'Un nouveau worktree n’a aucun de vos fichiers ignorés : ni <code>.env</code>, ni <code>node_modules</code>. <strong>Réglages › Préparation des worktrees</strong> règle cela une fois pour toutes : des fichiers à copier depuis le worktree principal (<code>.env*</code>, par exemple), des commandes à lancer dans le terminal du nouveau worktree (<code>pnpm install</code>) et un port de base, pour que chaque worktree ait son propre port dans <code>YGD_PORT</code> et que deux serveurs de développement cessent de se disputer le même. Le terminal du worktree et ses agents reçoivent aussi <code>YGD_WORKTREE</code> et <code>YGD_BRANCH</code>. La fenêtre Nouveau worktree montre ce que fera la préparation ; <em>Relancer la préparation</em> est dans le menu <code>···</code>.',
   'Un dépôt peut porter la même recette dans <code>.ygd/worktree.json</code>. Ses commandes viennent de l’auteur de la branche : l’app vous les montre et demande avant de les lancer la première fois — et de nouveau chaque fois que le fichier change.',
  ]),
  ('terminals', 'Terminaux', [
   '<strong>Plusieurs terminaux.</strong> <code>+</code> dans l’onglet Terminal ouvre un autre shell à côté de celui du worktree ; double-cliquez sur un onglet pour le renommer. <em>Lancer ▾</em> dans la barre d’outils démarre des commandes enregistrées — <code>dev: pnpm dev</code> — chacune dans un terminal à son nom, avec <em>Relancer</em> et <em>Arrêter</em>. <code>@terminal:dev</code> dans un prompt joint ce que ce terminal a affiché.',
   '<strong>Ils continuent de tourner.</strong> Un terminal garde son programme et son historique pendant que les Réglages, la page d’accueil ou la comparaison sont ouverts : <code>vim</code>, <code>htop</code> ou un serveur de développement sont exactement comme vous les avez laissés. ⌘F (Ctrl+Maj+F sous Windows et Linux), ou la loupe au bout des onglets, cherche dans l’historique. ⌘-clic (Ctrl+clic) ouvre un lien dans le navigateur. ⌘⇧] et ⌘⇧[ (Ctrl+Page suivante et Ctrl+Page précédente) passent au terminal suivant et précédent. Fermer un terminal qui exécute encore quelque chose demande d’abord confirmation et nomme le programme.',
  ]),
  ('tryn', 'Essayez de plusieurs façons', [
   'Vous ne savez pas quel agent ou modèle fera le mieux une tâche ? Cochez <em>Essayer de N façons</em> dans la fenêtre Nouveau worktree et choisissez de deux à quatre essais — Claude Code, Codex et Gemini CLI, ou le même modèle trois fois. Chacun a son worktree depuis la même base (<code>login-a</code>, <code>login-b</code>…), la préparation tourne dans chacun et le même premier prompt part à tous. Chaque essai compte dans votre budget, et la fenêtre le dit.',
   'Les essais sont regroupés dans la barre latérale. Cliquez sur leur entrée pour les comparer côte à côte : état, fichiers et lignes modifiés, coût, tours et durée, un diff rapide et votre commande de vérification — <code>pnpm test</code>, par exemple, depuis Réglages › Préparation des worktrees — lancée dans chacun à la demande. <em>Garder celui-ci</em> supprime les autres après les avoir listés, peut donner au gagnant le nom de branche sans suffixe et peut enchaîner sur Rendre courant ou une pull request.',
  ]),
  ('workspaces', 'Travailler sur plusieurs dépôts : les espaces de travail', [
    'Un <em>espace de travail</em> est un ensemble nommé de dossiers que l’application garde ouverts ensemble. Une passerelle, une console web et un dossier de notes forment souvent un seul travail, et une question sur l’un trouve généralement sa réponse dans un autre : un espace de travail est la façon de dire à l’application qu’ils vont ensemble.',
    '<img src="{img}workspace.png" alt="Un espace de travail de deux dépôts : la barre latérale regroupe les worktrees par dépôt" loading="lazy">',
    '<strong>En créer un.</strong> Ouvrez un second dépôt alors qu’un autre est déjà ouvert et l’application vous demande où il va : l’ajouter à ce sur quoi vous travaillez, démarrer un nouvel espace de travail avec les deux, ou l’ouvrir tout seul. Échap signifie « tout seul ». Vous pouvez aussi en démarrer un depuis la page d’accueil avec <em>Nouvel espace de travail</em>, et ajouter ou retirer des dossiers plus tard depuis le bouton des espaces de travail dans l’en-tête. Retirer un dossier d’un espace de travail ne supprime jamais rien : seul l’ensemble change.',
    '<strong>Depuis VS Code.</strong> Si votre équipe tient déjà un fichier <code>.code-workspace</code>, <em>Ouvrir un fichier d’espace de travail…</em> le lit : les mêmes dossiers, dans le même ordre, nommés comme VS Code les nomme. Les commentaires et les virgules finales dans le fichier ne posent aucun problème. Les dossiers qui ne sont pas des dépôts git sont conservés — ils n’ont simplement pas de worktrees — et un dossier qui a disparu est signalé plutôt que discrètement écarté. <em>Enregistrer dans le fichier</em> le réécrit en laissant intactes les parties que l’application n’utilise pas, de sorte que le même fichier continue de fonctionner dans les deux outils.',
    '<strong>Ce que montre la barre latérale.</strong> Les worktrees regroupés par dépôt, chaque groupe repliable, avec le filtre qui cherche dans le nom de branche comme dans le nom du dépôt, pour que vous trouviez une branche sans vous souvenir d’où elle vit. Un groupe replié montre toujours ce qui tourne à l’intérieur, et signale toujours quand une session attend. Avec un seul dépôt, il n’y a aucun groupe.',
    '<strong>Ce que voient les agents.</strong> Une session s’exécute toujours <em>dans</em> son worktree — c’est là que vivent git et tous les chemins relatifs — mais elle peut aussi lire les autres dossiers de l’espace de travail, si bien que « où aboutit cet appel ? » peut trouver sa réponse de chaque côté. Une session qui ne fait que lire n’a toujours que le droit de lire, partout. Il y a aussi une ligne au-dessus des groupes, <em>Sur tout l’espace de travail</em>, pour les sessions qui n’appartiennent à aucun worktree en particulier : posez-leur les questions qui couvrent toute la pile. Elles n’ont ni branche, ni modifications, ni terminal, parce que cela appartient à un worktree.',
    '<strong>Réglages.</strong> Trois niveaux désormais : Global, l’espace de travail, puis un dépôt en particulier. L’agent par défaut, le préréglage de permissions et la branche de base sont généralement une propriété de la pile plutôt que de chaque dépôt qui la compose, alors définissez-les une fois sur l’espace de travail ; un dépôt qui a besoin d’autre chose peut toujours les remplacer. Le sélecteur de portée dans Réglages choisit le niveau, et une section qui ne remplace rien indique d’où viennent ses valeurs.',
    'L’application mémorise chaque espace de travail séparément : revenez sur l’un d’eux et vous retrouvez le dépôt, le worktree et la disposition des panneaux que vous aviez laissés.',
  ]),
  ('current', 'Tester un worktree dans celui par défaut', [
    'L\'endroit pour essayer une modification est le dossier du dépôt lui-même — le <em>worktree par défaut</em> — parce que c\'est là que se trouvent déjà <code>node_modules</code>, <code>.env</code>, le cache de build et le serveur de développement. Le travail se fait dans les autres worktrees. <strong>Rendre courant</strong> amène l\'un d\'eux dans le worktree par défaut : ses commits, ce qu\'il n\'a pas encore committé et ses nouveaux fichiers, par-dessus la branche du worktree par défaut. Dès lors, l\'en-tête dit sur chaque écran ce qu\'exécute le worktree par défaut — <code>DÉFAUT · feat-a + feat-b · 1 modification</code> — et la barre latérale marque le worktree <em>par défaut</em> et les <em>courants</em>.',
    '<img src="{img}current.png" alt="La bande de l\'en-tête, ouverte : d\'où venait le worktree par défaut, les deux worktrees courants et ce qu\'on peut faire ensuite" loading="lazy">',
    '<strong>Échanger</strong> met un autre worktree à sa place. <strong>Ajouter</strong> en empile un autre par-dessus, pour essayer deux modifications ensemble ; là où les deux touchent les mêmes lignes, le chargement s\'arrête sur un conflit dans le worktree par défaut, et pour chaque fichier vous gardez le côté par défaut, prenez celui qui arrive ou le modifiez et le marquez résolu — puis <em>Continuer</em>, ou <em>Annuler</em> pour revenir à ce qui tournait avant.',
    '<strong>Les corrections faites pendant les tests rentrent à la maison.</strong> Si vous — ou un agent dans le worktree par défaut — corrigez quelque chose en essayant, <em>Renvoyer les modifications</em> le rend au worktree auquel il appartient, en modifications non committées à relire et committer là-bas ; <em>Annuler</em> le reprend jusqu\'à l\'étape suivante. Un fichier qui appartient à plusieurs worktrees courants, ou à aucun, est demandé plutôt que deviné. Échanger, Ajouter, Rafraîchir et Terminer renvoient d\'abord les modifications, donc rien de ce qui a été fait dans le worktree par défaut ne se perd. <em>Renvoyer les modifications</em>, <em>Terminer</em> et <em>Annuler ce tour</em> écrivent les fichiers comme le ferait un checkout — Git LFS, git-crypt et fins de ligne Windows compris ; s’il manque un filtre dont le dépôt a besoin (<code>git-lfs</code> non installé, par exemple), ils s’arrêtent avec le message de git au lieu de laisser des fichiers pointeurs.',
    '<strong>Terminer</strong> rend le worktree par défaut exactement comme il était : sa branche et ses propres modifications, indexées ou non. Chaque étape ouvre d\'abord un bref aperçu : ce qui entre, ce qui est mis de côté, quels fichiers seraient en conflit et ce qui l\'empêche maintenant, avec la porte de sortie. On les trouve dans le menu <code>···</code> d\'un worktree, au clic droit dans la barre latérale, dans la bande de l\'en-tête et avec ⌘⇧D / ⌘⇧E.',
    'Réglages › Git peut rafraîchir tout seul un worktree courant quand son agent continue de travailler, et lancer une commande après chaque chargement — <code>pnpm install</code> quand <code>pnpm-lock.yaml</code> a changé, par exemple — dans le terminal du worktree par défaut, où vous la voyez. Votre <code>git stash</code> n\'est jamais touché. Il faut git 2.40 ou plus récent.',
  ]),
  ('find', 'Aller vite, et ce que cela a coûté', [
   '<strong>⌘K</strong> ouvre la palette de commandes : toutes les actions de l’app — avec leur raccourci, ou la raison pour laquelle elles ne peuvent pas s’exécuter maintenant — plus vos worktrees de tout l’espace de travail, vos sessions, les pages des Réglages et vos dépôts récents. Commencez par <code>&gt;</code> pour les actions, <code>@</code> pour les worktrees, <code>#</code> pour les sessions ; les flèches et Entrée font le reste.',
   '<strong>Ce que cela a coûté.</strong> Réglages › Budget a un <em>Rapport d’utilisation</em> : une barre par jour répartie par agent, et ce qu’a dépensé chaque dépôt et chaque branche, sur les 7, 30 ou 90 derniers jours ou les dates de votre choix, avec <em>Exporter en CSV</em>. Les chiffres sont ceux du budget lui-même : ils correspondent toujours au compteur de dépenses.',
  ]),
  ('providers', 'Agents et fournisseurs', [
    '<p>ygd-editor ne parle lui-même à aucun service d’IA. Il exécute les outils en ligne de commande que vous avez déjà — <a href="https://docs.anthropic.com/en/docs/claude-code">Claude Code</a>, <a href="https://github.com/openai/codex">Codex</a>, <a href="https://github.com/google-gemini/gemini-cli">Gemini CLI</a> — avec vos propres comptes, si bien que votre utilisation, votre facturation et vos conditions de traitement des données sont exactement celles que vous avez acceptées auprès de ces fournisseurs.</p>'
    '<p>Réglages › Fournisseurs d’IA connecte chaque fournisseur avec votre propre compte : <em>Connecter</em> ouvre la page de connexion du fournisseur dans votre navigateur, et la carte affiche ensuite le compte, le forfait et <em>Changer de compte</em> / <em>Déconnecter</em> / <em>Tester la connexion</em>. Codex et Gemini CLI sont téléchargés par l’application la première fois que vous les choisissez — la carte indique la version et la taille, montre la progression, et <em>Supprimer le téléchargement</em> le retire ; si vous avez votre propre copie installée, l’application utilise celle-là. La licence de Claude Code ne permet pas de l’inclure, sa carte propose donc <em>Installer Claude Code</em>, qui exécute l’installateur officiel d’Anthropic dans le terminal de la carte, dans votre dossier personnel, sans mot de passe administrateur. L’agent et le modèle par défaut, ainsi que le préréglage de permissions, peuvent varier selon le dépôt.</p>',
    '<p>La carte indique aussi quand la CLI installée est plus récente ou plus ancienne que les versions avec lesquelles cette version de l’application a été vérifiée. Les sessions fonctionnent quand même ; la note est là pour expliquer un rapport incomplet. Quand Codex perd la connexion et réessaie, la transcription montre une courte note <em>Reconnexion…</em> au lieu d’une erreur.</p>',
  ]),
  ('permissions', 'Permissions', [
    '<p>Les agents demandent avant de faire ce que vous n’avez pas pré-approuvé. Réglages › Permissions propose trois préréglages — <em>strict</em> (lecture seule), <em>équilibré</em> (lire et modifier les fichiers, demander pour tout le reste) et <em>yolo</em> (aussi exécuter des commandes, utiliser le web et faire des push) — plus des interrupteurs individuels pour la lecture, la modification, l’exécution de commandes, l’accès web, le push et la suppression. Quel que soit le préréglage, un agent ne peut jamais supprimer sans demander, sauf si vous l’activez.</p>'
    '<p>Quand une demande arrive, <em>Approuver</em> et <em>Refuser</em> répondent une fois ; <em>Toujours autoriser</em> mémorise cet outil pour ce worktree, et la règle disparaît avec le worktree.</p>',
    '<p>Quand un agent demande plusieurs choses à la fois, les demandes font la queue sur la carte de la session et dans la boîte de réception — <em>1 sur 3</em> — et vous y répondez dans l’ordre. Réglages › Permissions › <em>Règles autorisées</em> liste chaque « Toujours autoriser » par worktree, avec sa date d’ajout ; <em>Révoquer</em> prend effet tout de suite, même dans une session en cours. <em>Refuser automatiquement après</em> (minutes, désactivé par défaut) refuse une demande restée sans réponse et dit pourquoi à l’agent. Codex et Gemini CLI ne peuvent pas demander : leur barre d’agent montre donc le mode bac à sable que leur donnent vos interrupteurs ; un clic dessus ouvre Réglages › Permissions.</p>',
  ]),
  ('notifications', 'Notifications, boîte de réception et budget', [
    '<p>Réglages › Notifications choisit quand l’application vous prévient : quand une session attend, quand une session se termine et quand une pull request change — checks terminés, approuvée, modifications demandées, fusionnée. Les pull requests de tous les worktrees sont suivies en arrière-plan, vous êtes donc prévenu en cinq minutes environ, même pour un worktree que vous ne regardez pas ; une fusion repérée ainsi garde la proposition de supprimer le worktree jusqu’à ce que vous répondiez. Les notifications ne s’affichent que lorsque la fenêtre n’est pas au premier plan, un clic sur l’une d’elles ouvre la session, et le badge du Dock ou de la barre des tâches peut compter les sessions en attente.</p>',
    '<p>La boîte de réception de l’en-tête a deux onglets. <em>Attend une réponse</em> regroupe les sessions qui vous attendent. <em>Activité</em> est tout ce que l’application vous a dit — tours terminés, changements de pull requests, échecs avec la sortie complète de git, les messages qui vous auraient échappé — et un clic sur une ligne mène à sa session ou à son worktree. Les lignes non lues sont comptées, <em>Tout marquer comme lu</em> les remet à zéro, et les 200 plus récentes sont gardées d’un redémarrage à l’autre.</p>',
    '<p>La barre de budget en bas du panneau de gauche est la dépense du jour sur toutes les sessions. Quand un agent indique son propre coût, c’est ce chiffre ; sinon ses jetons sont valorisés au prix catalogue du modèle, et les tarifs de Réglages › Budget ne servent qu’aux modèles qui n’en ont pas. La fenêtre d’utilisation et l’info-bulle du coût d’une session disent lequel s’applique. Réglages › Budget fixe aussi une limite quotidienne, une limite par session et un seuil d’avertissement ; avec <em>Mettre les sessions en pause à la limite</em> activé, atteindre la limite quotidienne arrête aussi les tours encore en cours, et un message dit combien.</p>',
  ]),
  ('settings', 'Réglages', [
    '<p>Les Réglages (⌘,) sont regroupés par thème. Apparence définit le thème, la couleur d’accent, la densité et les polices ; Langue bascule l’interface entre anglais, espagnol, italien, polonais, français, allemand et turc. Plusieurs sections portent le badge <em>par dépôt</em> : avec un dépôt sélectionné en haut, vous pouvez les remplacer pour ce dépôt uniquement. Les dates, heures, nombres et coûts suivent la langue choisie, pas celle du système.</p>'
    '<p>Tout s’enregistre automatiquement dans <code>settings.json</code>, dans le dossier de l’application au sein de votre répertoire personnel ; <em>Ouvrir settings.json</em> modifie le fichier brut avec validation, et l’en-tête indique quand il a été écrit pour la dernière fois. Le fichier indique son <a href="https://mhguitarte.github.io/ygd-editor/settings.schema.json">schéma</a>, si bien qu’un éditeur comme VS Code le complète et le vérifie quand vous le modifiez à la main. Chaque enregistrement garde le fichier précédent sous <code>settings.json.bak</code> ; si le fichier est endommagé, l’application utilise cette copie et vous le dit. Une version plus ancienne de l’application n’écrase jamais un fichier écrit par une plus récente : elle utilise les valeurs par défaut et refuse d’enregistrer les réglages jusqu’à ce que vous mettiez à jour à nouveau. Les espaces de travail, la boîte de réception et les listes de sessions sont gardés de la même façon.</p>',
    '<p><em>Rechercher dans les réglages</em>, en haut, trouve n’importe quelle ligne par son nom ou par ce qu’elle fait : tapez « limite budget » et Budget s’ouvre avec le curseur dans Limite quotidienne ; ⌘K trouve aussi les réglages. Une ligne que vous avez modifiée affiche un point et son propre <em>Réinitialiser</em>. Les champs numériques refusent une valeur que l’application ne pourrait pas utiliser, disent pourquoi et gardent celle enregistrée.</p>',
    '<img src="{img}settings.png" alt="Réglages › Apparence" loading="lazy">',
  ]),
  ('layout', 'Petites fenêtres et clavier', [
   '<strong>Petites fenêtres.</strong> La fenêtre descend jusqu’à 900 × 680, si bien que l’application tient à côté d’un éditeur sur un portable de 13 ou 14 pouces. En dessous d’environ 1 180 pixels de large, le panneau des sessions se replie en une barre étroite, et en dessous d’environ 1 000 la liste des worktrees aussi. Cliquez sur la barre pour ouvrir son panneau par-dessus le centre ; Échap, ou un clic à côté, le referme. Votre disposition enregistrée n’est pas touchée : élargissez la fenêtre et les panneaux reviennent comme avant.',
   '<strong>Au clavier.</strong> Chaque liste — worktrees, sessions, onglets du terminal, sections des Réglages, dépôts récents — est un seul arrêt de Tab. ↑ et ↓ (← et → sur les onglets du terminal), Début et Fin s’y déplacent, Entrée ou Espace choisissent une ligne, la touche Menu ou Maj+F10 ouvre son menu, et F2 renomme un onglet de terminal.',
   '<strong>Les questions viennent de l’application.</strong> Tout ce qui demande un oui — abandonner des changements, supprimer une remise, fusionner une pull request — demande dans une fenêtre de l’application elle-même, dans votre langue, avec l’action écrite sur le bouton ; Échap veut dire non. Cloner, Transférer la session et Dépôts distants demandent avant de jeter ce que vous y avez tapé.',
  ]),
  ('updates', 'Mises à jour', [
    '<p>Peu après le lancement, puis toutes les six heures tant qu’elle reste ouverte, l’application consulte les versions de ce site et vous prévient quand il y en a une nouvelle. Un clic la télécharge ; avec Réglages › À propos et mises à jour › <em>Télécharger les mises à jour automatiquement</em> activé, elle se télécharge dès qu’elle est trouvée. Rien ne s’installe tant que vous n’avez pas choisi : <em>Redémarrer et mettre à jour</em> maintenant, <em>Redémarrer plus tard</em> — elle s’installe alors quand vous quittez — ou <em>Ignorer</em>.</p>',
    '<p>Une mise à jour ne s’installe que si la liste signée des sommes de contrôle de la version la contient, vérifiée avec le certificat intégré à l’application. Sinon, l’application indique que la mise à jour n’est pas signée par le projet et n’installe rien. Réglages › À propos et mises à jour a aussi <em>Proposer les mises à jour</em>, qui coupe les vérifications, et <em>Rechercher des mises à jour</em> avec l’heure de la dernière vérification.</p>',
    '<p>Le premier lancement après une mise à jour indique quelle version vous utilisez, et son <em>Nouveautés</em> ouvre les notes de version dans l’application. Réglages › À propos et mises à jour et la palette de commandes les ouvrent aussi.</p>',
  ]),
  ('shortcuts', 'Raccourcis clavier', [
    '<table><tr><td>⌘O</td><td>Ouvrir un dépôt</td></tr><tr><td>⇧⌘C</td><td>Cloner un dépôt</td></tr><tr><td>⌘N</td><td>Nouveau worktree</td></tr><tr><td>⌘K</td><td>Palette de commandes</td></tr><tr><td>⌘,</td><td>Réglages</td></tr><tr><td>⌘↵</td><td>Envoyer le prompt</td></tr><tr><td>⌘F</td><td>Chercher dans le terminal</td></tr><tr><td>⌘⇧] ⌘⇧[</td><td>Terminal suivant / précédent</td></tr><tr><td>⇧N</td><td>Fichier suivant non vu</td></tr></table>'
    '<p>Sous Windows et Linux, lisez ⌘ comme Ctrl — sauf dans le terminal, où chercher se fait avec Ctrl+Maj+F et où Ctrl+Page suivante / Ctrl+Page précédente changent de terminal. La plupart des raccourcis peuvent être modifiés dans Réglages › Raccourcis clavier.</p>',
  ]),
  ('trouble', 'Quand quelque chose ne va pas', [
    '<p><strong>macOS dit qu’il n’a pas pu vérifier l’application (Placer dans la corbeille / Terminé).</strong> Cliquez sur Terminé, puis Réglages Système › Confidentialité et sécurité › descendez jusqu’à Sécurité › <em>Ouvrir quand même</em>, et confirmez avec votre mot de passe. Sous macOS 14 ou antérieur, clic droit › Ouvrir le fait en une étape. S’il refuse toujours, dans le Terminal : <code>xattr -d com.apple.quarantine /Applications/ygd-editor.app</code>. S’il dit que l’application est <em>endommagée</em>, le téléchargement a été corrompu : téléchargez-la de nouveau et comparez-la à <code>SHA256SUMS.txt</code>.</p>'
    '<p><strong>Éviter complètement l’avertissement.</strong> Installez-la depuis le Terminal : <code>curl -fsSL https://mhguitarte.github.io/ygd-editor/install.sh | bash</code>. Il vérifie le téléchargement comme macOS l’aurait fait et place l’application dans Applications ; voir la page de téléchargement.</p>'
    '<p><strong>Windows bloque l’installateur.</strong> SmartScreen › Informations complémentaires › Exécuter quand même. L’éditeur doit indiquer <em>ygd-editor release signing</em>.</p>'
    '<p><strong>L’AppImage ne démarre pas.</strong> Lancez-le avec <code>--appimage-extract-and-run</code>, ou installez <code>libfuse2</code>.</p>'
    '<p><strong>Un fournisseur affiche « Non installé ».</strong> Codex et Gemini CLI sont téléchargés à la demande : cliquez sur <em>Télécharger</em> sur la carte ; si le téléchargement échoue, la carte dit pourquoi (hors ligne, ou un fichier qui ne correspondait pas à sa somme de contrôle et a été écarté). Pour Claude Code, cliquez sur <em>Installer Claude Code</em> sur sa carte ; si vous l’avez installé vous-même, ouvrez un terminal, vérifiez que <code>claude --version</code> fonctionne, puis Réglages › Fournisseurs d’IA › Rechercher à nouveau.</p>'
    '<p><strong>Erreurs git.</strong> L’application explique les plus courantes en une phrase — identifiants, un dépôt distant qui a avancé, un fichier de verrouillage, un arbre de travail modifié, des conflits — et garde la sortie complète dans le terminal du worktree.</p>'
    '<p><strong>Aucune mise à jour n’apparaît.</strong> Vérifiez Réglages › À propos et mises à jour › Proposer les mises à jour, puis Rechercher des mises à jour ; l’application doit pouvoir joindre github.com.</p>'
    '<p><strong>Une mise à jour a été refusée car non signée par le projet.</strong> Rien n’a été installé. Téléchargez l’installeur depuis <a href="{prefix}releases.html">Toutes les versions</a> et vérifiez-le comme l’explique <a href="{prefix}index.html#genuine">Mon téléchargement est-il authentique ?</a>.</p>'
    '<p><strong>Les réglages ne s’enregistrent plus après un retour à une version plus ancienne.</strong> L’application plus ancienne laisse intacts les fichiers écrits par la plus récente, utilise les valeurs par défaut et indique de quel fichier il s’agit. Mettez à jour à nouveau et tout sera là où vous l’aviez laissé.</p>'
    '<p><strong>Signaler un problème.</strong> Réglages › Diagnostic montre ce dont un rapport de bug a besoin : les versions de l’application, de git et de chaque CLI d’agent, le PATH que reçoivent les agents, les processus d’agents en cours et un journal en direct que vous pouvez filtrer. <em>Niveaux du journal</em> règle la quantité de détails — <code>info, git=debug</code> journalise git en détail. <em>Préparer le paquet…</em> rassemble tout dans un zip et liste chaque fichier pour que vous le lisiez avant <em>Enregistrer le zip…</em> : les jetons et les clés d’API sont masqués, ce que vous avez tapé aux agents et dans les terminaux est laissé de côté, et votre dossier personnel apparaît comme <code>~</code>. Joignez-le à <a href="https://github.com/{repo}/issues">une issue</a> en décrivant ce que vous avez fait, ce que vous attendiez et ce qui s’est passé.</p>',
  ]),
  ('uninstall', 'Désinstaller', [
    '<strong>Avant de la supprimer</strong> — deux étapes facultatives. Si un worktree est <em>courant</em> dans celui par défaut, cliquez sur <em>Terminer</em>, pour que le worktree par défaut retrouve sa branche et ses modifications. Pour vous déconnecter d’un fournisseur, utilisez <em>Déconnecter</em> sur sa carte dans Réglages › Fournisseurs d’IA : les connexions appartiennent à Claude Code, Codex et Gemini CLI, pas à l’application, donc supprimer l’application ne les ferme pas. Quittez ensuite ygd-editor.',
    '<strong>macOS.</strong> Glissez <strong>ygd-editor</strong> depuis Applications vers la Corbeille — depuis <code>~/Applications</code> si l’installation par le Terminal l’y a mise.',
    '<strong>Windows.</strong> Paramètres › Applications › Applications installées › ygd-editor › <em>Désinstaller</em>, ou Panneau de configuration › Programmes et fonctionnalités.',
    '<strong>Linux.</strong> Supprimez le fichier AppImage. Pour le paquet Debian / Ubuntu : <code>sudo apt remove ygd-editor</code>.',
    '<strong>Ce qui reste.</strong> Vos réglages, espaces de travail, l’historique des sessions et les téléchargements de Codex et Gemini CLI sont dans le dossier <code>.ygd-editor</code> de votre répertoire personnel, et la désinstallation les garde : une réinstallation reprend là où vous en étiez. Pour les supprimer aussi, avec les caches de l’application, lancez ceci après la désinstallation :',
    '<p>macOS:</p><pre>rm -rf ~/.ygd-editor ~/Library/Application\\ Support/ygd-editor ~/Library/Caches/ygd-editor-updater ~/Library/Caches/com.mhguitarte.ygd-editor* ~/Library/HTTPStorages/com.mhguitarte.ygd-editor ~/Library/Preferences/com.mhguitarte.ygd-editor.plist</pre>',
    '<p>Windows (PowerShell):</p><pre>Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\\.ygd-editor", "$env:APPDATA\\ygd-editor", "$env:LOCALAPPDATA\\ygd-editor-updater"</pre>',
    '<p>Linux:</p><pre>rm -rf ~/.ygd-editor ~/.config/ygd-editor ~/.cache/ygd-editor-updater</pre>',
    '<strong>Ce qui n’est jamais touché.</strong> Vos dépôts et les worktrees que vous avez créés sont des dossiers git ordinaires et restent où ils sont ; <code>git worktree remove &lt;dossier&gt;</code> en supprime un. Si l’application a installé Claude Code pour vous, il reste dans votre répertoire personnel : la <a href="https://docs.anthropic.com/en/docs/claude-code">documentation d’Anthropic</a> explique comment le supprimer.',
  ]),
  ('privacy', 'Confidentialité et sécurité', [
    '<p>Tout s’exécute sur votre ordinateur. L’application elle-même se connecte à internet pour deux choses : consulter les versions de ce site à la recherche de mises à jour et, une fois par jour, récupérer sur models.dev la liste publique des modèles et de leurs prix. Les agents parlent à leurs fournisseurs avec vos comptes ; git parle à vos dépôts distants avec vos identifiants. Les jetons de fournisseur que l’application conserve sont stockés dans le trousseau du système d’exploitation. L’interface s’exécute dans un bac à sable, chaque requête qui nomme un chemin est vérifiée par rapport aux dépôts que vous avez réellement ouverts, et aucune commande n’est jamais construite à partir d’une chaîne shell. Le paquet de diagnostic est enregistré là où vous le choisissez et n’est envoyé nulle part.</p>'
    '<p>Pour vérifier qu’un téléchargement est bien le nôtre, voir <a href="{prefix}index.html#genuine">Mon téléchargement est-il authentique ?</a> sur la page de téléchargement.</p>',
  ]),
 ],
 # page des versions et petites chaînes partagées
 'dl_version': 'version {v}',
 'genuine_details': 'les détails techniques',
 'lang_label': 'Langue',
 'title_releases': 'ygd-editor — toutes les versions',
 'r_h1': 'Toutes les versions',
 'r_lead': 'Toutes les versions de ygd-editor qui ont été publiées. D’abord la plus récente pour chaque système, puis tout l’historique, système par système. La page de téléchargement propose toujours la version complète la plus récente ; cette liste est pour qui a besoin d’une version en particulier.',
 'r_latest_h': 'La plus récente pour chaque système',
 'r_all_h': 'Toutes les versions, par système',
 'r_systems': {'mac': 'macOS', 'win': 'Windows', 'linux': 'Linux'},
 'r_loading': 'Chargement des versions…',
 'r_error': 'Impossible de lire la liste des versions ({err}).',
 'r_github': 'Les versions sur GitHub',
 'r_none': 'Aucune version publiée pour l’instant.',
 'r_notes': 'Ce qui a changé',
 'r_checksums': 'Sommes de contrôle',
 'r_updates': 'Les applications installées se mettent à jour toutes seules vers la version complète la plus récente ; rien ici n’a besoin d’être téléchargé à la main, sauf si vous voulez une version en particulier.',
}
