# Italiano. Strings of the download page, the guide and the versions page. HTML fragments and
# {placeholders} stay as they are; keys match tools/strings/en.py, which is the reference.
T = {
 'title_index': 'ygd-editor — download', 'title_guide': 'ygd-editor — guida per l’utente',
 'desc': 'ygd-editor: esegui agenti di programmazione con IA in worktree git separati, rivedi le loro modifiche e pubblicale, tutto da una sola finestra. Gratis per macOS, Windows e Linux.',
 'nav_download': 'Scarica', 'nav_guide': 'Guida', 'nav_releases': 'Tutte le versioni', 'nav_issues': 'Segnala un problema',
 'tagline': 'Dai a ogni compito il suo branch e il suo agente di IA, e tienili tutti sotto controllo.',
 'hero_p': 'ygd-editor apre ogni compito nel suo worktree git, ci esegue dentro un agente di programmazione (Claude Code, Codex o Gemini CLI) e ti lascia rivedere le modifiche, fare commit, push e aprire la pull request senza uscire dalla finestra. Gratis, per macOS, Windows e Linux.',
 'dl_loading': 'Ricerca dell’ultima versione…', 'dl_for': 'Scarica per {label}', 'dl_none': 'Ancora nessuna versione pubblicata', 'dl_none_hint': 'La prima è in arrivo.',
 'dl_error': 'Vedi tutte le versioni', 'dl_error_hint': 'Non è stato possibile leggere l’ultima versione ({err}). Nella pagina delle versioni ci sono tutti i download.',
 'dl_others': 'Altri sistemi:', 'dl_checksums': 'Checksum', 'dl_free': 'Gratis · senza account · si aggiorna da solo',
 'kinds': {'mac-arm64': 'macOS · Apple Silicon (M1 e successivi)', 'mac-x64': 'macOS · Intel', 'win-x64': 'Windows', 'linux-appimage': 'Linux · AppImage', 'linux-deb': 'Linux · Debian / Ubuntu'},
 'shot_console': 'La console: i worktree a sinistra, modifiche e diff al centro, la sessione dell’agente a destra.',
 'what_h': 'Cosa ottieni',
 'what': [
   ('Un worktree per compito', 'Ogni branch ha la sua cartella: gli agenti non si pestano mai i piedi e cambi compito senza mettere niente nello stash.'),
   ('Gli agenti dove sta il codice', 'Avvia Claude Code, Codex o Gemini CLI dentro un worktree, guardalo lavorare, rispondi alle sue domande e passa una sessione a un altro worktree se i piani cambiano.'),
   ('Rivedi e pubblica sul posto', 'Metti i file in stage, leggi il diff, chiedi all’agente di spiegare o modificare una selezione, fai commit, push e apri la pull request dalla stessa schermata.'),
   ('Non ti intralcia', 'Una sola casella per tutte le sessioni che aspettano te e per tutto ciò che l’app ti ha detto, notifiche desktop facoltative e un contatore della spesa di oggi con i limiti che decidi tu.'),
   ('Provalo in più modi', 'Lancia un compito con da due a quattro agenti o modelli insieme, ognuno nel suo worktree, confronta cosa hanno fatto e tieni il migliore.'),
   ('Annulla un turno, non la giornata', 'Ogni turno dell’agente mostra cosa ha cambiato e si può annullare da solo: le tue modifiche e gli altri turni restano.'),
 ],
 'install_h': 'Installazione in un minuto',
 'install_intro': 'Il tuo computer ti avviserà la prima volta. È normale: nessuno ha pagato Apple o Microsoft per un certificato, e l’avviso riguarda quella pratica mancante, non ciò che fa l’app. Ecco come superarlo: una volta sola, e mai più su quel computer.',
 'install': [
   ('macOS', ['Apri il <code>.dmg</code> scaricato. Una finestra mostra questi passaggi nella tua lingua — fai clic su <em>Continua</em> — poi trascina <strong>ygd-editor</strong> in Applicazioni.', 'Aprila. macOS dice che <em>non è stato possibile verificare</em> l’app e offre <em>Sposta nel Cestino</em> o <em>Fine</em>: fai clic su <strong>Fine</strong>.', 'Apri <strong>Impostazioni di Sistema › Privacy e sicurezza</strong>, scorri fino a <em>Sicurezza</em> e fai clic su <strong>Apri comunque</strong> accanto a ygd-editor. Conferma con la tua password. Fatto: macOS non lo chiederà più.', 'Su macOS 14 o precedente, <strong>clic destro sull’app › Apri</strong> fa lo stesso in un passaggio.', 'Non sai che Mac hai? Menu Apple › Informazioni su questo Mac: «Apple M…» è Apple Silicon, se c’è scritto «Intel» è Intel.']),
   ('Windows', ['Esegui l’installer. Quando SmartScreen dice «PC protetto da Windows», fai clic su <strong>Ulteriori informazioni</strong> e poi su <strong>Esegui comunque</strong>.', 'L’autore indicato è <em>ygd-editor release signing</em>: siamo noi. Scegli la cartella di installazione se vuoi e concludi.', 'L’app compare nel menu Start come ygd-editor.']),
   ('Linux', ['<strong>AppImage:</strong> rendilo eseguibile (<code>chmod +x ygd-editor-*.AppImage</code>) ed eseguilo. Se si lamenta di FUSE, avvialo con <code>--appimage-extract-and-run</code>.', '<strong>Debian / Ubuntu:</strong> <code>sudo apt install ./ygd-editor-*.deb</code>, poi cercalo nel menu delle applicazioni.']),
 ],
 'cli_h': 'Senza l’avviso: installala dal Terminale.',
 'cli_p': 'Incolla questo nel Terminale (Applicazioni › Utility). Scarica l’ultima versione per il tuo Mac, controlla che i suoi checksum portino la firma del progetto, che il download corrisponda e che l’app sia firmata con il certificato del progetto, e la mette in Applicazioni. Se un controllo fallisce, non installa nulla. macOS non chiede nulla, perché niente è passato da un browser. Eseguilo di nuovo quando vuoi per reinstallare.',
 'cli_copy': 'Copia', 'cli_copied': 'Copiato',
 'cli_or': 'Oppure, con l’immagine disco del pulsante qui sopra:',
 'need_h': 'Cosa ti serve', 'need_p': 'Git sul tuo computer e un account presso almeno un provider. <a href="https://github.com/openai/codex">Codex</a> e <a href="https://github.com/google-gemini/gemini-cli">Gemini CLI</a> non sono nell’installer — è questo che lo tiene piccolo —: l’app scarica quello che scegli la prima volta che lo chiedi (circa 130–150 MB per Codex, 20 MB per Gemini CLI) e lo verifica contro la versione con cui è stata costruita questa release prima di eseguirlo; per <a href="https://docs.anthropic.com/en/docs/claude-code">Claude Code</a>, la cui licenza non ne consente la distribuzione, Impostazioni › Provider di IA offre un clic che esegue per te l’installer ufficiale di Anthropic. Collegare un provider apre la sua pagina di accesso nel browser. Per le pull request, <code>gh</code> di GitHub o <code>glab</code> di GitLab. L’app funziona su Windows 10 o 11 a 64 bit e su Linux x86-64 con glibc 2.34 o successiva (Ubuntu 22.04, Debian 12, Fedora 35 e successive).',
 'updates_h': 'Gli aggiornamenti si gestiscono da soli',
 'updates_p': 'Poco dopo l’avvio, e ogni sei ore finché resta aperta, l’app cerca una nuova versione e ti avvisa quando c’è. Un clic la scarica, e sei tu a scegliere quando installarla: riavviando subito o la prossima volta che esci. Un aggiornamento si installa solo se i checksum della versione portano la firma del progetto; qualsiasi altro viene rifiutato. Impostazioni › Informazioni e aggiornamenti ha un pulsante «Cerca aggiornamenti» e può scaricare da sola le nuove versioni. Dopo un aggiornamento, «Novità» mostra cosa è cambiato senza uscire dall’app.',
 'genuine_h': 'Il mio download è autentico?',
 'genuine_p': 'Due verifiche indipendenti, e nessuna delle due si basa sulla fiducia in un nome. Non sei obbligato a farle; sono qui per chi vuole.',
 'genuine_sums': '<strong>Checksum firmati.</strong> Ogni versione dalla 0.17.2 arriva con <code>SHA256SUMS.txt</code> e la sua firma, <code>SHA256SUMS.txt.sig</code>, fatta con la chiave del progetto: quella dietro al suo certificato, <a href="{pem}"><code>release-signing.pem</code></a>. Mettili entrambi accanto al file scaricato e confronta prima l’impronta del certificato con questa: è il passaggio che prova tutto il resto, perché chi potesse sostituire un installer potrebbe sostituire anche il certificato accanto. La firma garantisce poi i checksum, e i checksum ogni file. Serve solo <code>openssl</code> (macOS e Linux lo hanno; su Windows usa Git Bash). Devi vedere <code>Verified OK</code>, poi <code>OK</code> per il tuo file:',
 'genuine_prov': '<strong>Versioni precedenti.</strong> Dalla 0.6.0 alla 0.17.1 arrivano con un <code>SHA256SUMS.txt</code> non firmato, e a garantirle è la firma del codice qui sotto. Dalla 0.1.0 alla 0.4.0 sono state prodotte dal flusso di rilascio del progetto su GitHub e portano invece la sua firma <a href="https://www.sigstore.dev/">Sigstore</a>, <code>SHA256SUMS.txt.sigstore.json</code>. Con <code>cosign</code> installato:',
 'genuine_sig': '<strong>Firma del codice.</strong> L’app per macOS e l’installer per Windows sono firmati con il certificato del progetto (<a href="{pem}">chiave pubblica</a>). Confronta l’impronta, non il nome: chiunque può chiamare un certificato come vuole.',
 'guide_cta_h': 'Prima volta qui?', 'guide_cta_p': 'La <a href="{prefix}guide.html">guida per l’utente</a> ripercorre i primi dieci minuti: aprire un repository, creare un worktree, avviare un agente, rivedere e pubblicare il risultato.',
 'footer_made': 'Fatto da Manu Hurtado. L’app è gratuita; il codice sorgente è privato.',
 # guide
 'g_h1': 'Guida per l’utente', 'g_lead': 'Tutto quello che ti serve per il primo pomeriggio con ygd-editor, in parole semplici. Dieci minuti di lettura, e puoi tornare a qualsiasi sezione dall’elenco.',
 'g_toc': 'In questa pagina',
 'g_sections': [
  ('idea', 'L’idea in un minuto', [
    'Un <em>worktree</em> di git è una seconda cartella dello stesso repository, con il checkout di un altro branch. Invece di cambiare branch in un’unica cartella — e ogni volta mettere le modifiche nello stash, ricompilare e perdere il filo — tieni una cartella per compito.',
    'ygd-editor è costruito intorno a questo: il pannello di sinistra elenca i tuoi worktree, quello centrale mostra cosa è cambiato in quello che hai scelto e quello di destra ci esegue dentro un agente di IA. Due agenti su due compiti lavorano in due cartelle e non si scontrano mai. Quando uno aspetta una risposta, la casella delle attese nell’intestazione te lo dice.',
    '<img src="{img}start.png" alt="La pagina iniziale: repository recenti e le azioni per cominciare" loading="lazy">',
  ]),
  ('first', 'I tuoi primi dieci minuti', [
    'In una nuova installazione la pagina iniziale mostra un elenco <em>Per iniziare</em>: git, un provider di IA, un repository, un primo worktree e una prima sessione. Ogni passo ha il pulsante che lo esegue e si spunta da solo quando è fatto; <em>Nascondi questo elenco</em> lo toglie per sempre. Ecco gli stessi passi, con più parole.',
    '<ol>'
    '<li><strong>Apri un repository.</strong> Nella pagina iniziale scegli <em>Apri repository</em> e indica una cartella che ha già git dentro, oppure <em>Clona repository</em> con un URL di GitHub, GitLab o di qualsiasi git. I repository recenti restano nella pagina iniziale.</li>'
    '<li><strong>Crea un worktree.</strong> <em>Nuovo worktree</em> (⌘N) suggerisce un nome di branch a partire dal compito e una cartella dove metterlo; entrambi sono tuoi da rinominare secondo la convenzione che usi. Git non ammette spazi nel nome di un branch, quindi diventano trattini e la finestra ti mostra il risultato prima di creare qualcosa. Dove finiscono i worktree su disco, e un prefisso suggerito facoltativo, stanno in Impostazioni › Git.</li>'
    '<li><strong>Avvia una sessione.</strong> <em>+ Sessione</em> nel pannello di destra sceglie un agente e un modello; l’agente predefinito è in Impostazioni › Agente predefinito. Scrivi quello che vuoi nel compositore. <code>@</code> allega file o contesto come il diff attuale, <code>/</code> esegue i comandi dell’agente, <code>#</code> le sue skill. ⌘↵ invia.</li>'
    '<li><strong>Lascialo lavorare — o fermalo.</strong> La trascrizione mostra ogni strumento che l’agente usa. Quando ha bisogno di un permesso per qualcosa che non hai approvato in anticipo, la sessione passa a <em>in attesa</em>, la casella delle attese nell’intestazione la conta e tu consenti o neghi; «Consenti sempre» ricorda la tua scelta per quel worktree. <em>Ferma</em> interrompe; i messaggi che scrivi mentre lavora vanno in coda.</li>'
    '<li><strong>Rivedi le modifiche.</strong> La scheda Modifiche elenca ogni file toccato e chi lo ha cambiato. Fai clic su un file per il diff; seleziona delle righe e scegli <em>Spiega</em> o <em>Chiedi una modifica</em> per rimandarle all’agente. Un avviso segnala i file che anche un altro worktree dello stesso repository sta toccando.</li>'
    '<li><strong>Commit, push, apri la PR.</strong> Spunta i file da mettere in stage, scrivi il messaggio o <em>Scrivi con l’IA</em>, <em>Commit</em>. <em>Push</em> imposta l’upstream; <em>Apri pull request</em> compila titolo, descrizione (scritta a partire dal diff, se vuoi), bozza, revisori ed etichette, e passa la mano a <code>gh</code> o <code>glab</code>. Il riquadro del worktree mostra poi la PR e i suoi controlli.</li>'
    '</ol>',
    '<img src="{img}console.png" alt="La console con un diff aperto e una sessione di Claude Code in corso" loading="lazy">',
  ]),
  ('daily', 'Nell’uso quotidiano', [
    '<p><strong>Il worktree principale</strong> — la cartella con cui hai aperto il repository — è elencato insieme agli altri ed è quello da cui si diramano i nuovi worktree. Selezionalo e fai clic sul nome del suo branch nell’intestazione: si apre una casella di ricerca su tutti i branch — i tuoi, o uno che esiste solo sul remoto, di cui fa il checkout come nuovo branch di tracciamento. Scrivi per restringere, frecce e Invio per cambiare. Un branch che un altro worktree ha già è elencato ma in grigio, perché git permette un branch in un solo worktree alla volta.</p>'
    '<p><strong>Aggiorna dalla base</strong> su un worktree fa fetch e rebase sul branch di base; i conflitti fermano tutto con l’elenco dei file, li risolvi, li metti in stage e <em>Continua</em>. <strong>Fetch</strong> aggiorna i contatori di commit avanti/indietro. La scheda Terminale è una shell vera nella cartella del worktree; Attività è la cronologia di quello che è successo lì — commit, push, sessioni — e sopravvive ai riavvii.</p>'
    '<p><strong>Passare una sessione.</strong> Una sessione può spostarsi in un altro worktree dal suo menu, trascrizione inclusa, quando ti accorgi che il lavoro appartiene a un altro branch.</p>'
    '<p><strong>Rimuovere un worktree</strong> termina le sue sessioni, archivia i loro log e dimentica le sue regole di permesso; il branch resta, a meno che tu non lo elimini. Da Impostazioni › Git l’app può eliminare il worktree da sola quando la sua PR viene unita.</p>'
    '<p><strong>Più repository.</strong> Aprine quanti ne vuoi; l’intestazione passa dall’uno all’altro e la casella conta le sessioni in attesa di tutti.</p>',
  ]),
  ('git', 'Git senza terminale', [
   '<strong>Pull e Aggiorna dalla base sono due cose diverse.</strong> <em>Pull</em> porta dentro ciò che è stato inviato al tuo branch — il commit di un collega, per esempio — così il tuo prossimo push passa; se entrambi i lati hanno commit nuovi fa rebase o merge come dicono le Impostazioni › Git, oppure chiede. <em>Aggiorna dalla base</em>, nel menu <code>···</code>, è l’altro lavoro: rimettersi in pari con il branch di base.',
   '<strong>Conflitti.</strong> Quando un rebase, un merge, un revert o un cherry-pick si ferma per conflitti, apri il file e risolvilo blocco per blocco: tieni un lato, l’altro o <em>Tieni entrambi</em> — oppure prendi un file intero, o <em>Chiedi all’agente</em>. I due lati hanno il nome di ciò che sta succedendo, così non devi mai indovinare quale sia il «nostro». <em>Segna come risolto</em>, poi <em>Continua</em> sul banner.',
   '<strong>Amend.</strong> La casella del commit ha un interruttore <em>Modifica (amend)</em>. Un commit che non hai inviato viene semplicemente riscritto. Uno già inviato non viene mai forzato: l’app lo mette su un branch nuovo, lo invia, apre una nuova pull request e chiude la vecchia con un link alla nuova.',
   '<strong>Cronologia.</strong> Fai clic destro su un commit in Attività per <em>Copia SHA</em>, <em>Mostra modifiche</em>, <em>Annulla (revert)</em> o <em>Cherry-pick su…</em> un altro worktree.',
   '<strong>Pull request.</strong> La scheda della PR elenca ogni check, il verdetto di ogni revisore e i commenti della revisione con file e riga. <em>Gestisci la revisione</em> passa all’agente i commenti aperti; <em>Unisci</em> offre i metodi che il repository consente e spiega perché quando non si può ancora. Quando il lavoro è entrato, <em>Pulisci i worktree uniti…</em> rimuove in un colpo tutti i worktree finiti e nomina quelli che lascia.',
   '<strong>Fork.</strong> In un fork, <code>origin</code> è la tua copia e <code>upstream</code> il progetto. L’app legge il branch base da <code>upstream</code> ogni volta che esiste, così un nuovo worktree parte da <code>upstream/main</code> e non dalla copia superata del tuo fork, mentre push e pull request vanno ancora al tuo fork; <em>Fetch</em> scarica da entrambi. Impostazioni › Git › <em>Remoto base</em> sceglie un altro remoto, e la finestra Remoti lo segna come <em>base</em>.',
   '<strong>Repository bare.</strong> Un repository si apre per intero da qualsiasi sua cartella: quella principale, un worktree collegato, un <code>api.git</code> bare con i suoi worktree accanto o una struttura <code>proj/.bare</code>. Tutti i worktree vengono elencati. Un repository bare non ha un worktree principale, quindi qualunque worktree si può rimuovere, i nuovi vanno accanto alla cartella bare (<code>api--fix</code>), e <em>Rendi corrente</em> e il cambio di branch del worktree principale non sono disponibili.',
  ]),
  ('review', 'Rivedere cosa ha fatto un agente', [
   '<strong>Un turno alla volta.</strong> Ogni turno che cambia dei file finisce con una riga sotto nella trascrizione — <em>4 file modificati · +120 −8</em>. Fai clic e la scheda Modifiche mostra solo ciò che ha fatto quel turno. <em>Annulla questo turno…</em> prima elenca cosa succederà a ogni file, poi toglie le modifiche del turno: un file che nessuno ha più toccato torna com’era, uno che hai modificato tu o un turno successivo conserva quelle modifiche, e dove entrambi hanno cambiato le stesse righe restano marcatori di conflitto da risolvere. L’annullamento è un turno a sé, quindi si può annullare anche lui.',
   '<strong>Blocco per blocco.</strong> Ogni blocco di un diff ha <em>Metti in stage</em> e <em>Scarta</em> (<em>Togli dallo stage</em> una volta in stage); seleziona alcune righe per mettere in stage o scartare solo quelle. Un file in stage a metà ha un selettore <em>In stage / Fuori stage</em> sopra il diff.',
   '<strong>Ritrovare una vecchia conversazione.</strong> <em>Cerca nelle sessioni</em>, in cima al pannello delle sessioni, cerca in ciò che è stato detto in questo worktree, nel repository o nel workspace — e, se spunti <em>archiviate</em>, nei worktree che hai già rimosso. Un risultato apre la sessione su quel messaggio. Fai clic destro su una sessione per <em>Esporta la trascrizione…</em>: un file Markdown con i prompt, le risposte e le chiamate agli strumenti. Non viene nascosto nulla, quindi leggilo prima di condividerlo.',
   '<strong>Leggere una modifica lunga.</strong> L’elenco delle Modifiche raggruppa i file per cartella — il pulsante cartella accanto al filtro passa a un elenco semplice — e il filtro tiene i percorsi che contengono tutte le parole che scrivi. Spunta <em>Visto</em> (V) su ogni file che hai letto: la spunta se ne va da sola se l’agente modifica di nuovo quel file, e <em>Prossimo non visto</em> (⇧N) ti porta al successivo. Nel diff, N e P saltano da un blocco all’altro e W manda a capo le righe lunghe. Le parole cambiate sono evidenziate dentro la riga, il codice è colorato secondo il linguaggio, la vista affiancata diventa unificata quando il pannello è stretto, le immagini si vedono prima e dopo, e un file Markdown può essere mostrato <em>Visualizzato</em>.',
   '<strong>Scartato per errore?</strong> <em>Scarta</em>, <em>Scarta tutte le modifiche</em>, scartare un blocco o alcune righe e la rimozione forzata di un worktree conservano ciò che buttano via. L’<em>Annulla</em> dell’avviso lo riporta indietro; più tardi, <em>Stash › Scartati di recente</em> ha <em>Ripristina</em>, e <em>Salva come stash</em> trasforma una voce in uno stash normale — la strada per recuperare le modifiche di un worktree che hai rimosso. Anche <em>Metti tutte le modifiche nello stash</em> offre Annulla.',
   '<strong>Repository grandi.</strong> Con più di 2.000 file non tracciati l’elenco mostra i primi 2.000 e una riga per cartella che conta il resto; <em>Tutto in stage</em>, <em>Commit</em> e <code>.gitignore</code> li coprono comunque tutti. I file non tracciati oltre i 10 MB restano fuori dai punti di ripristino dei turni, e il piè del turno dice quanti sono. Se leggere il worktree richiede più di 5 secondi, il turno resta senza punto di ripristino e il suo piè dice che non si può aprire né annullare. Le modifiche dentro <code>node_modules</code>, <code>dist</code>, <code>.next</code> e <code>target</code> non aggiornano più l’elenco, e le modifiche fatte fuori dall’app compaiono anche durante un push o un fetch lunghi.',
  ]),
  ('sessions', 'Agenti al lavoro', [
   '<strong>Leggere la trascrizione.</strong> Le risposte appaiono come testo formattato, e ogni blocco di codice ha un pulsante <em>Copia</em>. Tre o più chiamate agli strumenti di fila si raccolgono in una riga che si apre per mostrarle. Un percorso verso un file del worktree è un link: un file modificato apre il suo diff, gli altri si aprono nel tuo editor. Scorri in su per leggere e la trascrizione smette di seguire; <em>Vai agli ultimi</em> ti riporta in fondo. Se una sessione è stata fermata mentre chiedeva un permesso, la trascrizione lo dice.',
   '<strong>Sessioni lunghe.</strong> Una sessione si apre sugli ultimi messaggi, e <em>Mostra i messaggi precedenti</em> carica il resto quando ti serve. Perché la cronologia non cresca all’infinito, Impostazioni › Agente predefinito ha <em>Conserva le sessioni per</em> (giorni) e <em>Spazio massimo per le sessioni</em> (MB): all’avvio l’app elimina ciò che è più vecchio o supera il limite. Sono entrambi disattivati finché non li imposti.',
   '<strong>Fermare ferma davvero.</strong> <em>Ferma</em>, la rimozione di un worktree e l’uscita dall’app chiudono anche ciò che l’agente ha avviato — un server di sviluppo, per esempio. Cambiare modello no, e nemmeno il limite di inattività: Impostazioni › Agente predefinito › <em>Termina gli agenti inattivi dopo</em> (30 minuti se non lo cambi; vuoto vuol dire mai) chiude un agente rimasto inattivo così a lungo per liberarne la memoria, e il tuo prossimo prompt riprende la conversazione. Se l’app si è chiusa di colpo con degli agenti ancora in esecuzione, all’avvio successivo propone <em>Ferma</em> o <em>Lascia in esecuzione</em>.',
   '<strong>L’ambiente della tua shell.</strong> Gli agenti ricevono ciò che esportano il tuo <code>.zshrc</code> o il tuo <code>.bashrc</code> — un proxy, chiavi API, <code>AWS_PROFILE</code> — come se li avessi avviati da un terminale, anche quando l’app è stata aperta dal Dock o da un menu. Impostazioni › Editor e terminale › <em>Usa l’ambiente della mia shell</em> lo disattiva ed elenca i nomi delle variabili che porta, mai i loro valori. Su Windows non serve: lì le app ricevono già le tue variabili.',
  ]),
  ('setup', 'Worktree pronti a partire', [
   'Un worktree nuovo non ha nessuno dei tuoi file ignorati: niente <code>.env</code>, niente <code>node_modules</code>. <strong>Impostazioni › Preparazione dei worktree</strong> lo sistema una volta per tutte: file da copiare dal worktree principale (<code>.env*</code>, per esempio), comandi da eseguire nel terminale del nuovo worktree (<code>pnpm install</code>) e una porta base, così ogni worktree ha la sua porta in <code>YGD_PORT</code> e due server di sviluppo smettono di litigarsi la stessa. Il terminale del worktree e i suoi agenti ricevono anche <code>YGD_WORKTREE</code> e <code>YGD_BRANCH</code>. La finestra Nuovo worktree mostra cosa farà la preparazione; <em>Esegui di nuovo la preparazione</em> è nel menu <code>···</code>.',
   'Un repository può portare la stessa ricetta in <code>.ygd/worktree.json</code>. I suoi comandi vengono da chi ha scritto il branch, quindi l’app te li mostra e chiede prima di eseguirli la prima volta — e di nuovo ogni volta che il file cambia.',
  ]),
  ('terminals', 'Terminali', [
   '<strong>Più terminali.</strong> <code>+</code> nella scheda Terminale apre un’altra shell accanto a quella del worktree; doppio clic su una scheda per rinominarla. <em>Esegui ▾</em> nella barra degli strumenti avvia comandi salvati — <code>dev: pnpm dev</code> — ognuno in un terminale con il suo nome, con <em>Riavvia</em> e <em>Ferma</em>. <code>@terminal:dev</code> in un prompt allega ciò che quel terminale ha stampato.',
   '<strong>Restano in esecuzione.</strong> Un terminale conserva il suo programma e la sua cronologia mentre sono aperti le Impostazioni, la pagina iniziale o il confronto, così <code>vim</code>, <code>htop</code> o un server di sviluppo restano esattamente come li hai lasciati. ⌘F (Ctrl+Maiusc+F su Windows e Linux), o la lente in fondo alle schede, cerca nella cronologia. ⌘-clic (Ctrl+clic) apre un link nel browser. ⌘⇧] e ⌘⇧[ (Ctrl+PagGiù e Ctrl+PagSu) passano al terminale successivo e al precedente. Chiudere un terminale che sta ancora eseguendo qualcosa chiede prima conferma e dice di quale programma si tratta.',
  ]),
  ('tryn', 'Provalo in più modi', [
   'Non sai quale agente o modello farà meglio un compito? Spunta <em>Prova in N modi</em> nella finestra Nuovo worktree e scegli da due a quattro tentativi — Claude Code, Codex e Gemini CLI, oppure lo stesso modello tre volte. Ognuno ha il suo worktree dalla stessa base (<code>login-a</code>, <code>login-b</code>…), la preparazione gira in ciascuno e lo stesso primo prompt va a tutti. Ogni tentativo conta nel tuo budget, e la finestra lo dice.',
   'I tentativi stanno insieme nella barra laterale. Fai clic sulla loro voce per confrontarli fianco a fianco: stato, file e righe modificati, costo, turni e tempo, un diff rapido e il tuo comando di verifica — <code>pnpm test</code>, per esempio, da Impostazioni › Preparazione dei worktree — eseguito in ciascuno quando vuoi. <em>Tieni questo</em> rimuove gli altri dopo averli elencati, può dare al vincitore il nome di branch senza suffisso e può passare subito a Rendi corrente o a una pull request.',
  ]),
  ('workspaces', 'Lavorare su più repository: gli spazi di lavoro', [
    'Uno <em>spazio di lavoro</em> è un insieme di cartelle con un nome che l’app tiene aperte insieme. Un gateway, una console web e una cartella di appunti sono spesso un unico lavoro, e una domanda su una di esse trova di solito risposta in un’altra: lo spazio di lavoro è il modo in cui dici all’app che vanno insieme.',
    '<img src="{img}workspace.png" alt="Uno spazio di lavoro con due repository: la barra laterale raggruppa i worktree per repository" loading="lazy">',
    '<strong>Crearne uno.</strong> Apri un secondo repository mentre ne hai già uno aperto e l’app ti chiede dove va: aggiungerlo a quello su cui stai lavorando, creare un nuovo spazio di lavoro con entrambi, o aprirlo da solo. Esc vuol dire «da solo». Puoi anche crearne uno dalla pagina iniziale con <em>Nuovo spazio di lavoro</em>, e aggiungere o togliere cartelle in seguito dal pulsante degli spazi di lavoro nell’intestazione. Togliere una cartella da uno spazio di lavoro non elimina mai nulla: cambia solo l’insieme.',
    '<strong>Da VS Code.</strong> Se il tuo team ha già un file <code>.code-workspace</code>, <em>Apri file dello spazio di lavoro…</em> lo legge: le stesse cartelle, nello stesso ordine, con i nomi che dà loro VS Code. Commenti e virgole finali nel file non sono un problema. Le cartelle che non sono repository git vengono mantenute — semplicemente non hanno worktree — e una cartella che non c’è più viene segnalata invece di sparire in silenzio. <em>Salva su file</em> lo riscrive lasciando intatte le parti che l’app non usa, così lo stesso file continua a funzionare in entrambi gli strumenti.',
    '<strong>Cosa mostra la barra laterale.</strong> I worktree raggruppati per repository, ogni gruppo ripiegabile, con il filtro che cerca sia nel nome del branch sia in quello del repository, così trovi un branch senza ricordarti dove vive. Un gruppo ripiegato mostra comunque cosa sta girando al suo interno e continua ad avvisarti quando una sessione è in attesa. Con un solo repository non ci sono gruppi.',
    '<strong>Cosa vedono gli agenti.</strong> Una sessione continua a girare <em>dentro</em> il suo worktree — è lì che stanno git e ogni percorso relativo — ma può leggere anche le altre cartelle dello spazio di lavoro, così «dove finisce questa chiamata?» ha una risposta da entrambi i lati. Una sessione che può solo leggere continua a poter solo leggere, ovunque. C’è anche una riga sopra i gruppi, <em>Su tutto lo spazio di lavoro</em>, per le sessioni che non appartengono a nessun worktree in particolare: a quelle fai le domande che attraversano tutto lo stack. Non hanno branch, né modifiche, né terminale, perché quelli appartengono a un worktree.',
    '<strong>Impostazioni.</strong> Ora i livelli sono tre: Globale, lo spazio di lavoro, poi il singolo repository. L’agente predefinito, la preimpostazione dei permessi e il branch di base sono di solito una proprietà dello stack più che di ogni repository al suo interno, quindi impostali una volta sullo spazio di lavoro; un repository che ha bisogno di qualcosa di diverso può comunque sovrascriverli. Il selettore di ambito nelle Impostazioni sceglie il livello, e una sezione che non sta sovrascrivendo nulla ti dice da dove arrivano i suoi valori.',
    'L’app ricorda ogni spazio di lavoro separatamente: quando torni a uno, ritrovi il repository, il worktree e la disposizione dei pannelli in cui lo avevi lasciato.',
  ]),
  ('current', 'Provare un worktree in quello predefinito', [
    'Il posto per provare una modifica è la cartella del repository stesso — il <em>worktree predefinito</em> — perché lì ci sono già <code>node_modules</code>, <code>.env</code>, la cache di build e il server di sviluppo. Il lavoro si fa negli altri worktree. <strong>Rendi corrente</strong> ne porta uno nel worktree predefinito: i suoi commit, ciò che non ha ancora committato e i suoi file nuovi, sopra il branch del worktree predefinito. Da allora l\'intestazione dice, in ogni schermata, cosa esegue il worktree predefinito — <code>PREDEFINITO · feat-a + feat-b · 1 modifica</code> — e la barra laterale contrassegna il worktree <em>predefinito</em> e quelli <em>correnti</em>.',
    '<img src="{img}current.png" alt="La striscia dell\'intestazione, aperta: da dove veniva il worktree predefinito, i due worktree correnti e cosa si può fare dopo" loading="lazy">',
    '<strong>Scambia</strong> mette un altro worktree al suo posto. <strong>Aggiungi</strong> ne impila un altro sopra, per provare due modifiche insieme; dove entrambi toccano le stesse righe il caricamento si ferma su un conflitto nel worktree predefinito, e per ogni file tieni il lato predefinito, prendi quello in arrivo o lo modifichi e lo segni risolto — poi <em>Continua</em>, oppure <em>Annulla</em> per tornare a ciò che girava prima.',
    '<strong>Le correzioni fatte durante i test tornano a casa.</strong> Se tu — o un agente nel worktree predefinito — correggi qualcosa mentre provi, <em>Rimanda le modifiche</em> lo restituisce al worktree a cui appartiene, come modifiche non committate da rivedere e committare lì; <em>Annulla</em> lo riporta indietro fino al passo successivo. Un file che appartiene a più worktree correnti, o a nessuno, viene chiesto invece che indovinato. Scambia, Aggiungi, Aggiorna e Termina rimandano prima le modifiche, così nulla di ciò che è stato fatto nel worktree predefinito va perso. <em>Rimanda le modifiche</em>, <em>Termina</em> e <em>Annulla questo turno</em> scrivono i file come farebbe un checkout — Git LFS, git-crypt e fine riga di Windows compresi; se manca un filtro che il repository richiede (<code>git-lfs</code> non installato, per esempio), si fermano con il messaggio di git invece di lasciare file puntatore.',
    '<strong>Termina</strong> restituisce il worktree predefinito esattamente com\'era: il suo branch e le sue modifiche, in stage e non. Ogni passo apre prima una breve anteprima: cosa entra, cosa viene messo da parte, quali file andrebbero in conflitto e cosa lo impedisce adesso, con la via d\'uscita. Li trovi nel menu <code>···</code> di un worktree, con il tasto destro nella barra laterale, nella striscia dell\'intestazione e con ⌘⇧D / ⌘⇧E.',
    'Impostazioni › Git può aggiornare da solo un worktree corrente quando il suo agente continua a lavorare, ed eseguire un comando dopo ogni caricamento — <code>pnpm install</code> quando è cambiato <code>pnpm-lock.yaml</code>, per esempio — nel terminale del worktree predefinito, dove lo vedi. Il tuo <code>git stash</code> non viene mai toccato. Serve git 2.40 o successivo.',
  ]),
  ('find', 'Muoversi in fretta, e quanto è costato', [
   '<strong>⌘K</strong> apre la tavolozza dei comandi: ogni azione dell’app — con la sua scorciatoia, o il motivo per cui ora non si può eseguire — più i tuoi worktree in tutto il workspace, le sessioni, le pagine delle Impostazioni e i repository recenti. Inizia con <code>&gt;</code> per le azioni, <code>@</code> per i worktree, <code>#</code> per le sessioni; frecce e Invio fanno il resto.',
   '<strong>Quanto è costato.</strong> Impostazioni › Budget ha un <em>Rapporto di utilizzo</em>: una barra al giorno divisa per agente e quanto ha speso ogni repository e ogni branch, negli ultimi 7, 30 o 90 giorni o nelle date che scegli, con <em>Esporta CSV</em>. Le cifre sono quelle del budget stesso, quindi coincidono sempre con il contatore della spesa.',
  ]),
  ('providers', 'Agenti e provider', [
    '<p>ygd-editor non parla da solo con nessun servizio di IA. Esegue gli strumenti a riga di comando che hai già — <a href="https://docs.anthropic.com/en/docs/claude-code">Claude Code</a>, <a href="https://github.com/openai/codex">Codex</a>, <a href="https://github.com/google-gemini/gemini-cli">Gemini CLI</a> — con i tuoi account, quindi utilizzo, fatturazione e condizioni sui dati sono esattamente quelle che hai accettato con quei provider.</p>'
    '<p>Impostazioni › Provider di IA collega ogni provider con il tuo account: <em>Collega</em> apre la pagina di accesso del provider nel browser, e il riquadro mostra poi l’account, il piano e <em>Cambia account</em> / <em>Scollega</em> / <em>Prova la connessione</em>. Codex e Gemini CLI li scarica l’app la prima volta che li scegli — la scheda indica versione e dimensione, mostra l’avanzamento e <em>Rimuovi download</em> lo toglie di nuovo —; se hai una tua copia installata, l’app usa quella. La licenza di Claude Code non ne consente la distribuzione, quindi il suo riquadro offre <em>Installa Claude Code</em>, che esegue l’installer ufficiale di Anthropic nel terminale del riquadro, nella tua cartella personale, senza password di amministratore. L’agente e il modello predefiniti, e la preimpostazione dei permessi, possono cambiare da repository a repository.</p>',
    '<p>La scheda dice anche quando la CLI installata è più nuova o più vecchia delle versioni con cui questa release è stata verificata. Le sessioni funzionano comunque; la nota serve a spiegare un report incompleto. Quando Codex perde la connessione e riprova, la trascrizione mostra una breve nota <em>Riconnessione…</em> invece di un errore.</p>',
  ]),
  ('permissions', 'Permessi', [
    '<p>Gli agenti chiedono prima di fare ciò che non hai approvato in anticipo. Impostazioni › Permessi ha tre preimpostazioni — <em>rigorosa</em> (sola lettura), <em>bilanciata</em> (leggere e modificare file, chiedere per tutto il resto) e <em>yolo</em> (anche eseguire comandi, usare il web e fare push) — più interruttori singoli per lettura, modifica, esecuzione di comandi, accesso al web, push ed eliminazione. Qualunque sia la preimpostazione, un agente non può mai eliminare senza chiedere, a meno che tu non lo attivi.</p>'
    '<p>Quando arriva una richiesta, <em>Consenti</em> e <em>Nega</em> rispondono una volta; <em>Consenti sempre</em> ricorda quello strumento per quel worktree, e la regola sparisce insieme al worktree.</p>',
    '<p>Quando un agente chiede più cose insieme, le richieste si mettono in coda sulla scheda della sessione e nella casella — <em>1 di 3</em> — e tu rispondi nell’ordine. Impostazioni › Permessi › <em>Regole consentite</em> elenca ogni «Consenti sempre» per worktree, con la data in cui è stata aggiunta; <em>Revoca</em> ha effetto subito, anche in una sessione in corso. <em>Nega automaticamente dopo</em> (minuti, disattivato di default) rifiuta una richiesta a cui nessuno risponde e dice all’agente perché. Codex e Gemini CLI non possono chiedere, quindi la loro barra dell’agente mostra la modalità sandbox che gli danno i tuoi interruttori; un clic lì apre Impostazioni › Permessi.</p>',
  ]),
  ('notifications', 'Notifiche, casella e budget', [
    '<p>Impostazioni › Notifiche sceglie quando l’app ti avvisa: quando una sessione è in attesa, quando una finisce e quando cambia una pull request — controlli conclusi, approvata, modifiche richieste, unita. Le pull request di tutti i worktree sono seguite in background, quindi lo sai entro circa cinque minuti anche per un worktree che non stai guardando; un merge scoperto così mantiene la proposta di rimuovere il worktree finché non rispondi. Le notifiche compaiono solo mentre la finestra non è in primo piano, un clic su una porta alla sessione, e il badge nel Dock o nella barra delle applicazioni può contare le sessioni in attesa.</p>',
    '<p>La casella nell’intestazione ha due schede. <em>Richiede input</em> sono le sessioni che aspettano te. <em>Attività</em> è tutto ciò che l’app ti ha detto — turni conclusi, cambi nelle pull request, errori con l’output completo di git, gli avvisi che ti sono sfuggiti — e un clic su una riga ti porta alla sua sessione o al suo worktree. Le righe non lette vengono contate, <em>Segna tutto come letto</em> le azzera, e le 200 più recenti restano tra un riavvio e l’altro.</p>',
    '<p>La barra del budget in fondo al pannello di sinistra è la spesa di oggi su tutte le sessioni. Quando un agente riporta il proprio costo, quella è la cifra; altrimenti i suoi token sono valutati al prezzo di listino del modello, e le tariffe in Impostazioni › Budget servono solo per i modelli che non ne hanno uno. Il riquadro dell’utilizzo e il suggerimento sul costo di una sessione dicono quale dei casi è. Impostazioni › Budget fissa anche un limite giornaliero e uno per sessione e una soglia di avviso; con <em>Metti in pausa le sessioni al limite</em> attivo, raggiungere il limite giornaliero ferma anche i turni ancora in corso, e un avviso dice quanti.</p>',
  ]),
  ('settings', 'Impostazioni', [
    '<p>Le Impostazioni (⌘,) sono raggruppate per argomento. Aspetto imposta tema, colore di accento, densità e caratteri; Lingua cambia l’interfaccia tra inglese, spagnolo, italiano, polacco, francese, tedesco e turco. Diverse sezioni portano l’etichetta <em>per repo</em>: con un repository selezionato in alto puoi sovrascriverle solo per quel repository. Date, orari, numeri e costi seguono la lingua che scegli, non quella del sistema.</p>'
    '<p>Tutto si salva automaticamente in <code>settings.json</code>, nella cartella dell’app dentro la tua cartella personale; <em>Apri settings.json</em> modifica il file grezzo con validazione, e l’intestazione mostra quando è stato scritto l’ultima volta. Il file indica il suo <a href="https://mhguitarte.github.io/ygd-editor/settings.schema.json">schema</a>, così un editor come VS Code lo completa e lo controlla quando lo modifichi a mano. Ogni salvataggio conserva il file precedente come <code>settings.json.bak</code>; se il file si danneggia, l’app usa quella copia e te lo dice. Una versione più vecchia dell’app non sovrascrive mai un file scritto da una più nuova: usa i valori predefiniti e rifiuta di salvare le impostazioni finché non aggiorni di nuovo. Workspace, casella ed elenchi delle sessioni sono conservati allo stesso modo.</p>',
    '<p><em>Cerca nelle impostazioni</em>, in alto, trova qualsiasi riga dal nome o da quello che fa: scrivi «limite budget» e si apre Budget con il cursore in Limite giornaliero; anche ⌘K trova le impostazioni. Una riga che hai cambiato mostra un punto e il suo <em>Ripristina</em>. I campi numerici rifiutano un valore che l’app non potrebbe usare, dicono perché e tengono quello salvato.</p>',
    '<img src="{img}settings.png" alt="Impostazioni › Aspetto" loading="lazy">',
  ]),
  ('layout', 'Finestre piccole e tastiera', [
   '<strong>Finestre piccole.</strong> La finestra scende fino a 900 × 680, così l’app sta accanto a un editor su un portatile da 13 o 14 pollici. Sotto i 1.180 pixel circa di larghezza il pannello delle sessioni si riduce a una barra sottile, e sotto i 1.000 circa lo fa anche l’elenco dei worktree. Fai clic sulla barra per aprire il suo pannello sopra il centro; Esc, o un clic accanto, lo richiude. La disposizione salvata non viene toccata: allarga la finestra e i pannelli tornano com’erano.',
   '<strong>Dalla tastiera.</strong> Ogni elenco — worktree, sessioni, schede del terminale, sezioni delle Impostazioni, repository recenti — è una sola fermata del Tab. ↑ e ↓ (← e → sulle schede del terminale), Home e Fine si muovono lungo l’elenco, Invio o Spazio scelgono una riga, il tasto Menu o Maiusc+F10 apre il suo menu, e F2 rinomina una scheda del terminale.',
   '<strong>Le domande sono dell’app.</strong> Tutto ciò che richiede un sì — scartare, eliminare uno stash, unire una pull request — chiede in una finestra dell’app stessa, nella tua lingua, con l’azione scritta sul pulsante; Esc vuol dire no. Clona, Passa la sessione e Remoti chiedono prima di buttare via quello che vi hai scritto.',
  ]),
  ('updates', 'Aggiornamenti', [
    '<p>Poco dopo l’avvio, e ogni sei ore finché resta aperta, l’app controlla le versioni pubblicate su questo sito e ti avvisa quando ce n’è una nuova. Un clic la scarica; con Impostazioni › Informazioni e aggiornamenti › <em>Scarica gli aggiornamenti automaticamente</em> attivo, si scarica appena viene trovata. Non si installa nulla finché non scegli: <em>Riavvia e aggiorna</em> subito, <em>Riavvia più tardi</em> — allora si installa quando esci — oppure <em>Scarta</em>.</p>',
    '<p>Un aggiornamento si installa solo se i checksum firmati della versione lo elencano, verificati con il certificato incluso nell’app. Altrimenti l’app dice che l’aggiornamento non è firmato dal progetto e non installa nulla. Impostazioni › Informazioni e aggiornamenti ha anche <em>Proponi gli aggiornamenti</em>, che spegne i controlli, e <em>Cerca aggiornamenti</em> con l’ora dell’ultimo controllo.</p>',
    '<p>Il primo avvio dopo un aggiornamento dice che versione hai, e il suo <em>Novità</em> apre le note di rilascio dentro l’app. Le aprono anche Impostazioni › Informazioni e aggiornamenti e la palette dei comandi.</p>',
  ]),
  ('shortcuts', 'Scorciatoie da tastiera', [
    '<table><tr><td>⌘O</td><td>Apri repository</td></tr><tr><td>⇧⌘C</td><td>Clona repository</td></tr><tr><td>⌘N</td><td>Nuovo worktree</td></tr><tr><td>⌘K</td><td>Tavolozza dei comandi</td></tr><tr><td>⌘,</td><td>Impostazioni</td></tr><tr><td>⌘↵</td><td>Invia messaggio</td></tr><tr><td>⌘F</td><td>Cerca nel terminale</td></tr><tr><td>⌘⇧] ⌘⇧[</td><td>Terminale successivo / precedente</td></tr><tr><td>⇧N</td><td>Prossimo file non visto</td></tr></table>'
    '<p>Su Windows e Linux leggi ⌘ come Ctrl, tranne nel terminale: lì la ricerca è Ctrl+Maiusc+F e Ctrl+PagGiù / Ctrl+PagSu cambiano terminale. La maggior parte delle scorciatoie si cambia in Impostazioni › Scorciatoie da tastiera.</p>',
  ]),
  ('trouble', 'Quando qualcosa va storto', [
    '<p><strong>macOS dice che non è stato possibile verificare l’app (Sposta nel Cestino / Fine).</strong> Fai clic su Fine, poi Impostazioni di Sistema › Privacy e sicurezza › scorri fino a Sicurezza › <em>Apri comunque</em>, e conferma con la tua password. Su macOS 14 o precedente, clic destro › Apri lo fa in un passaggio. Se si rifiuta ancora, nel Terminale: <code>xattr -d com.apple.quarantine /Applications/ygd-editor.app</code>. Se dice che l’app è <em>danneggiata</em>, il download si è corrotto: scaricala di nuovo e confrontala con <code>SHA256SUMS.txt</code>.</p>'
    '<p><strong>Evitare del tutto l’avviso.</strong> Installala dal Terminale: <code>curl -fsSL https://mhguitarte.github.io/ygd-editor/install.sh | bash</code>. Controlla il download come avrebbe fatto macOS e mette l’app in Applicazioni; vedi la pagina di download.</p>'
    '<p><strong>Windows blocca l’installer.</strong> SmartScreen › Ulteriori informazioni › Esegui comunque. L’autore deve risultare <em>ygd-editor release signing</em>.</p>'
    '<p><strong>L’AppImage non si avvia.</strong> Eseguilo con <code>--appimage-extract-and-run</code>, oppure installa <code>libfuse2</code>.</p>'
    '<p><strong>Un provider risulta «Non installato».</strong> Codex e Gemini CLI si scaricano su richiesta: premi <em>Scarica</em> sulla scheda; se il download fallisce, la scheda dice perché (offline, oppure un file che non corrispondeva al suo checksum ed è stato scartato). Per Claude Code, fai clic su <em>Installa Claude Code</em> nel suo riquadro; se lo hai installato tu, apri un terminale, verifica che <code>claude --version</code> funzioni, poi Impostazioni › Provider di IA › Ripeti la ricerca.</p>'
    '<p><strong>Errori di git.</strong> L’app spiega quelli più comuni in una frase — credenziali, un remoto andato avanti, un file di lock, un albero con modifiche, conflitti — e conserva l’output completo nel terminale del worktree.</p>'
    '<p><strong>Non compare nessun aggiornamento.</strong> Controlla Impostazioni › Informazioni e aggiornamenti › Proponi gli aggiornamenti, poi Cerca aggiornamenti; l’app deve poter raggiungere github.com.</p>'
    '<p><strong>Un aggiornamento è stato rifiutato perché non firmato dal progetto.</strong> Non è stato installato nulla. Scarica l’installer da <a href="{prefix}releases.html">Tutte le versioni</a> e verificalo come spiega <a href="{prefix}index.html#genuine">Il mio download è autentico?</a>.</p>'
    '<p><strong>Le impostazioni non si salvano dopo essere tornati a una versione precedente.</strong> L’app più vecchia lascia stare i file scritti da quella più nuova, usa i valori predefiniti e dice di quale file si tratta. Aggiorna di nuovo e ritrovi tutto com’era.</p>'
    '<p><strong>Segnalare un problema.</strong> Impostazioni › Diagnostica mostra ciò che serve a una segnalazione: le versioni dell’app, di git e di ogni CLI degli agenti, il PATH che ricevono gli agenti, i processi degli agenti in corso e un log in tempo reale che puoi filtrare. <em>Livelli di log</em> stabilisce quanto registrare — <code>info, git=debug</code> registra git nei dettagli. <em>Prepara pacchetto…</em> raccoglie tutto in uno zip ed elenca ogni file perché tu lo legga prima di <em>Salva zip…</em>: token e chiavi API sono mascherati, ciò che hai scritto ad agenti e terminali resta fuori, e la tua cartella home appare come <code>~</code>. Allegalo a <a href="https://github.com/{repo}/issues">una issue</a> raccontando cosa hai fatto, cosa ti aspettavi e cosa è successo.</p>',
  ]),
  ('uninstall', 'Disinstallare', [
    '<strong>Prima di rimuoverla</strong> — entrambe le cose sono facoltative. Se c’è un worktree <em>corrente</em> in quello predefinito, fai clic su <em>Termina</em>, così il worktree predefinito riavrà il suo branch e le sue modifiche. Per uscire da un provider, usa <em>Scollega</em> sul suo riquadro in Impostazioni › Provider di IA: gli accessi appartengono a Claude Code, Codex e Gemini CLI, non all’app, quindi rimuovere l’app non li chiude. Poi esci da ygd-editor.',
    '<strong>macOS.</strong> Trascina <strong>ygd-editor</strong> da Applicazioni al Cestino — da <code>~/Applications</code> se l’installazione dal Terminale l’ha messa lì.',
    '<strong>Windows.</strong> Impostazioni › App › App installate › ygd-editor › <em>Disinstalla</em>, oppure Pannello di controllo › Programmi e funzionalità.',
    '<strong>Linux.</strong> Elimina il file AppImage. Per il pacchetto Debian / Ubuntu: <code>sudo apt remove ygd-editor</code>.',
    '<strong>Cosa resta.</strong> Le impostazioni, gli spazi di lavoro, la cronologia delle sessioni e i download di Codex e Gemini CLI stanno nella cartella <code>.ygd-editor</code> della tua cartella personale, e la disinstallazione li conserva: reinstallando riprendi da dove avevi lasciato. Per eliminarli, insieme alle cache dell’app, esegui questo dopo la disinstallazione:',
    '<p>macOS:</p><pre>rm -rf ~/.ygd-editor ~/Library/Application\\ Support/ygd-editor ~/Library/Caches/ygd-editor-updater ~/Library/Caches/com.mhguitarte.ygd-editor* ~/Library/HTTPStorages/com.mhguitarte.ygd-editor ~/Library/Preferences/com.mhguitarte.ygd-editor.plist</pre>',
    '<p>Windows (PowerShell):</p><pre>Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\\.ygd-editor", "$env:APPDATA\\ygd-editor", "$env:LOCALAPPDATA\\ygd-editor-updater"</pre>',
    '<p>Linux:</p><pre>rm -rf ~/.ygd-editor ~/.config/ygd-editor ~/.cache/ygd-editor-updater</pre>',
    '<strong>Cosa non viene mai toccato.</strong> I tuoi repository e i worktree che hai creato sono normali cartelle git e restano dove sono; <code>git worktree remove &lt;cartella&gt;</code> ne rimuove uno. Se l’app ha installato Claude Code per te, resta nella tua cartella personale: la <a href="https://docs.anthropic.com/en/docs/claude-code">documentazione di Anthropic</a> spiega come rimuoverlo.',
  ]),
  ('privacy', 'Privacy e sicurezza', [
    '<p>Tutto gira sul tuo computer. L’app in sé si collega a internet per due cose: controllare le versioni pubblicate su questo sito in cerca di aggiornamenti e, una volta al giorno, scaricare da models.dev l’elenco pubblico dei modelli e dei loro prezzi. Gli agenti parlano con i loro provider con i tuoi account; git parla con i tuoi remoti con le tue credenziali. I token dei provider che l’app conserva stanno nel portachiavi del sistema operativo. L’interfaccia gira in una sandbox, ogni richiesta che nomina un percorso viene verificata rispetto ai repository che hai davvero aperto, e nessun comando viene mai costruito a partire da una stringa di shell. Il pacchetto di diagnostica viene salvato dove scegli tu e non viene inviato da nessuna parte.</p>'
    '<p>Per verificare che un download sia davvero nostro, vedi <a href="{prefix}index.html#genuine">Il mio download è autentico?</a> nella pagina di download.</p>',
  ]),
 ],
 # versions page and small shared strings
 'dl_version': 'versione {v}',
 'genuine_details': 'i dettagli tecnici',
 'lang_label': 'Lingua',
 'title_releases': 'ygd-editor — tutte le versioni',
 'r_h1': 'Tutte le versioni',
 'r_lead': 'Tutte le versioni di ygd-editor pubblicate finora. Prima la più recente per ogni sistema, poi la cronologia completa, sistema per sistema. La pagina di download offre sempre la versione completa più recente; questo elenco è per chi ne ha bisogno di una in particolare.',
 'r_latest_h': 'La più recente per ogni sistema',
 'r_all_h': 'Tutte le versioni, per sistema',
 'r_systems': {'mac': 'macOS', 'win': 'Windows', 'linux': 'Linux'},
 'r_loading': 'Caricamento delle versioni…',
 'r_error': 'Non è stato possibile leggere l’elenco delle versioni ({err}).',
 'r_github': 'Le release su GitHub',
 'r_none': 'Ancora nessuna versione pubblicata.',
 'r_notes': 'Cosa è cambiato',
 'r_checksums': 'Checksum',
 'r_updates': 'Le app installate si aggiornano da sole alla versione completa più recente; niente di quello che c’è qui va scaricato a mano, a meno che tu non voglia una versione in particolare.',
}
