# Polski. Strings of the download page, the guide and the versions page. HTML fragments and
# {placeholders} stay as they are; keys match tools/strings/en.py, which is the reference.
T = {
 'title_index': 'ygd-editor — pobieranie', 'title_guide': 'ygd-editor — przewodnik użytkownika',
 'desc': 'ygd-editor: uruchamiaj agentów programujących AI w osobnych worktree git, przeglądaj ich zmiany i publikuj je, wszystko z jednego okna. Bezpłatnie dla macOS, Windows i Linux.',
 'nav_download': 'Pobierz', 'nav_guide': 'Przewodnik', 'nav_releases': 'Wszystkie wersje', 'nav_issues': 'Zgłoś problem',
 'tagline': 'Daj każdemu zadaniu własną gałąź i własnego agenta AI — i miej wszystkie na oku.',
 'hero_p': 'ygd-editor otwiera każde zadanie w osobnym worktree git, uruchamia w nim agenta programującego (Claude Code, Codex lub Gemini CLI) i pozwala przejrzeć zmiany, zrobić commit, push i otworzyć pull request bez wychodzenia z okna. Bezpłatnie, dla macOS, Windows i Linux.',
 'dl_loading': 'Szukam najnowszej wersji…', 'dl_for': 'Pobierz dla {label}', 'dl_none': 'Nie opublikowano jeszcze żadnej wersji', 'dl_none_hint': 'Pierwsze wydanie jest w drodze.',
 'dl_error': 'Zobacz wszystkie wersje', 'dl_error_hint': 'Nie udało się odczytać najnowszej wersji ({err}). Na stronie wersji są wszystkie pliki do pobrania.',
 'dl_others': 'Inne systemy:', 'dl_checksums': 'Sumy kontrolne', 'dl_free': 'Bezpłatnie · bez konta · aktualizuje się sam',
 'kinds': {'mac-arm64': 'macOS · Apple Silicon (M1 i nowsze)', 'mac-x64': 'macOS · Intel', 'win-x64': 'Windows', 'linux-appimage': 'Linux · AppImage', 'linux-deb': 'Linux · Debian / Ubuntu'},
 'shot_console': 'Konsola: worktree po lewej, zmiany i diff w środku, sesja agenta po prawej.',
 'what_h': 'Co dostajesz',
 'what': [
   ('Jeden worktree na zadanie', 'Każda gałąź ma własny folder, więc agenci nigdy nie wchodzą sobie w drogę, a ty przełączasz się między zadaniami bez odkładania czegokolwiek na stash.'),
   ('Agenci tam, gdzie jest kod', 'Uruchom Claude Code, Codex lub Gemini CLI w worktree, patrz, jak pracuje, odpowiadaj na jego pytania i przekaż sesję do innego worktree, gdy plany się zmienią.'),
   ('Przeglądaj i publikuj na miejscu', 'Dodaj pliki do stage, przeczytaj diff, poproś agenta o wyjaśnienie lub zmianę zaznaczonego fragmentu, zrób commit, push i otwórz pull request z tego samego ekranu.'),
   ('Nie przeszkadza', 'Jedna skrzynka ze wszystkimi sesjami, które na ciebie czekają, i ze wszystkim, co aplikacja ci powiedziała, opcjonalne powiadomienia na pulpicie i licznik dzisiejszych wydatków z limitami, które sam ustawiasz.'),
   ('Spróbuj na kilka sposobów', 'Uruchom jedno zadanie z dwoma do czterech agentów lub modeli naraz, każdy we własnym worktree, porównaj, co zrobili, i zostaw najlepszy wynik.'),
   ('Cofnij turę, nie cały dzień', 'Każda tura agenta pokazuje, co zmieniła, i można ją cofnąć osobno — twoje edycje i pozostałe tury zostają.'),
 ],
 'install_h': 'Instalacja w minutę',
 'install_intro': 'Twój komputer ostrzeże cię za pierwszym razem. Tak ma być: nikt nie zapłacił Apple ani Microsoftowi za certyfikat, a ostrzeżenie dotyczy brakujących papierów, nie tego, co robi aplikacja. Oto jak je ominąć — raz, i nigdy więcej na tym komputerze.',
 'install': [
   ('macOS', ['Otwórz pobrany plik <code>.dmg</code>. Okno pokaże te kroki w twoim języku — kliknij <em>Dalej</em> — a potem przeciągnij <strong>ygd-editor</strong> do folderu Aplikacje.', 'Otwórz aplikację. macOS powie, że <em>nie mógł sprawdzić</em> aplikacji, i zaproponuje <em>Przenieś do Kosza</em> lub <em>Gotowe</em>: kliknij <strong>Gotowe</strong>.', 'Otwórz <strong>Ustawienia systemowe › Prywatność i ochrona</strong>, przewiń w dół do sekcji <em>Ochrona</em> i kliknij <strong>Otwórz mimo to</strong> obok ygd-editor. Potwierdź hasłem. To wszystko — macOS nie zapyta ponownie.', 'W macOS 14 lub starszym <strong>kliknij aplikację prawym przyciskiem › Otwórz</strong> — to samo w jednym kroku.', 'Nie wiesz, jakiego masz Maca? Menu Apple › Ten Mac: „Apple M…” to Apple Silicon, cokolwiek z „Intel” to Intel.']),
   ('Windows', ['Uruchom instalator. Gdy SmartScreen powie „System Windows ochronił ten komputer”, kliknij <strong>Więcej informacji</strong>, a potem <strong>Uruchom mimo to</strong>.', 'Wydawca to <em>ygd-editor release signing</em> — to my. Wybierz folder instalacji, jeśli chcesz, i dokończ.', 'Aplikacja pojawi się w menu Start jako ygd-editor.']),
   ('Linux', ['<strong>AppImage:</strong> nadaj mu prawa do uruchamiania (<code>chmod +x ygd-editor-*.AppImage</code>) i uruchom. Jeśli narzeka na FUSE, uruchom go z <code>--appimage-extract-and-run</code>.', '<strong>Debian / Ubuntu:</strong> <code>sudo apt install ./ygd-editor-*.deb</code>, a potem znajdź go w menu aplikacji.']),
 ],
 'cli_h': 'Bez ostrzeżenia: zainstaluj z Terminala.',
 'cli_p': 'Wklej to do Terminala (Aplikacje › Narzędzia). Pobiera najnowszą wersję dla twojego Maca, sprawdza, czy jej sumy kontrolne mają podpis projektu, czy pobrany plik się z nimi zgadza i czy aplikacja jest podpisana certyfikatem projektu, i umieszcza ją w folderze Aplikacje. Jeśli którakolwiek kontrola zawiedzie, niczego nie instaluje. macOS o nic nie pyta, bo nic nie przeszło przez przeglądarkę. Uruchom ponownie w dowolnej chwili, żeby zainstalować od nowa.',
 'cli_copy': 'Kopiuj', 'cli_copied': 'Skopiowano',
 'cli_or': 'Albo z obrazem dysku z przycisku powyżej:',
 'need_h': 'Czego potrzebujesz', 'need_p': 'Gita na komputerze i konta u co najmniej jednego dostawcy. <a href="https://github.com/openai/codex">Codex</a> i <a href="https://github.com/google-gemini/gemini-cli">Gemini CLI</a> nie są w instalatorze — dlatego jest mały —: aplikacja pobiera ten, który wybierzesz, gdy pierwszy raz o niego poprosisz (około 130–150 MB dla Codex, 20 MB dla Gemini CLI), i sprawdza go względem wersji, z którą zbudowano to wydanie, zanim go uruchomi; dla <a href="https://docs.anthropic.com/en/docs/claude-code">Claude Code</a>, którego licencja nie pozwala go dołączyć, Ustawienia › Dostawcy AI oferują jedno kliknięcie, które uruchamia za ciebie oficjalny instalator Anthropic. Połączenie z dostawcą otwiera jego stronę logowania w przeglądarce. Do pull requestów: <code>gh</code> (GitHub) lub <code>glab</code> (GitLab). Aplikacja działa na 64-bitowym Windows 10 lub 11 oraz na Linuksie x86-64 z glibc 2.34 lub nowszym (Ubuntu 22.04, Debian 12, Fedora 35 i nowsze).',
 'updates_h': 'Aktualizacje dbają o siebie same',
 'updates_p': 'Krótko po uruchomieniu, a potem co sześć godzin, dopóki jest otwarta, aplikacja sprawdza, czy jest nowa wersja, i daje znać, gdy się pojawi. Jedno kliknięcie ją pobiera, a ty decydujesz, kiedy się zainstaluje: przy ponownym uruchomieniu teraz albo przy następnym wyjściu. Aktualizacja instaluje się tylko wtedy, gdy sumy kontrolne wydania mają podpis projektu; każda inna jest odrzucana. Ustawienia › O aplikacji i aktualizacje mają przycisk „Sprawdź aktualizacje” i mogą same pobierać nowe wersje. Po aktualizacji „Co nowego” pokazuje zmiany bez wychodzenia z aplikacji.',
 'genuine_h': 'Czy pobrany plik jest autentyczny?',
 'genuine_p': 'Dwie niezależne kontrole, z których żadna nie opiera się na zaufaniu do nazwy. Nie musisz ich wykonywać; są tu dla tych, którzy chcą.',
 'genuine_sums': '<strong>Podpisane sumy kontrolne.</strong> Każda wersja od 0.17.2 ma plik <code>SHA256SUMS.txt</code> i jego podpis, <code>SHA256SUMS.txt.sig</code>, złożony kluczem projektu — tym, który stoi za jego certyfikatem, <a href="{pem}"><code>release-signing.pem</code></a>. Połóż oba obok pobranego pliku i najpierw porównaj odcisk palca certyfikatu z tym tutaj: to ten krok dowodzi całej reszty, bo kto mógłby podmienić instalator, mógłby podmienić też certyfikat obok niego. Podpis ręczy wtedy za sumy kontrolne, a sumy za każdy plik. Potrzebny jest tylko <code>openssl</code> (macOS i Linux go mają; na Windows użyj Git Bash). Powinno pojawić się <code>Verified OK</code>, a potem <code>OK</code> dla twojego pliku:',
 'genuine_prov': '<strong>Starsze wersje.</strong> Wersje od 0.6.0 do 0.17.1 mają niepodpisany <code>SHA256SUMS.txt</code> i ręczy za nie podpis kodu opisany niżej. Wersje od 0.1.0 do 0.4.0 zbudował workflow wydawniczy projektu na GitHubie i zamiast tego mają jego podpis <a href="https://www.sigstore.dev/">Sigstore</a>, <code>SHA256SUMS.txt.sigstore.json</code>. Z zainstalowanym <code>cosign</code>:',
 'genuine_sig': '<strong>Podpis kodu.</strong> Aplikacja na macOS i instalator na Windows są podpisane certyfikatem projektu (<a href="{pem}">klucz publiczny</a>). Porównuj odcisk palca, nie nazwę — każdy może nazwać certyfikat, jak chce.',
 'guide_cta_h': 'Pierwszy raz tutaj?', 'guide_cta_p': '<a href="{prefix}guide.html">Przewodnik użytkownika</a> prowadzi przez pierwsze dziesięć minut: otwarcie repozytorium, utworzenie worktree, uruchomienie agenta, przejrzenie i opublikowanie wyniku.',
 'footer_made': 'Autor: Manu Hurtado. Aplikacja jest bezpłatna; kod źródłowy jest prywatny.',
 # przewodnik
 'g_h1': 'Przewodnik użytkownika', 'g_lead': 'Wszystko, czego potrzebujesz na pierwsze popołudnie z ygd-editor, prostymi słowami. Dziesięć minut czytania, a do każdej sekcji możesz wrócić z listy.',
 'g_toc': 'Na tej stronie',
 'g_sections': [
  ('idea', 'Pomysł w jedną minutę', [
    'Git <em>worktree</em> to drugi folder tego samego repozytorium, przełączony na inną gałąź. Zamiast przełączać gałęzie w jednym folderze — i za każdym razem robić stash, przebudowywać i tracić wątek — masz jeden folder na zadanie.',
    'ygd-editor jest zbudowany wokół tego: lewy panel wyświetla listę twoich worktree, środkowy pokazuje, co się zmieniło w wybranym, a prawy uruchamia w nim agenta AI. Dwóch agentów przy dwóch zadaniach pracuje w dwóch folderach i nigdy się nie zderza. Gdy jeden czeka na odpowiedź, skrzynka w nagłówku ci o tym mówi.',
    '<img src="{img}start.png" alt="Strona startowa: ostatnie repozytoria i akcje na start" loading="lazy">',
  ]),
  ('first', 'Twoje pierwsze dziesięć minut', [
    'Po świeżej instalacji strona startowa pokazuje listę <em>Pierwsze kroki</em>: git, dostawca AI, repozytorium, pierwszy worktree i pierwsza sesja. Każdy krok ma przycisk, który go wykonuje, i sam się odhacza, gdy jest gotowy; <em>Ukryj tę listę</em> chowa ją na dobre. Poniżej te same kroki, opisane dokładniej.',
    '<ol>'
    '<li><strong>Otwórz repozytorium.</strong> Na stronie startowej wybierz <em>Otwórz repozytorium</em> i wskaż folder, w którym już jest git, albo <em>Sklonuj repozytorium</em> z adresem URL z GitHub, GitLab lub dowolnego serwera git. Ostatnie repozytoria zostają na stronie startowej.</li>'
    '<li><strong>Utwórz worktree.</strong> <em>Nowy worktree</em> (⌘N) proponuje nazwę gałęzi na podstawie zadania i folder, w którym ją umieścić; oba możesz zmienić na dowolną konwencję, której używasz. Git nie pozwala na spacje w nazwie gałęzi, więc zamieniają się w myślniki, a okno pokazuje wynik, zanim cokolwiek utworzy. Gdzie worktree trafiają na dysku i opcjonalny sugerowany prefiks ustawisz w Ustawienia › Git.</li>'
    '<li><strong>Uruchom sesję.</strong> <em>+ Sesja</em> w prawym panelu wybiera agenta i model; domyślny agent to Ustawienia › Domyślny agent. Wpisz, czego chcesz, w kompozytorze. <code>@</code> dołącza pliki lub kontekst, na przykład bieżący diff, <code>/</code> uruchamia polecenia agenta, <code>#</code> jego skille. ⌘↵ wysyła.</li>'
    '<li><strong>Pozwól mu pracować — albo go zatrzymaj.</strong> Transkrypcja pokazuje każde narzędzie, którego agent używa. Gdy potrzebuje zgody na coś, czego wcześniej nie zatwierdzono, sesja przechodzi w stan <em>Czeka na odpowiedź</em>, skrzynka w nagłówku ją zlicza, a ty zezwalasz lub odmawiasz — „Zawsze zezwalaj” zapamiętuje twój wybór dla tego worktree. <em>Zatrzymaj</em> przerywa; wiadomości wpisane w trakcie pracy trafiają do kolejki.</li>'
    '<li><strong>Przejrzyj zmiany.</strong> Zakładka Zmiany wyświetla każdy zmieniony plik razem z tym, kto go zmienił. Kliknij plik, aby zobaczyć diff; zaznacz linie i wybierz <em>Wyjaśnij</em> lub <em>Poproś o zmianę</em>, aby odesłać je do agenta. Ostrzeżenie oznacza pliki, których dotyka też inny worktree tego samego repozytorium.</li>'
    '<li><strong>Commit, push, otwórz PR.</strong> Zaznacz pliki do dodania do stage, napisz wiadomość albo <em>Napisz z AI</em>, <em>Commit</em>. <em>Push</em> ustawia upstream; <em>Otwórz pull request</em> wypełnia tytuł, opis (napisany na podstawie diffu, jeśli chcesz), flagę draft, recenzentów i etykiety, po czym przekazuje sprawę do <code>gh</code> lub <code>glab</code>. Karta worktree pokazuje wtedy PR i jego checki.</li>'
    '</ol>',
    '<img src="{img}console.png" alt="Konsola z otwartym diffem i działającą sesją Claude Code" loading="lazy">',
  ]),
  ('daily', 'Na co dzień', [
    '<p><strong>Główny worktree</strong> — folder, z którego otworzono repozytorium — jest na liście razem z pozostałymi i to od niego odgałęziają się nowe worktree. Wybierz go i kliknij nazwę jego gałęzi w nagłówku: rozwinie się pole wyszukiwania ze wszystkimi gałęziami — twoimi albo takimi, które istnieją tylko na zdalnym repozytorium i które pobierze jako nową gałąź śledzącą. Pisz, aby zawęzić listę, strzałki i Enter, aby się przełączyć. Gałąź, którą ma już inny worktree, jest na liście, ale wyszarzona, bo git pozwala na jedną gałąź w jednym worktree naraz.</p>'
    '<p><strong>Aktualizuj z bazy</strong> na worktree robi fetch i rebase na gałęzi bazowej; konflikty zatrzymują proces z listą plików, rozwiązujesz je, dodajesz do stage i <em>Kontynuuj</em>. <strong>Fetch</strong> odświeża liczniki przed/za. Zakładka Terminal to prawdziwa powłoka w folderze worktree; Aktywność to oś czasu tego, co się tam działo — commity, pushe, sesje — i przetrwa restarty.</p>'
    '<p><strong>Przekazywanie.</strong> Sesję można przenieść do innego worktree z jej menu, razem z transkrypcją, gdy zorientujesz się, że praca należy do innej gałęzi.</p>'
    '<p><strong>Usunięcie worktree</strong> kończy jego sesje, archiwizuje ich logi i zapomina jego reguły uprawnień; gałąź zostaje, chyba że ją usuniesz. Ustawienia › Git mogą same usunąć worktree, gdy jego PR zostanie scalony.</p>'
    '<p><strong>Wiele repozytoriów.</strong> Otwórz, ile chcesz; nagłówek przełącza między nimi, a skrzynka zlicza oczekujące sesje ze wszystkich.</p>',
  ]),
  ('git', 'Git bez terminala', [
   '<strong>Pull i Aktualizuj z bazy to dwie różne rzeczy.</strong> <em>Pull</em> pobiera to, co wypchnięto na twoją własną gałąź — na przykład commit kolegi — żeby twój następny push przeszedł; gdy obie strony mają nowe commity, robi rebase albo merge zgodnie z Ustawienia › Git albo pyta. <em>Aktualizuj z bazy</em>, w menu <code>···</code>, to drugie zadanie: nadrabianie zaległości względem gałęzi bazowej.',
   '<strong>Konflikty.</strong> Gdy rebase, merge, revert albo cherry-pick zatrzyma się na konfliktach, otwórz plik i rozwiąż go blok po bloku: zachowaj jedną stronę, drugą albo <em>Zachowaj oba</em> — albo weź cały plik, albo <em>Poproś agenta</em>. Obie strony są nazwane według tego, co się dzieje, więc nie trzeba zgadywać, która jest „nasza”. <em>Oznacz jako rozwiązane</em>, a potem <em>Kontynuuj</em> na pasku.',
   '<strong>Amend.</strong> Pole commita ma przełącznik <em>Popraw (amend)</em>. Commit, którego nie wypchnięto, jest po prostu przepisywany. Wypchniętego nigdy nie wypycha się na siłę: aplikacja umieszcza go na nowej gałęzi, wypycha ją, otwiera nowy pull request i zamyka stary z linkiem do nowego.',
   '<strong>Historia.</strong> Kliknij prawym przyciskiem commit w Aktywności, aby <em>Kopiuj SHA</em>, <em>Pokaż zmiany</em>, <em>Cofnij (revert)</em> albo zrobić <em>Cherry-pick do…</em> innego worktree.',
   '<strong>Pull requesty.</strong> Karta PR wymienia każdy check, werdykt każdego recenzenta i komentarze z recenzji z plikiem i wierszem. <em>Uwzględnij recenzję</em> przekazuje otwarte komentarze agentowi; <em>Scal</em> proponuje metody, na które pozwala repozytorium, i mówi, dlaczego jeszcze się nie da. Gdy praca jest już w środku, <em>Posprzątaj scalone worktree…</em> usuwa za jednym razem wszystkie skończone worktree i wymienia te, które zostawia.',
   '<strong>Forki.</strong> W forku <code>origin</code> to twoja kopia, a <code>upstream</code> — projekt. Aplikacja czyta gałąź bazową z <code>upstream</code>, gdy tylko istnieje, więc nowy worktree startuje od <code>upstream/main</code>, a nie od nieaktualnej kopii w twoim forku, podczas gdy push i pull requesty nadal idą do twojego forka; <em>Fetch</em> pobiera z obu. Ustawienia › Git › <em>Zdalne repozytorium bazy</em> wskazuje inne, a okno zdalnych repozytoriów oznacza je jako <em>base</em>.',
   '<strong>Repozytoria bare.</strong> Repozytorium otwiera się w całości z każdego swojego folderu: głównego, połączonego worktree, repozytorium bare <code>api.git</code> z worktree obok albo układu <code>proj/.bare</code>. Wszystkie worktree są na liście. Repozytorium bare nie ma głównego worktree, więc każdy worktree można usunąć, nowe trafiają obok folderu bare (<code>api--fix</code>), a <em>Ustaw jako bieżący</em> i zmiana gałęzi głównego worktree nie są dostępne.',
  ]),
  ('review', 'Przegląd tego, co zrobił agent', [
   '<strong>Tura po turze.</strong> Każda tura, która zmienia pliki, kończy się linijką pod nią w transkrypcji — <em>Zmieniono 5 plików · +120 −8</em>. Kliknij ją, a zakładka Zmiany pokaże tylko to, co zrobiła ta tura. <em>Cofnij tę turę…</em> najpierw wymienia, co stanie się z każdym plikiem, a potem wycofuje zmiany tury: plik, którego nikt potem nie ruszał, wraca do poprzedniego stanu, plik edytowany przez ciebie lub późniejszą turę zachowuje te edycje, a tam, gdzie obie strony zmieniły te same wiersze, zostają znaczniki konfliktu do rozwiązania. Cofnięcie jest osobną turą, więc je też można cofnąć.',
   '<strong>Blok po bloku.</strong> Każdy blok diffu ma <em>Do stage</em> i <em>Odrzuć</em> (<em>Ze stage</em>, gdy już jest w stage); zaznacz kilka wierszy, aby dodać do stage albo odrzucić tylko je. Plik częściowo w stage ma przełącznik <em>W stage / Poza stage</em> nad diffem.',
   '<strong>Odszukanie starej rozmowy.</strong> <em>Szukaj w sesjach</em>, na górze panelu sesji, przeszukuje to, co powiedziano w tym worktree, w repozytorium albo w obszarze roboczym — a jeśli zaznaczysz <em>zarchiwizowane</em>, także w worktree, które już usunięto. Wynik otwiera sesję na tej wiadomości. Kliknij sesję prawym przyciskiem, aby <em>Eksportuj transkrypcję…</em>: plik Markdown z promptami, odpowiedziami i wywołaniami narzędzi. Nic nie jest ukrywane, więc przeczytaj go, zanim go udostępnisz.',
   '<strong>Czytanie dużej zmiany.</strong> Lista Zmian grupuje pliki według folderów — przycisk folderu obok filtra przełącza na płaską listę — a filtr zostawia ścieżki zawierające wszystkie wpisane słowa. Zaznacz <em>Przejrzany</em> (V) przy każdym przeczytanym pliku: znacznik znika sam, gdy agent znowu zmieni ten plik, a <em>Następny nieprzejrzany</em> (⇧N) przenosi do kolejnego. W diffie N i P skaczą od bloku do bloku, a W zawija długie wiersze. Zmienione słowa są podświetlone wewnątrz wiersza, kod jest kolorowany według języka, widok obok siebie przechodzi w jednolity, gdy panel jest wąski, obrazy widać przed i po, a plik Markdown można pokazać jako <em>Wyrenderowany</em>.',
   '<strong>Odrzucone przez pomyłkę?</strong> <em>Odrzuć</em>, <em>Odrzuć wszystkie zmiany</em>, odrzucenie bloku lub kilku wierszy oraz wymuszone usunięcie worktree zachowują to, co wyrzucają. <em>Cofnij</em> w komunikacie przywraca zmiany; później <em>Schowki › Ostatnio odrzucone</em> mają <em>Przywróć</em>, a <em>Zapisz jako schowek</em> zamienia wpis w zwykły schowek — to droga powrotu do zmian z usuniętego worktree. <em>Schowaj wszystkie zmiany</em> też oferuje Cofnij.',
   '<strong>Duże repozytoria.</strong> Przy ponad 2000 nieśledzonych plików lista pokazuje pierwsze 2000 i po jednym wierszu na folder z liczbą pozostałych; <em>Wszystko do stage</em>, <em>Commit</em> i <code>.gitignore</code> nadal obejmują każdy z nich. Nieśledzone pliki powyżej 10 MB są pomijane w punktach kontrolnych tur, a stopka tury mówi, ile ich było. Jeśli odczyt worktree trwa dłużej niż 5 sekund, tura nie dostaje punktu kontrolnego, a jej stopka mówi, że nie da się jej otworzyć ani cofnąć. Zmiany w <code>node_modules</code>, <code>dist</code>, <code>.next</code> i <code>target</code> nie odświeżają już listy, a edycje zrobione poza aplikacją pojawiają się nawet podczas długiego pusha czy fetcha.',
  ]),
  ('sessions', 'Agenci przy pracy', [
   '<strong>Czytanie transkrypcji.</strong> Odpowiedzi są pokazywane jako sformatowany tekst, a każdy blok kodu ma przycisk <em>Kopiuj</em>. Trzy lub więcej wywołań narzędzi z rzędu zwija się w jeden wiersz, który rozwija się, by je pokazać. Ścieżka do pliku z worktree jest linkiem: zmieniony plik otwiera swój diff, każdy inny otwiera się w twoim edytorze. Przewiń w górę, by czytać, a transkrypcja przestanie podążać za nowymi wiadomościami; <em>Przejdź do najnowszych</em> wraca na dół. Jeśli sesję zatrzymano, gdy prosiła o pozwolenie, transkrypcja o tym mówi.',
   '<strong>Długie sesje.</strong> Sesja otwiera się na najnowszych wiadomościach, a <em>Pokaż wcześniejsze wiadomości</em> wczytuje resztę, kiedy jej potrzebujesz. Żeby historia nie rosła bez końca, Ustawienia › Domyślny agent mają <em>Przechowuj sesje przez</em> (dni) i <em>Limit miejsca na sesje</em> (MB): przy starcie aplikacja usuwa to, co starsze albo ponad limit. Obie opcje są wyłączone, dopóki ich nie ustawisz.',
   '<strong>Zatrzymanie naprawdę zatrzymuje.</strong> <em>Zatrzymaj</em>, usunięcie worktree i wyjście z aplikacji kończą też to, co agent uruchomił — na przykład serwer deweloperski. Zmiana modelu tego nie robi, limit bezczynności też nie: Ustawienia › Domyślny agent › <em>Kończ bezczynnych agentów po</em> (30 minut, jeśli tego nie zmienisz; puste pole oznacza nigdy) kończy agenta, który był bezczynny tak długo, żeby zwolnić pamięć, a twój następny prompt podejmuje rozmowę na nowo. Jeśli aplikacja padła, gdy agenci jeszcze działali, przy następnym uruchomieniu proponuje <em>Zatrzymaj</em> albo <em>Zostaw uruchomione</em>.',
   '<strong>Środowisko twojej powłoki.</strong> Agenci dostają to, co eksportuje twój <code>.zshrc</code> lub <code>.bashrc</code> — proxy, klucze API, <code>AWS_PROFILE</code> — tak jakby zostali uruchomieni z terminala, nawet gdy samą aplikację otwarto z Docka czy z menu. Ustawienia › Edytor i terminal › <em>Używaj środowiska mojej powłoki</em> to wyłącza i pokazuje nazwy przenoszonych zmiennych, nigdy ich wartości. Windows tego nie potrzebuje: tam aplikacje już dostają twoje zmienne.',
  ]),
  ('setup', 'Worktree gotowe do uruchomienia', [
   'Nowy worktree nie ma żadnego z twoich ignorowanych plików — ani <code>.env</code>, ani <code>node_modules</code>. <strong>Ustawienia › Przygotowanie worktree</strong> załatwia to raz: pliki do skopiowania z głównego worktree (na przykład <code>.env*</code>), polecenia do uruchomienia w terminalu nowego worktree (<code>pnpm install</code>) i port bazowy, dzięki któremu każdy worktree dostaje własny port w <code>YGD_PORT</code>, a dwa serwery deweloperskie przestają walczyć o ten sam. Terminal worktree i jego agenci dostają też <code>YGD_WORKTREE</code> i <code>YGD_BRANCH</code>. Okno Nowy worktree pokazuje, co zrobi przygotowanie; <em>Uruchom przygotowanie ponownie</em> jest w menu <code>···</code>.',
   'Repozytorium może mieć ten sam przepis w <code>.ygd/worktree.json</code>. Jego polecenia pochodzą od autora gałęzi, więc aplikacja je pokazuje i pyta przed pierwszym uruchomieniem — i ponownie przy każdej zmianie pliku.',
  ]),
  ('terminals', 'Terminale', [
   '<strong>Kilka terminali.</strong> <code>+</code> w zakładce Terminal otwiera kolejną powłokę obok tej worktree; kliknij dwukrotnie kartę, aby zmienić jej nazwę. <em>Uruchom ▾</em> na pasku narzędzi startuje zapisane polecenia — <code>dev: pnpm dev</code> — każde we własnym terminalu nazwanym tak jak ono, z <em>Uruchom ponownie</em> i <em>Zatrzymaj</em>. <code>@terminal:dev</code> w prompcie dołącza to, co wypisał ten terminal.',
   '<strong>Działają dalej.</strong> Terminal zachowuje swój program i historię, gdy otwarte są Ustawienia, strona startowa albo widok porównania, więc <code>vim</code>, <code>htop</code> czy serwer deweloperski są dokładnie takie, jak je zostawiłeś. ⌘F (Ctrl+Shift+F w Windows i Linux) albo lupa na końcu kart przeszukuje historię. ⌘-klik (Ctrl+klik) otwiera link w przeglądarce. ⌘⇧] i ⌘⇧[ (Ctrl+PageDown i Ctrl+PageUp) przechodzą do następnego i poprzedniego terminala. Zamknięcie terminala, w którym coś jeszcze działa, wymaga potwierdzenia, a pytanie podaje nazwę programu.',
  ]),
  ('tryn', 'Spróbuj na kilka sposobów', [
   'Nie wiesz, który agent albo model najlepiej wykona zadanie? Zaznacz <em>Spróbuj na N sposobów</em> w oknie Nowy worktree i wybierz od dwóch do czterech prób — Claude Code, Codex i Gemini CLI albo ten sam model trzy razy. Każda dostaje własny worktree z tej samej bazy (<code>login-a</code>, <code>login-b</code>…), przygotowanie uruchamia się w każdym, a ten sam pierwszy prompt trafia do wszystkich. Każda próba liczy się do budżetu i okno to mówi.',
   'Próby stoją razem na pasku bocznym. Kliknij ich pozycję, aby porównać je obok siebie: stan, zmienione pliki i wiersze, koszt, tury i czas, szybki diff oraz twoje polecenie sprawdzające — na przykład <code>pnpm test</code> z Ustawienia › Przygotowanie worktree — uruchamiane w każdej na żądanie. <em>Zostaw ten</em> usuwa pozostałe po ich wymienieniu, może nadać zwycięzcy nazwę gałęzi bez sufiksu i może od razu przejść do Ustaw jako bieżący albo do pull requesta.',
  ]),
  ('workspaces', 'Praca z kilkoma repozytoriami: przestrzenie robocze', [
    '<em>Przestrzeń robocza</em> to nazwany zestaw folderów, które aplikacja trzyma otwarte razem. Gateway, konsola webowa i folder z notatkami to często jeden kawałek pracy, a pytanie o jeden z nich zwykle znajduje odpowiedź w innym — przestrzeń robocza to sposób, by powiedzieć aplikacji, że należą do siebie.',
    '<img src="{img}workspace.png" alt="Przestrzeń robocza z dwoma repozytoriami: pasek boczny grupuje worktree według repozytorium" loading="lazy">',
    '<strong>Tworzenie.</strong> Otwórz drugie repozytorium, gdy jedno jest już otwarte, a aplikacja zapyta, gdzie je umieścić: dodać do tego, nad czym pracujesz, utworzyć nową przestrzeń roboczą z obydwoma albo otworzyć osobno. Escape oznacza „osobno”. Możesz też utworzyć przestrzeń ze strony startowej przez <em>Nowa przestrzeń robocza</em>, a foldery dodawać i usuwać później przyciskiem Przestrzenie robocze w nagłówku. Usunięcie folderu z przestrzeni roboczej nigdy niczego nie kasuje — zmienia się tylko zestaw.',
    '<strong>Z VS Code.</strong> Jeśli twój zespół ma już plik <code>.code-workspace</code>, <em>Otwórz plik przestrzeni roboczej…</em> go wczyta: te same foldery, w tej samej kolejności, nazwane tak, jak nazywa je VS Code. Komentarze i końcowe przecinki w pliku nie przeszkadzają. Foldery, które nie są repozytoriami git, zostają — po prostu nie mają worktree — a o folderze, który zniknął, aplikacja informuje, zamiast po cichu go pominąć. <em>Zapisz do pliku</em> zapisuje go z powrotem, nie ruszając części, których aplikacja nie używa, więc ten sam plik dalej działa w obu narzędziach.',
    '<strong>Co pokazuje pasek boczny.</strong> Worktree pogrupowane według repozytorium, każda grupa zwijana, a filtr dopasowuje nazwę gałęzi lub repozytorium, więc znajdziesz gałąź bez pamiętania, gdzie mieszka. Zwinięta grupa nadal pokazuje, co w niej działa, i nadal mówi, gdy jakaś sesja czeka. Przy jednym repozytorium grup nie ma wcale.',
    '<strong>Co widzą agenci.</strong> Sesja nadal działa <em>w</em> swoim worktree — tam należą git i każda ścieżka względna — ale może też czytać pozostałe foldery przestrzeni roboczej, więc na „gdzie trafia to wywołanie?” da się odpowiedzieć z obu stron. Sesja, która tylko czyta, nadal może tylko czytać, wszędzie. Nad grupami jest też wiersz <em>W całej przestrzeni roboczej</em>, dla sesji, które nie należą do żadnego worktree: im zadawaj pytania obejmujące cały stack. Nie mają gałęzi, zmian ani terminala, bo to należy do worktree.',
    '<strong>Ustawienia.</strong> Teraz trzy poziomy: Globalne, przestrzeń robocza, potem pojedyncze repozytorium. Domyślny agent, preset uprawnień i gałąź bazowa są zwykle cechą całego stacku, a nie każdego repozytorium z osobna, więc ustaw je raz w przestrzeni roboczej; repozytorium, które potrzebuje czegoś innego, nadal może je nadpisać. Selektor zakresu w Ustawieniach wybiera poziom, a sekcja, która nie nadpisuje, mówi, skąd biorą się jej wartości.',
    'Aplikacja pamięta każdą przestrzeń roboczą osobno: wróć do jednego z nich i wylądujesz w repozytorium, worktree i układzie paneli, które były otwarte przy wyjściu.',
  ]),
  ('current', 'Testowanie worktree w domyślnym', [
    'Miejscem do wypróbowania zmiany jest folder samego repozytorium — <em>domyślny worktree</em> — bo tam są już <code>node_modules</code>, <code>.env</code>, pamięć podręczna budowania i działający serwer deweloperski. Praca odbywa się w pozostałych worktree. <strong>Ustaw jako bieżący</strong> wnosi jeden z nich do domyślnego worktree: jego commity, to, czego jeszcze nie zacommitował, i jego nowe pliki, na gałęzi domyślnego worktree. Od tej chwili nagłówek na każdym ekranie mówi, co uruchamia domyślny worktree — <code>DOMYŚLNY · feat-a + feat-b · 1 edycja</code> — a pasek boczny oznacza worktree <em>domyślny</em> i <em>bieżące</em>.',
    '<img src="{img}current.png" alt="Pasek w nagłówku, rozwinięty: skąd przyszedł domyślny worktree, dwa bieżące worktree i co można zrobić dalej" loading="lazy">',
    '<strong>Zamień</strong> wstawia na jego miejsce inny worktree. <strong>Dodaj</strong> nakłada kolejny, żeby wypróbować dwie zmiany razem; gdzie oba dotykają tych samych linii, wczytywanie zatrzymuje się na konflikcie w domyślnym worktree, a dla każdego pliku zostawiasz stronę domyślną, bierzesz przychodzącą albo edytujesz go i oznaczasz jako rozwiązany — potem <em>Kontynuuj</em> albo <em>Przerwij</em>, by wrócić do tego, co działało wcześniej.',
    '<strong>Poprawki zrobione podczas testów wracają do domu.</strong> Jeśli ty — albo agent w domyślnym worktree — poprawisz coś podczas próby, <em>Odeślij edycje</em> zwraca to do worktree, do którego należy, jako niezacommitowane zmiany do przejrzenia i zacommitowania tam; <em>Cofnij</em> odwraca to aż do następnego kroku. O plik należący do kilku bieżących worktree albo do żadnego aplikacja pyta, zamiast zgadywać. Zamień, Dodaj, Odśwież i Zakończ najpierw odsyłają edycje, więc nic zrobionego w domyślnym worktree nie przepada. <em>Odeślij edycje</em>, <em>Zakończ</em> i <em>Cofnij tę turę</em> zapisują pliki tak, jak zrobiłby to checkout — razem z Git LFS, git-crypt i windowsowymi końcami wierszy; jeśli brakuje filtra, którego repozytorium potrzebuje (na przykład nie zainstalowano <code>git-lfs</code>), zatrzymują się z komunikatem gita, zamiast zostawiać pliki-wskaźniki.',
    '<strong>Zakończ</strong> oddaje domyślny worktree dokładnie w takim stanie, w jakim był: jego gałąź i jego własne zmiany, dodane do indeksu i nie. Każdy krok najpierw otwiera krótki podgląd: co wchodzi, co czeka z boku, które pliki weszłyby w konflikt i co blokuje go teraz, razem z wyjściem. Znajdziesz je w menu <code>···</code> worktree, pod prawym przyciskiem w pasku bocznym, w pasku nagłówka i pod ⌘⇧D / ⌘⇧E.',
    'Ustawienia › Git mogą same odświeżać bieżący worktree, gdy jego agent dalej pracuje, i uruchamiać polecenie po każdym wczytaniu — na przykład <code>pnpm install</code>, gdy zmienił się <code>pnpm-lock.yaml</code> — w terminalu domyślnego worktree, gdzie je widzisz. Twój <code>git stash</code> nigdy nie jest ruszany. Wymaga git 2.40 lub nowszego.',
  ]),
  ('find', 'Szybkie poruszanie się i ile to kosztowało', [
   '<strong>⌘K</strong> otwiera paletę poleceń: każdą akcję aplikacji — ze skrótem albo z powodem, dla którego teraz nie da się jej wykonać — a także worktree z całego obszaru roboczego, sesje, strony Ustawień i ostatnie repozytoria. Zacznij od <code>&gt;</code> dla akcji, <code>@</code> dla worktree, <code>#</code> dla sesji; strzałki i Enter robią resztę.',
   '<strong>Ile to kosztowało.</strong> Ustawienia › Budżet mają <em>Raport użycia</em>: słupek na każdy dzień podzielony według agenta i to, ile wydało każde repozytorium i każda gałąź, z ostatnich 7, 30 lub 90 dni albo z wybranych dat, z <em>Eksportuj CSV</em>. Liczby są te same co w budżecie, więc zawsze zgadzają się z miernikiem wydatków.',
  ]),
  ('providers', 'Agenci i dostawcy', [
    '<p>ygd-editor sam nie rozmawia z żadną usługą AI. Uruchamia narzędzia wiersza poleceń, które już masz — <a href="https://docs.anthropic.com/en/docs/claude-code">Claude Code</a>, <a href="https://github.com/openai/codex">Codex</a>, <a href="https://github.com/google-gemini/gemini-cli">Gemini CLI</a> — z twoimi własnymi kontami, więc zużycie, rozliczenia i warunki dotyczące danych są dokładnie te, które obowiązują cię u tych dostawców.</p>'
    '<p>Ustawienia › Dostawcy AI łączą każdego dostawcę z twoim własnym kontem: <em>Połącz</em> otwiera stronę logowania dostawcy w przeglądarce, a karta pokazuje potem konto, plan oraz <em>Zmień konto</em> / <em>Odłącz</em> / <em>Testuj połączenie</em>. Codex i Gemini CLI aplikacja pobiera, gdy wybierzesz je po raz pierwszy — karta podaje wersję i rozmiar, pokazuje postęp, a <em>Usuń pobrane</em> znów je usuwa; jeśli masz zainstalowaną własną kopię, aplikacja używa właśnie jej. Licencja Claude Code nie pozwala go dołączyć, więc jego karta oferuje <em>Zainstaluj Claude Code</em>, co uruchamia oficjalny instalator Anthropic w terminalu na karcie, do twojego folderu domowego, bez hasła administratora. Domyślny agent i model oraz preset uprawnień mogą się różnić dla każdego repozytorium.</p>',
    '<p>Karta mówi też, gdy zainstalowane CLI jest nowsze lub starsze niż wersje, z którymi sprawdzono to wydanie. Sesje działają normalnie; ta uwaga tłumaczy, skąd mógłby się wziąć niepełny raport. Gdy Codex traci połączenie i próbuje ponownie, transkrypcja pokazuje krótką notkę <em>Ponowne łączenie…</em> zamiast błędu.</p>',
  ]),
  ('permissions', 'Uprawnienia', [
    '<p>Agenci pytają, zanim zrobią coś, czego wcześniej nie zatwierdzono. Ustawienia › Uprawnienia mają trzy presety — <em>ścisły</em> (tylko odczyt), <em>zrównoważony</em> (odczyt i edycja plików, pytanie o wszystko inne) i <em>yolo</em> (dodatkowo uruchamianie poleceń, dostęp do sieci i push) — plus osobne przełączniki dla odczytu, edycji, uruchamiania poleceń, dostępu do sieci, pusha i usuwania. Niezależnie od presetu agent nigdy nie usuwa bez pytania, chyba że to włączysz.</p>'
    '<p>Gdy przychodzi prośba, <em>Zatwierdź</em> i <em>Odmów</em> odpowiadają jednorazowo; <em>Zawsze zezwalaj</em> zapamiętuje to narzędzie dla tego worktree, a reguła znika razem z worktree.</p>',
    '<p>Gdy agent prosi o kilka rzeczy naraz, prośby ustawiają się w kolejce na karcie sesji i w skrzynce — <em>1 z 3</em> — i odpowiadasz na nie po kolei. Ustawienia › Uprawnienia › <em>Dozwolone reguły</em> wymieniają każde „Zawsze zezwalaj” według worktree, z datą dodania; <em>Cofnij</em> działa od razu, także w trwającej sesji. <em>Odmawiaj automatycznie po</em> (minuty, domyślnie wyłączone) odrzuca prośbę, na którą nikt nie odpowiedział, i mówi agentowi dlaczego. Codex i Gemini CLI nie umieją pytać, więc ich pasek agenta pokazuje tryb piaskownicy, jaki dają im twoje przełączniki; kliknięcie w niego otwiera Ustawienia › Uprawnienia.</p>',
  ]),
  ('notifications', 'Powiadomienia, skrzynka i budżet', [
    '<p>Ustawienia › Powiadomienia decydują, kiedy aplikacja da ci znać: gdy sesja czeka, gdy jakaś się skończy i gdy zmieni się pull request — checki zakończone, zatwierdzony, poproszono o zmiany, scalony. Pull requesty wszystkich worktree są śledzone w tle, więc dowiadujesz się o nich w ciągu mniej więcej pięciu minut, nawet gdy nie patrzysz na dany worktree; scalenie wykryte w ten sposób zostawia propozycję usunięcia worktree, dopóki nie odpowiesz. Powiadomienia pokazują się tylko wtedy, gdy okno nie jest na pierwszym planie, kliknięcie w jedno z nich przenosi do sesji, a plakietka w Docku lub na pasku zadań może zliczać oczekujące sesje.</p>',
    '<p>Skrzynka w nagłówku ma dwie karty. <em>Czeka na odpowiedź</em> to sesje, które na ciebie czekają. <em>Aktywność</em> to wszystko, co aplikacja ci powiedziała — zakończone tury, zmiany w pull requestach, błędy z pełnym wyjściem gita, komunikaty, które mogły ci umknąć — a kliknięcie wiersza przenosi do jego sesji lub worktree. Nieprzeczytane wiersze są zliczane, <em>Oznacz wszystko jako przeczytane</em> je czyści, a 200 najnowszych zostaje po ponownym uruchomieniu.</p>',
    '<p>Pasek budżetu na dole lewego panelu to dzisiejsze wydatki we wszystkich sesjach. Gdy agent podaje własny koszt, to jest ta kwota; w przeciwnym razie jego tokeny są wyceniane według ceny katalogowej modelu, a stawki z Ustawienia › Budżet służą tylko modelom, które jej nie mają. Okienko zużycia i podpowiedź przy koszcie sesji mówią, który to przypadek. Ustawienia › Budżet ustawiają też limit dzienny i limit na sesję oraz próg ostrzeżenia; przy włączonym <em>Wstrzymuj sesje przy limicie</em> osiągnięcie limitu dziennego zatrzymuje także trwające tury, a komunikat mówi, ile ich było.</p>',
  ]),
  ('settings', 'Ustawienia', [
    '<p>Ustawienia (⌘,) są pogrupowane tematycznie. Wygląd ustawia motyw, kolor akcentu, gęstość i czcionki; Język przełącza interfejs między angielskim, hiszpańskim, włoskim, polskim, francuskim, niemieckim i tureckim. Kilka sekcji ma plakietkę <em>na repo</em>: z repozytorium wybranym u góry możesz je nadpisać tylko dla tego repozytorium. Daty, godziny, liczby i koszty są zapisywane według wybranego języka, nie według systemu.</p>'
    '<p>Wszystko zapisuje się automatycznie do <code>settings.json</code> w folderze aplikacji w twoim katalogu domowym; <em>Otwórz settings.json</em> edytuje surowy plik z walidacją, a nagłówek pokazuje, kiedy został ostatnio zapisany. Plik wskazuje swój <a href="https://mhguitarte.github.io/ygd-editor/settings.schema.json">schemat</a>, więc edytor taki jak VS Code podpowiada i sprawdza go, gdy edytujesz go ręcznie. Każdy zapis zachowuje poprzedni plik jako <code>settings.json.bak</code>; jeśli plik się uszkodzi, aplikacja działa na tej kopii i o tym mówi. Starsza wersja aplikacji nigdy nie nadpisuje pliku zapisanego przez nowszą: działa na ustawieniach domyślnych i odmawia zapisu ustawień, dopóki znowu nie zaktualizujesz. Obszary robocze, skrzynka i listy sesji są przechowywane tak samo.</p>',
    '<p><em>Szukaj w ustawieniach</em>, na górze, znajduje każdy wiersz po nazwie lub po tym, co robi: wpisz „limit budżetu”, a otworzy się Budżet z kursorem w Limicie dziennym; ⌘K też znajduje ustawienia. Zmieniony wiersz ma kropkę i własne <em>Przywróć</em>. Pola liczbowe odrzucają wartość, której aplikacja nie mogłaby użyć, mówią dlaczego i zostawiają zapisaną.</p>',
    '<img src="{img}settings.png" alt="Ustawienia › Wygląd" loading="lazy">',
  ]),
  ('layout', 'Małe okna i klawiatura', [
   '<strong>Małe okna.</strong> Okno można zmniejszyć do 900 × 680, więc aplikacja mieści się obok edytora na 13- lub 14-calowym laptopie. Poniżej około 1180 pikseli szerokości panel sesji zwija się do wąskiego paska, a poniżej około 1000 — także lista worktree. Kliknij pasek, by otworzyć jego panel nad środkiem; Escape albo kliknięcie obok chowa go z powrotem. Zapisany układ pozostaje nietknięty: poszerz okno, a panele wrócą na swoje miejsca.',
   '<strong>Z klawiatury.</strong> Każda lista — worktree, sesje, karty terminala, sekcje Ustawień, ostatnie repozytoria — to jeden przystanek klawisza Tab. ↑ i ↓ (← i → na kartach terminala), Home i End poruszają się po niej, Enter lub Spacja wybierają wiersz, klawisz menu lub Shift+F10 otwiera jego menu, a F2 zmienia nazwę karty terminala.',
   '<strong>Pytania zadaje sama aplikacja.</strong> Wszystko, co wymaga zgody — odrzucenie zmian, usunięcie schowka, scalenie pull requesta — pyta w oknie samej aplikacji, w twoim języku, z nazwą akcji na przycisku; Escape oznacza nie. Klonowanie, Przekaż sesję i zdalne repozytoria pytają, zanim wyrzucą to, co w nich wpisano.',
  ]),
  ('updates', 'Aktualizacje', [
    '<p>Krótko po uruchomieniu, a potem co sześć godzin, dopóki jest otwarta, aplikacja sprawdza wydania na tej stronie i daje znać, gdy jest nowa wersja. Jedno kliknięcie ją pobiera; przy włączonym Ustawienia › O aplikacji i aktualizacje › <em>Pobieraj aktualizacje automatycznie</em> pobiera się, gdy tylko zostanie znaleziona. Nic się nie instaluje, dopóki nie wybierzesz: <em>Uruchom ponownie i zaktualizuj</em> teraz, <em>Uruchom ponownie później</em> — wtedy instaluje się przy wyjściu — albo <em>Odrzuć</em>.</p>',
    '<p>Aktualizacja instaluje się tylko wtedy, gdy wymieniają ją podpisane sumy kontrolne wydania, sprawdzone względem certyfikatu wbudowanego w aplikację. Jeśli nie, aplikacja mówi, że aktualizacja nie jest podpisana przez projekt, i niczego nie instaluje. Ustawienia › O aplikacji i aktualizacje mają też <em>Proponuj aktualizacje</em>, które wyłącza sprawdzanie, i <em>Sprawdź aktualizacje</em> z godziną ostatniego sprawdzenia.</p>',
    '<p>Pierwsze uruchomienie po aktualizacji mówi, jaką masz wersję, a jego <em>Co nowego</em> otwiera informacje o wydaniu w samej aplikacji. Otwierają je też Ustawienia › O aplikacji i aktualizacje oraz paleta poleceń.</p>',
  ]),
  ('shortcuts', 'Skróty klawiszowe', [
    '<table><tr><td>⌘O</td><td>Otwórz repozytorium</td></tr><tr><td>⇧⌘C</td><td>Sklonuj repozytorium</td></tr><tr><td>⌘N</td><td>Nowy worktree</td></tr><tr><td>⌘K</td><td>Paleta poleceń</td></tr><tr><td>⌘,</td><td>Ustawienia</td></tr><tr><td>⌘↵</td><td>Wyślij wiadomość</td></tr><tr><td>⌘F</td><td>Szukaj w terminalu</td></tr><tr><td>⌘⇧] ⌘⇧[</td><td>Następny / poprzedni terminal</td></tr><tr><td>⇧N</td><td>Następny nieprzejrzany plik</td></tr></table>'
    '<p>W Windows i Linux czytaj ⌘ jako Ctrl — z wyjątkiem terminala, gdzie szukanie to Ctrl+Shift+F, a Ctrl+PageDown / Ctrl+PageUp przełączają terminale. Większość skrótów można zmienić w Ustawienia › Skróty klawiszowe.</p>',
  ]),
  ('trouble', 'Gdy coś pójdzie nie tak', [
    '<p><strong>macOS mówi, że nie mógł sprawdzić aplikacji (Przenieś do Kosza / Gotowe).</strong> Kliknij Gotowe, potem Ustawienia systemowe › Prywatność i ochrona › przewiń do sekcji Ochrona › <em>Otwórz mimo to</em> i potwierdź hasłem. W macOS 14 lub starszym prawy przycisk › Otwórz robi to w jednym kroku. Jeśli nadal odmawia, w Terminalu: <code>xattr -d com.apple.quarantine /Applications/ygd-editor.app</code>. Jeśli mówi, że aplikacja jest <em>uszkodzona</em>, pobrany plik jest uszkodzony: pobierz go ponownie i porównaj z <code>SHA256SUMS.txt</code>.</p>'
    '<p><strong>Jak w ogóle uniknąć ostrzeżenia.</strong> Zainstaluj z Terminala: <code>curl -fsSL https://mhguitarte.github.io/ygd-editor/install.sh | bash</code>. Sprawdza pobrany plik tak, jak zrobiłby to macOS, i umieszcza aplikację w folderze Aplikacje; więcej na stronie pobierania.</p>'
    '<p><strong>Windows blokuje instalator.</strong> SmartScreen › Więcej informacji › Uruchom mimo to. Wydawca powinien brzmieć <em>ygd-editor release signing</em>.</p>'
    '<p><strong>AppImage się nie uruchamia.</strong> Uruchom go z <code>--appimage-extract-and-run</code> albo zainstaluj <code>libfuse2</code>.</p>'
    '<p><strong>Dostawca pokazuje „Nie zainstalowano”.</strong> Codex i Gemini CLI są pobierane na żądanie: kliknij <em>Pobierz</em> na karcie; jeśli pobieranie się nie uda, karta mówi dlaczego (brak sieci albo plik, który nie zgadzał się z sumą kontrolną i został odrzucony). W przypadku Claude Code kliknij <em>Zainstaluj Claude Code</em> na jego karcie; jeśli to twoja własna instalacja, otwórz terminal, sprawdź, czy <code>claude --version</code> działa, a potem Ustawienia › Dostawcy AI › Skanuj ponownie.</p>'
    '<p><strong>Błędy gita.</strong> Aplikacja wyjaśnia typowe w jednym zdaniu — dane logowania, zdalne repozytorium, które poszło dalej, plik blokady, niezacommitowane zmiany, konflikty — a pełne wyjście trzyma w terminalu worktree.</p>'
    '<p><strong>Nie pojawia się żadna aktualizacja.</strong> Sprawdź Ustawienia › O aplikacji i aktualizacje › Proponuj aktualizacje, potem Sprawdź aktualizacje; aplikacja musi mieć dostęp do github.com.</p>'
    '<p><strong>Aktualizacja została odrzucona jako niepodpisana przez projekt.</strong> Nic nie zostało zainstalowane. Pobierz instalator ze strony <a href="{prefix}releases.html">Wszystkie wersje</a> i sprawdź go tak, jak wyjaśnia <a href="{prefix}index.html#genuine">Czy pobrany plik jest autentyczny?</a>.</p>'
    '<p><strong>Ustawienia nie zapisują się po powrocie do starszej wersji.</strong> Starsza aplikacja nie rusza plików zapisanych przez nowszą, działa na ustawieniach domyślnych i mówi, o który plik chodzi. Zaktualizuj ponownie, a wszystko będzie tam, gdzie to zostawiłeś.</p>'
    '<p><strong>Zgłaszanie problemu.</strong> Ustawienia › Diagnostyka pokazują to, czego potrzebuje zgłoszenie błędu: wersje aplikacji, gita i każdego CLI agenta, PATH, który dostają agenci, działające procesy agentów i bieżący dziennik, który można filtrować. <em>Poziomy dziennika</em> ustalają, ile jest zapisywane — <code>info, git=debug</code> zapisuje szczegóły gita. <em>Przygotuj pakiet…</em> zbiera wszystko w zip i wymienia każdy plik, żebyś mógł go przeczytać przed <em>Zapisz zip…</em>: tokeny i klucze API są zamaskowane, to, co wpisano agentom i w terminalach, jest pominięte, a twój folder domowy widać jako <code>~</code>. Dołącz go do <a href="https://github.com/{repo}/issues">issue</a>, opisując swoje kroki, oczekiwany wynik i to, co się stało.</p>',
  ]),
  ('uninstall', 'Odinstalowanie', [
    '<strong>Zanim ją usuniesz</strong> — oba kroki są opcjonalne. Jeśli w domyślnym worktree jest <em>bieżący</em> worktree, kliknij <em>Zakończ</em>, żeby domyślny worktree odzyskał swoją gałąź i zmiany. Aby wylogować się z dostawcy, użyj <em>Odłącz</em> na jego karcie w Ustawienia › Dostawcy AI: logowania należą do Claude Code, Codex i Gemini CLI, a nie do aplikacji, więc usunięcie aplikacji ich nie kończy. Potem zamknij ygd-editor.',
    '<strong>macOS.</strong> Przeciągnij <strong>ygd-editor</strong> z folderu Aplikacje do Kosza — z <code>~/Applications</code>, jeśli umieściła ją tam instalacja z Terminala.',
    '<strong>Windows.</strong> Ustawienia › Aplikacje › Zainstalowane aplikacje › ygd-editor › <em>Odinstaluj</em> albo Panel sterowania › Programy i funkcje.',
    '<strong>Linux.</strong> Usuń plik AppImage. Dla pakietu Debian / Ubuntu: <code>sudo apt remove ygd-editor</code>.',
    '<strong>Co zostaje.</strong> Twoje ustawienia, przestrzenie robocze, historia sesji i pobrane Codex i Gemini CLI są w folderze <code>.ygd-editor</code> w twoim katalogu domowym, a odinstalowanie ich nie usuwa, więc po ponownej instalacji wszystko wraca. Aby usunąć także je, razem z pamięcią podręczną aplikacji, uruchom to po odinstalowaniu:',
    '<p>macOS:</p><pre>rm -rf ~/.ygd-editor ~/Library/Application\\ Support/ygd-editor ~/Library/Caches/ygd-editor-updater ~/Library/Caches/com.mhguitarte.ygd-editor* ~/Library/HTTPStorages/com.mhguitarte.ygd-editor ~/Library/Preferences/com.mhguitarte.ygd-editor.plist</pre>',
    '<p>Windows (PowerShell):</p><pre>Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\\.ygd-editor", "$env:APPDATA\\ygd-editor", "$env:LOCALAPPDATA\\ygd-editor-updater"</pre>',
    '<p>Linux:</p><pre>rm -rf ~/.ygd-editor ~/.config/ygd-editor ~/.cache/ygd-editor-updater</pre>',
    '<strong>Co pozostaje nietknięte.</strong> Twoje repozytoria i utworzone worktree to zwykłe foldery git i zostają na swoim miejscu; <code>git worktree remove &lt;folder&gt;</code> usuwa jeden z nich. Jeśli aplikacja zainstalowała za ciebie Claude Code, zostaje on w twoim katalogu domowym — <a href="https://docs.anthropic.com/en/docs/claude-code">dokumentacja Anthropic</a> wyjaśnia, jak go usunąć.',
  ]),
  ('privacy', 'Prywatność i bezpieczeństwo', [
    '<p>Wszystko działa na twoim komputerze. Sama aplikacja łączy się z internetem w dwóch celach: sprawdza wydania na tej stronie w poszukiwaniu aktualizacji i raz dziennie pobiera z models.dev publiczną listę modeli i ich cen. Agenci rozmawiają ze swoimi dostawcami przez twoje konta; git rozmawia z twoimi zdalnymi repozytoriami przez twoje dane logowania. Tokeny dostawców, które aplikacja przechowuje, trafiają do pęku kluczy systemu operacyjnego. Interfejs działa w piaskownicy, każde żądanie, które wskazuje ścieżkę, jest sprawdzane względem repozytoriów, które faktycznie otwarto, a żadne polecenie nie jest nigdy budowane z ciągu znaków powłoki. Pakiet diagnostyczny zapisuje się tam, gdzie wskażesz, i nie jest nigdzie wysyłany.</p>'
    '<p>Aby sprawdzić, czy pobrany plik naprawdę pochodzi od nas, zobacz <a href="{prefix}index.html#genuine">Czy pobrany plik jest autentyczny?</a> na stronie pobierania.</p>',
  ]),
 ],
 # strona wersji i wspólne krótkie teksty
 'dl_version': 'wersja {v}',
 'genuine_details': 'szczegóły techniczne',
 'lang_label': 'Język',
 'title_releases': 'ygd-editor — wszystkie wersje',
 'r_h1': 'Wszystkie wersje',
 'r_lead': 'Każda opublikowana wersja ygd-editor. Najpierw najnowsza dla każdego systemu, potem cała historia, system po systemie. Strona pobierania zawsze oferuje najnowszą kompletną wersję; ta lista jest dla tych, którzy potrzebują konkretnej.',
 'r_latest_h': 'Najnowsza dla każdego systemu',
 'r_all_h': 'Każda wersja, według systemu',
 'r_systems': {'mac': 'macOS', 'win': 'Windows', 'linux': 'Linux'},
 'r_loading': 'Wczytuję wersje…',
 'r_error': 'Nie udało się odczytać listy wersji ({err}).',
 'r_github': 'Wydania na GitHub',
 'r_none': 'Nie opublikowano jeszcze żadnej wersji.',
 'r_notes': 'Co się zmieniło',
 'r_checksums': 'Sumy kontrolne',
 'r_updates': 'Zainstalowane aplikacje same aktualizują się do najnowszej kompletnej wersji; niczego stąd nie trzeba pobierać ręcznie, chyba że chcesz konkretną.',
}
