# Türkçe. Strings of the download page, the guide and the versions page. HTML fragments and
# {placeholders} stay as they are; keys match tools/strings/en.py, which is the reference.
T = {
 'title_index': 'ygd-editor — indir', 'title_guide': 'ygd-editor — kullanım kılavuzu',
 'desc': 'ygd-editor: yapay zekâ kodlama ajanlarını ayrı git worktree’lerinde çalıştır, değişikliklerini incele ve yayınla; hepsi tek pencereden. macOS, Windows ve Linux için ücretsiz.',
 'nav_download': 'İndir', 'nav_guide': 'Kılavuz', 'nav_releases': 'Tüm sürümler', 'nav_issues': 'Sorun bildir',
 'tagline': 'Her göreve kendi dalını ve kendi yapay zekâ ajanını ver — ve hepsini gözünün önünde tut.',
 'hero_p': 'ygd-editor her görevi kendi git worktree’sinde açar, içinde bir kodlama ajanı çalıştırır (Claude Code, Codex veya Gemini CLI) ve pencereden çıkmadan değişiklikleri incelemene, commit ve push yapmana ve pull request açmana izin verir. macOS, Windows ve Linux için ücretsiz.',
 'dl_loading': 'En son sürüm aranıyor…', 'dl_for': '{label} için indir', 'dl_none': 'Henüz yayınlanmış sürüm yok', 'dl_none_hint': 'İlk sürüm yolda.',
 'dl_error': 'Tüm sürümleri gör', 'dl_error_hint': 'En son sürüm okunamadı ({err}). Sürümler sayfasında tüm indirmeler var.',
 'dl_others': 'Diğer sistemler:', 'dl_checksums': 'Sağlama toplamları', 'dl_free': 'Ücretsiz · hesap gerekmez · kendini günceller',
 'kinds': {'mac-arm64': 'macOS · Apple Silicon (M1 ve sonrası)', 'mac-x64': 'macOS · Intel', 'win-x64': 'Windows', 'linux-appimage': 'Linux · AppImage', 'linux-deb': 'Linux · Debian / Ubuntu'},
 'shot_console': 'Konsol: solda worktree’ler, ortada değişiklikler ve diff, sağda ajan oturumu.',
 'what_h': 'Neler sunuyor',
 'what': [
   ('Her göreve bir worktree', 'Her dalın kendi klasörü var; ajanlar birbirinin ayağına basmaz ve hiçbir şeyi stash’lemeden görev değiştirirsin.'),
   ('Ajanlar kodun olduğu yerde', 'Claude Code, Codex veya Gemini CLI’ı bir worktree’nin içinde başlat, çalışmasını izle, sorularını yanıtla ve planlar değişince oturumu başka bir worktree’ye devret.'),
   ('Yerinden kalkmadan incele ve yayınla', 'Dosyaları stage’e al, diff’i oku, ajandan bir seçimi açıklamasını veya değiştirmesini iste, commit ve push yap, pull request’i aynı ekrandan aç.'),
   ('İşine karışmaz', 'Seni bekleyen tüm oturumlar ve uygulamanın sana söylediği her şey için tek bir gelen kutusu, isteğe bağlı masaüstü bildirimleri ve senin belirlediğin limitlerle günlük harcama göstergesi.'),
   ('Birkaç yolla dene', 'Bir görevi aynı anda iki ila dört ajan ya da modelle, her birini kendi worktree’sinde çalıştır, yaptıklarını yan yana karşılaştır ve en iyisini tut.'),
   ('Günü değil, bir turu geri al', 'Ajanın her turu neyi değiştirdiğini gösterir ve tek başına geri alınabilir — senin düzenlemelerin ve diğer turlar yerinde kalır.'),
 ],
 'install_h': 'Bir dakikada kur',
 'install_intro': 'Bilgisayarın ilk seferinde seni uyaracak. Bu beklenen bir şey: kimse Apple’a ya da Microsoft’a sertifika parası ödemedi ve uyarı eksik evrak işiyle ilgili, uygulamanın yaptığı bir şeyle değil. Şöyle geçilir — bir kez, ve o bilgisayarda bir daha asla.',
 'install': [
   ('macOS', ['İndirdiğin <code>.dmg</code> dosyasını aç. Bir pencere bu adımları senin dilinde gösterir — <em>Devam</em>’a tıkla — sonra <strong>ygd-editor</strong>’ü Uygulamalar klasörüne sürükle.', 'Uygulamayı aç. macOS uygulamayı <em>doğrulayamadığını</em> söyler ve <em>Çöp Sepeti’ne Taşı</em> ya da <em>Bitti</em> seçeneklerini sunar: <strong>Bitti</strong>’ye tıkla.', '<strong>Sistem Ayarları › Gizlilik ve Güvenlik</strong>’i aç, <em>Güvenlik</em> bölümüne kadar in ve ygd-editor’ün yanındaki <strong>Yine de Aç</strong>’a tıkla. Parolanla onayla. Hepsi bu — macOS bir daha sormaz.', 'macOS 14 veya daha eskisinde <strong>uygulamaya sağ tıkla › Aç</strong> aynı şeyi tek adımda yapar.', 'Hangi Mac’e sahip olduğundan emin değil misin? Apple menüsü › Bu Mac Hakkında: “Apple M…” yazıyorsa Apple Silicon, “Intel” geçiyorsa Intel.']),
   ('Windows', ['Yükleyiciyi çalıştır. SmartScreen “Windows bilgisayarınızı korudu” dediğinde <strong>Ek bilgi</strong>’ye, sonra <strong>Yine de çalıştır</strong>’a tıkla.', 'Gösterilen yayımcı <em>ygd-editor release signing</em> — o biziz. İstersen kurulum klasörünü seç ve bitir.', 'Uygulama Başlat menüsünde ygd-editor olarak görünür.']),
   ('Linux', ['<strong>AppImage:</strong> çalıştırılabilir yap (<code>chmod +x ygd-editor-*.AppImage</code>) ve çalıştır. FUSE hakkında şikâyet ederse <code>--appimage-extract-and-run</code> ile çalıştır.', '<strong>Debian / Ubuntu:</strong> <code>sudo apt install ./ygd-editor-*.deb</code>, sonra uygulama menünde bul.']),
 ],
 'cli_h': 'Uyarı olmadan: Terminal’den kur.',
 'cli_p': 'Bunu Terminal’e yapıştır (Uygulamalar › İzlenceler). Mac’in için en son sürümü indirir; sağlama toplamlarının projenin imzasını taşıdığını, indirilen dosyanın onlarla eşleştiğini ve uygulamanın projenin sertifikasıyla imzalandığını denetler, sonra Uygulamalar klasörüne koyar. Denetimlerden biri başarısız olursa hiçbir şey kurmaz. macOS hiçbir şey sormaz, çünkü hiçbir şey tarayıcıdan gelmedi. Yeniden kurmak için istediğin zaman tekrar çalıştır.',
 'cli_copy': 'Kopyala', 'cli_copied': 'Kopyalandı',
 'cli_or': 'Ya da yukarıdaki düğmeden disk görüntüsüyle:',
 'need_h': 'Neye ihtiyacın var', 'need_p': 'Bilgisayarında Git ve en az bir sağlayıcıda bir hesap. <a href="https://github.com/openai/codex">Codex</a> ve <a href="https://github.com/google-gemini/gemini-cli">Gemini CLI</a> yükleyicinin içinde değildir — onu küçük tutan da budur —: uygulama seçtiğini ilk istediğinde indirir (Codex için yaklaşık 130–150 MB, Gemini CLI için 20 MB) ve çalıştırmadan önce bu sürümün yapıldığı sürümle karşılaştırıp doğrular; lisansı birlikte dağıtılmasına izin vermeyen <a href="https://docs.anthropic.com/en/docs/claude-code">Claude Code</a> için Ayarlar › Yapay zekâ sağlayıcıları, Anthropic’in resmî yükleyicisini senin için çalıştıran tek tıklık bir seçenek sunar. Bir sağlayıcıyı bağlamak, giriş sayfasını tarayıcında açar. Pull request’ler için GitHub’da <code>gh</code>, GitLab’da <code>glab</code>. Uygulama 64 bit Windows 10 ya da 11’de ve glibc 2.34 veya daha yenisi olan x86-64 Linux’ta çalışır (Ubuntu 22.04, Debian 12, Fedora 35 ve sonrası).',
 'updates_h': 'Güncellemeler kendi kendine olur',
 'updates_p': 'Açılıştan kısa süre sonra ve açık kaldığı sürece her altı saatte bir, uygulama yeni bir sürüm olup olmadığına bakar ve varsa sana söyler. Tek tıkla indirilir; ne zaman kurulacağını sen seçersin: şimdi yeniden başlatarak ya da bir sonraki çıkışta. Bir güncelleme yalnızca sürümün sağlama toplamları projenin imzasını taşıyorsa kurulur; diğer her şey reddedilir. Ayarlar › Hakkında ve güncellemeler’de bir “Güncellemeleri kontrol et” düğmesi var ve yeni sürümleri kendi başına indirebilir. Güncellemeden sonra “Yenilikler”, uygulamadan çıkmadan nelerin değiştiğini gösterir.',
 'genuine_h': 'İndirdiğim dosya gerçek mi?',
 'genuine_p': 'Birbirinden bağımsız iki kontrol; ikisi de bir isme güvenmeye dayanmaz. Bunları çalıştırman gerekmez; isteyenler için buradalar.',
 'genuine_sums': '<strong>İmzalı sağlama toplamları.</strong> 0.17.2’den bu yana her sürüm, <code>SHA256SUMS.txt</code> dosyası ve onun imzası <code>SHA256SUMS.txt.sig</code> ile gelir; imza projenin anahtarıyla, yani sertifikasının (<a href="{pem}"><code>release-signing.pem</code></a>) arkasındaki anahtarla atılır. İkisini indirdiğin dosyanın yanına koy ve önce sertifikanın parmak izini buradakiyle karşılaştır: geri kalan her şeyi kanıtlayan adım budur, çünkü bir yükleyiciyi değiştirebilen biri yanındaki sertifikayı da değiştirebilir. Ardından imza sağlama toplamlarına, sağlama toplamları da her dosyaya kefil olur. Yalnızca <code>openssl</code> gerekir (macOS ve Linux’ta var; Windows’ta Git Bash kullan). Önce <code>Verified OK</code>, sonra dosyan için <code>OK</code> görmelisin:',
 'genuine_prov': '<strong>Eski sürümler.</strong> 0.6.0 ile 0.17.1 arasındaki sürümler imzasız bir <code>SHA256SUMS.txt</code> ile gelir ve onlara kefil olan, aşağıdaki kod imzasıdır. 0.1.0 ile 0.4.0 arasındakileri projenin GitHub’daki yayın iş akışı derledi; bunlarda onun yerine iş akışının <a href="https://www.sigstore.dev/">Sigstore</a> imzası, <code>SHA256SUMS.txt.sigstore.json</code> bulunur. <code>cosign</code> kuruluyken:',
 'genuine_sig': '<strong>Kod imzası.</strong> macOS uygulaması ve Windows yükleyicisi projenin sertifikasıyla imzalanmıştır (<a href="{pem}">açık anahtar</a>). İsmi değil parmak izini karşılaştır — bir sertifikaya herkes istediği ismi verebilir.',
 'guide_cta_h': 'Yeni misin?', 'guide_cta_p': '<a href="{prefix}guide.html">Kullanım kılavuzu</a> ilk on dakikayı adım adım anlatır: bir depo açmak, bir worktree oluşturmak, bir ajan başlatmak, sonucu incelemek ve yayınlamak.',
 'footer_made': 'Manu Hurtado tarafından yapıldı. Uygulama ücretsizdir; kaynak kodu kapalıdır.',
 # guide
 'g_h1': 'Kullanım kılavuzu', 'g_lead': 'ygd-editor ile ilk öğleden sonran için gereken her şey, sade sözlerle. Okuması on dakika; listeden istediğin bölüme geri dönebilirsin.',
 'g_toc': 'Bu sayfada',
 'g_sections': [
  ('idea', 'Fikir, bir dakikada', [
    'Bir git <em>worktree</em>’si, aynı deponun başka bir dalda checkout edilmiş ikinci bir klasörüdür. Tek klasörde dal değiştirmek — ve her seferinde stash’lemek, yeniden derlemek ve kaldığın yeri kaybetmek — yerine görev başına bir klasör tutarsın.',
    'ygd-editor bunun etrafında kurulu: sol panel worktree’lerini listeler, ortadaki seçtiğinde neyin değiştiğini gösterir, sağdaki ise içinde bir yapay zekâ ajanı çalıştırır. İki görevdeki iki ajan iki klasörde çalışır ve asla çarpışmaz. Biri yanıt beklerken üst bardaki gelen kutusu sana haber verir.',
    '<img src="{img}start.png" alt="Başlangıç sayfası: son depolar ve başlangıç eylemleri" loading="lazy">',
  ]),
  ('first', 'İlk on dakikan', [
    'Yeni bir kurulumda başlangıç sayfası bir <em>Başlarken</em> listesi gösterir: git, bir yapay zekâ sağlayıcısı, bir depo, ilk worktree ve ilk oturum. Her adımın onu yapan bir düğmesi vardır ve adım tamamlanınca kendiliğinden işaretlenir; <em>Bu listeyi gizle</em> onu kalıcı olarak kaldırır. Aşağıda aynı adımlar, daha ayrıntılı.',
    '<ol>'
    '<li><strong>Bir depo aç.</strong> Başlangıç sayfasında <em>Depo aç</em>’ı seç ve içinde zaten git olan bir klasör seç, ya da <em>Depo klonla</em> ile bir GitHub, GitLab veya herhangi bir git URL’si kullan. Son depolar başlangıç sayfasında kalır.</li>'
    '<li><strong>Bir worktree oluştur.</strong> <em>Yeni worktree</em> (⌘N) görevden bir dal adı ve onu koyacak bir klasör önerir; ikisini de kullandığın kurala göre dilediğin gibi yeniden adlandırabilirsin. Git dal adında boşluğa izin vermez, bu yüzden boşluklar tireye dönüşür ve iletişim kutusu bir şey oluşturmadan önce sonucu gösterir. Worktree’lerin diskte nereye gideceği ve isteğe bağlı önerilen önek Ayarlar › Git’te.</li>'
    '<li><strong>Bir oturum başlat.</strong> Sağ paneldeki <em>+ Oturum</em> bir ajan ve bir model seçer; varsayılan ajan Ayarlar › Varsayılan ajan’da. Ne istediğini yazma alanına yaz. <code>@</code> dosya ya da geçerli diff gibi bağlam ekler, <code>/</code> ajanın komutlarını, <code>#</code> skill’lerini çalıştırır. ⌘↵ gönderir.</li>'
    '<li><strong>Çalışmasına izin ver — ya da durdur.</strong> Transkript ajanın kullandığı her aracı gösterir. Önceden onaylamadığın bir şey için izin gerektiğinde oturum <em>bekliyor</em> durumuna geçer, üst bardaki gelen kutusu onu sayar ve sen onaylar ya da reddedersin — “Her zaman izin ver” seçimini o worktree için hatırlar. <em>Durdur</em> keser; o çalışırken yazdığın istemler sıraya alınır.</li>'
    '<li><strong>Değişiklikleri incele.</strong> Değişiklikler sekmesi dokunulan her dosyayı kimin değiştirdiğiyle birlikte listeler. Diff için bir dosyaya tıkla; satırları seç ve ajana geri göndermek için <em>Açıkla</em> ya da <em>Değişiklik iste</em>’yi seç. Aynı deponun başka bir worktree’sinin de dokunduğu dosyaları bir uyarı işaretler.</li>'
    '<li><strong>Commit, push, PR’ı aç.</strong> Stage’e alınacak dosyaları işaretle, mesajı yaz ya da <em>Yapay zekâ ile yaz</em>, <em>Commit</em>. <em>Push</em> upstream’i ayarlar; <em>Pull request aç</em> başlığı, gövdeyi (istersen diff’ten taslak olarak), taslak işaretini, gözden geçirenleri ve etiketleri doldurur ve işi <code>gh</code> ya da <code>glab</code>’a devreder. Worktree kartı sonra PR’ı ve kontrollerini gösterir.</li>'
    '</ol>',
    '<img src="{img}console.png" alt="Açık bir diff ve çalışan bir Claude Code oturumuyla konsol" loading="lazy">',
  ]),
  ('daily', 'Günlük kullanımda', [
    '<p><strong>Ana worktree</strong> — depoyu açtığın klasör — diğerleriyle birlikte listelenir ve yeni worktree’lerin dallandığı yerdir. Onu seç ve üst barda dal adına tıkla: tüm dalları kapsayan bir arama kutusu açılır — seninkiler ya da yalnızca uzak depoda bulunan ve yeni bir izleme dalı olarak checkout edilen bir dal. Daraltmak için yaz, geçmek için ok tuşları ve Enter. Başka bir worktree’nin zaten tuttuğu bir dal listelenir ama gri görünür, çünkü git bir dala aynı anda tek bir worktree’de izin verir.</p>'
    '<p>Bir worktree’de <strong>Temel daldan güncelle</strong> fetch yapar ve onu temel dalın üzerine rebase eder; çakışmalar dosyalar listelenmiş halde durur, onları çözersin, stage’e alırsın ve <em>Devam</em>. <strong>Fetch</strong> ileri/geri sayaçlarını yeniler. Terminal sekmesi worktree klasöründe gerçek bir kabuktur; Etkinlik, orada olanların — commit’ler, push’lar, oturumlar — zaman çizelgesidir ve yeniden başlatmalarda kaybolmaz.</p>'
    '<p><strong>Devretme.</strong> İşin başka bir dala ait olduğunu fark ettiğinde bir oturum, menüsünden, transkriptiyle birlikte başka bir worktree’ye taşınabilir.</p>'
    '<p><strong>Bir worktree’yi kaldırmak</strong> oturumlarını sonlandırır, günlüklerini arşivler ve izin kurallarını unutur; sen silmezsen dal kalır. Ayarlar › Git, PR’ı birleştikten sonra worktree’yi kendi başına silebilir.</p>'
    '<p><strong>Birden fazla depo.</strong> İstediğin kadar aç; üst bar aralarında geçiş yapar ve gelen kutusu hepsindeki bekleyen oturumları sayar.</p>',
  ]),
  ('git', 'Terminalsiz git', [
   '<strong>Pull ile Temel daldan güncelle ayrı şeylerdir.</strong> <em>Pull</em> kendi dalına gönderilenleri — örneğin bir ekip arkadaşının commit’ini — getirir, böylece bir sonraki push’un geçer; iki tarafta da yeni commit’ler varsa Ayarlar › Git’te ne yazıyorsa ona göre rebase ya da merge yapar, ya da sorar. <code>···</code> menüsündeki <em>Temel daldan güncelle</em> diğer iştir: temel dala yetişmek.',
   '<strong>Çakışmalar.</strong> Bir rebase, merge, revert ya da cherry-pick çakışmalarda durduğunda dosyayı aç ve blok blok çöz: bir tarafı, diğerini tut ya da <em>İkisi de kalsın</em> — veya dosyanın tamamını al, ya da <em>Ajana sor</em>. İki taraf o an olana göre adlandırılır, böylece hangisinin “bizimki” olduğunu tahmin etmen gerekmez. <em>Çözüldü olarak işaretle</em>, sonra şeritte <em>Devam et</em>.',
   '<strong>Amend.</strong> Commit kutusunda bir <em>Düzelt (amend)</em> anahtarı var. Henüz göndermediğin bir commit basitçe yeniden yazılır. Gönderdiğin bir commit ise asla zorla gönderilmez: uygulama onu yeni bir dala koyar, o dalı gönderir, yeni bir pull request açar ve eskisini yenisine bir bağlantıyla kapatır.',
   '<strong>Geçmiş.</strong> Etkinlik’teki bir commit’e sağ tıklayarak <em>SHA’yı kopyala</em>, <em>Değişiklikleri göster</em>, <em>Geri al (revert)</em> ya da başka bir worktree’ye <em>Şuraya cherry-pick…</em> yapabilirsin.',
   '<strong>Pull request’ler.</strong> PR kartı her kontrolü, her gözden geçirenin kararını ve inceleme yorumlarını dosyası ve satırıyla listeler. <em>İncelemeyi ele al</em> açık yorumları ajana verir; <em>Birleştir</em> deponun izin verdiği yöntemleri sunar ve henüz olmuyorsa nedenini söyler. İş içeri girdiğinde <em>Birleştirilmiş worktree’leri temizle…</em> biten tüm worktree’leri tek seferde kaldırır ve bıraktıklarını adıyla söyler.',
   '<strong>Fork’lar.</strong> Bir fork’ta <code>origin</code> senin kopyan, <code>upstream</code> ise projedir. Uygulama, varsa temel dalı <code>upstream</code>’den okur; böylece yeni bir worktree fork’undaki eskimiş kopyadan değil <code>upstream/main</code>’den başlar, push’lar ve pull request’ler ise yine fork’una gider; <em>Fetch</em> ikisinden de çeker. Ayarlar › Git › <em>Temel uzak depo</em> başka bir uzak depo seçer ve Uzak depolar penceresi onu <em>base</em> olarak işaretler.',
   '<strong>Bare depolar.</strong> Bir depo, klasörlerinin herhangi birinden bütün olarak açılır: ana klasör, bağlı bir worktree, yanında worktree’leriyle bare bir <code>api.git</code> ya da bir <code>proj/.bare</code> düzeni. Tüm worktree’ler listelenir. Bare bir deponun ana worktree’si yoktur; bu yüzden herhangi bir worktree kaldırılabilir, yenileri bare klasörün yanına gider (<code>api--fix</code>) ve <em>Geçerli yap</em> ile ana worktree’nin dalını değiştirme sunulmaz.',
  ]),
  ('review', 'Bir ajanın yaptıklarını incelemek', [
   '<strong>Her seferinde bir tur.</strong> Dosya değiştiren her tur, dökümde altında bir satırla biter — <em>4 dosya değişti · +120 −8</em>. Ona tıkla, Değişiklikler sekmesi yalnızca o turun yaptığını gösterir. <em>Bu turu geri al…</em> önce her dosyaya ne olacağını listeler, sonra turun değişikliklerini çıkarır: o zamandan beri kimsenin dokunmadığı bir dosya eski haline döner, senin ya da sonraki bir turun düzenlediği bir dosya bu düzenlemeleri korur, ikisinin de aynı satırları değiştirdiği yerlerde çözülecek çakışma işaretleri kalır. Geri alma da başlı başına bir turdur, yani o da geri alınabilir.',
   '<strong>Blok blok.</strong> Bir diff’in her bloğunda <em>Stage’e al</em> ve <em>At</em> vardır (stage’deyse <em>Stage’den çıkar</em>); yalnızca bazı satırları stage’e almak ya da atmak için onları seç. Kısmen stage’de olan bir dosyanın diff’inin üstünde <em>Stage’de / Stage dışı</em> seçicisi olur.',
   '<strong>Eski bir konuşmayı bulmak.</strong> Oturumlar panelinin üstündeki <em>Oturumlarda ara</em>, bu worktree’de, depoda ya da çalışma alanında söylenenlerde arar — <em>arşivlenmiş</em> kutusunu işaretlersen kaldırdığın worktree’lerde de. Bir sonuç oturumu o mesajda açar. Bir oturuma sağ tıklayıp <em>Dökümü dışa aktar…</em> seç: istemleri, yanıtları ve araç çağrılarını içeren bir Markdown dosyası. İçinde hiçbir şey gizlenmez, paylaşmadan önce oku.',
   '<strong>Uzun bir değişikliği okumak.</strong> Değişiklikler listesi dosyaları klasöre göre gruplar — filtrenin yanındaki klasör düğmesi düz listeye geçer — ve filtre yazdığın her kelimeyi içeren yolları bırakır. Okuduğun her dosyada <em>Görüldü</em>’yü (V) işaretle: ajan o dosyayı yeniden değiştirirse işaret kendiliğinden kalkar, <em>Sonraki görülmemiş</em> (⇧N) seni bir sonrakine götürür. Diff’te N ve P bloktan bloğa atlar, W uzun satırları kaydırır. Değişen kelimeler satır içinde vurgulanır, kod diline göre renklendirilir, panel daraldığında yan yana görünüm birleşik görünüme geçer, görseller önce ve sonra hâliyle gösterilir ve bir Markdown dosyası <em>İşlenmiş</em> olarak gösterilebilir.',
   '<strong>Yanlışlıkla mı attın?</strong> <em>At</em>, <em>Tüm değişiklikleri at</em>, bir bloğu ya da birkaç satırı atmak ve bir worktree’yi zorla kaldırmak, attıklarını saklar. Uyarıdaki <em>Geri al</em> geri getirir; daha sonra <em>Stash’ler › Son atılanlar</em>’da <em>Geri yükle</em> vardır, <em>Stash olarak kaydet</em> de bir girdiyi sıradan bir stash’e çevirir — kaldırdığın bir worktree’nin değişikliklerine dönüş yolu budur. <em>Tüm değişiklikleri stash’le</em> de Geri al sunar.',
   '<strong>Büyük depolar.</strong> 2.000’den fazla izlenmeyen dosya olduğunda liste ilk 2.000’i ve geri kalanı sayan klasör başına bir satır gösterir; <em>Tümünü stage’e al</em>, <em>Commit</em> ve <code>.gitignore</code> yine hepsini kapsar. 10 MB’tan büyük izlenmeyen dosyalar tur kontrol noktalarının dışında bırakılır ve turun alt satırı kaç tane olduğunu söyler. Worktree’yi okumak 5 saniyeden uzun sürerse tur kontrol noktası almaz ve alt satırı turun açılamayacağını ya da geri alınamayacağını söyler. <code>node_modules</code>, <code>dist</code>, <code>.next</code> ve <code>target</code> içindeki değişiklikler artık listeyi yenilemez, uygulama dışında yapılan düzenlemeler ise uzun bir push ya da fetch sırasında bile görünür.',
  ]),
  ('sessions', 'İş başındaki ajanlar', [
   '<strong>Dökümü okumak.</strong> Yanıtlar biçimlendirilmiş metin olarak görünür ve her kod bloğunun bir <em>Kopyala</em> düğmesi vardır. Art arda üç veya daha fazla araç çağrısı, açınca onları gösteren tek bir satıra katlanır. Worktree’deki bir dosyanın yolu bir bağlantıdır: değişmiş bir dosya diff’ini açar, diğerleri editöründe açılır. Okumak için yukarı kaydırdığında döküm akışı izlemeyi bırakır; <em>En sona git</em> seni geri götürür. Bir oturum izin isterken durdurulduysa döküm bunu söyler.',
   '<strong>Uzun oturumlar.</strong> Bir oturum en son mesajlarında açılır, <em>Önceki mesajları göster</em> ise gerisini istediğinde yükler. Geçmişin sonsuza dek büyümemesi için Ayarlar › Varsayılan ajan’da <em>Oturumları sakla</em> (gün) ve <em>Oturum depolama sınırı</em> (MB) var: uygulama açılırken daha eski olanı ya da sınırı aşanı siler. İkisi de sen ayarlayana kadar kapalıdır.',
   '<strong>Durdurmak gerçekten durdurur.</strong> <em>Durdur</em>, bir worktree’yi kaldırmak ve uygulamadan çıkmak, ajanın başlattığı şeyleri de sonlandırır — örneğin bir geliştirme sunucusunu. Model değiştirmek bunu yapmaz, boşta kalma sınırı da: Ayarlar › Varsayılan ajan › <em>Boştaki ajanları şu süreden sonra sonlandır</em> (değiştirmezsen 30 dakika; boş bırakmak hiçbir zaman demek) bu kadar süre boşta kalan bir ajanı belleğini geri vermek için sonlandırır, bir sonraki istemin de konuşmayı kaldığı yerden sürdürür. Uygulama ajanlar hâlâ çalışırken çöktüyse bir sonraki açılış <em>Durdur</em> ya da <em>Çalışır bırak</em> seçeneklerini sunar.',
   '<strong>Kabuğunun ortamı.</strong> Ajanlar <code>.zshrc</code> ya da <code>.bashrc</code> dosyanın dışa aktardıklarını — bir proxy, API anahtarları, <code>AWS_PROFILE</code> — sanki onları bir terminalden başlatmışsın gibi alır; uygulamanın kendisi Dock’tan ya da bir menüden açılmış olsa bile. Ayarlar › Editör ve terminal › <em>Kabuğumun ortamını kullan</em> bunu kapatır ve getirdiği değişkenlerin adlarını listeler, değerlerini asla. Windows’un buna ihtiyacı yok: orada uygulamalar değişkenlerini zaten alır.',
  ]),
  ('setup', 'Çalışmaya hazır worktree’ler', [
   'Yeni bir worktree’de yok sayılan dosyalarının hiçbiri yoktur — ne <code>.env</code> ne <code>node_modules</code>. <strong>Ayarlar › Worktree hazırlığı</strong> bunu bir kez halleder: ana worktree’den kopyalanacak dosyalar (örneğin <code>.env*</code>), yeni worktree’nin terminalinde çalışacak komutlar (<code>pnpm install</code>) ve bir taban port; böylece her worktree <code>YGD_PORT</code> içinde kendi portunu alır ve iki geliştirme sunucusu aynı port için kavga etmez. Worktree’nin terminali ve ajanları ayrıca <code>YGD_WORKTREE</code> ve <code>YGD_BRANCH</code> alır. Yeni worktree penceresi hazırlığın ne yapacağını gösterir; <em>Hazırlığı yeniden çalıştır</em> <code>···</code> menüsündedir.',
   'Bir depo aynı tarifi <code>.ygd/worktree.json</code> içinde taşıyabilir. Komutları dalı yazan kişiden gelir; bu yüzden uygulama onları gösterir ve ilk kez çalıştırmadan önce sorar — dosya her değiştiğinde de yeniden.',
  ]),
  ('terminals', 'Terminaller', [
   '<strong>Birkaç terminal.</strong> Terminal sekmesindeki <code>+</code> worktree’nin kendi kabuğunun yanında bir kabuk daha açar; yeniden adlandırmak için bir sekmeye çift tıkla. Araç çubuğundaki <em>Çalıştır ▾</em> kayıtlı komutları — <code>dev: pnpm dev</code> — her birini kendi adını taşıyan bir terminalde, <em>Yeniden başlat</em> ve <em>Durdur</em> ile başlatır. Bir istemdeki <code>@terminal:dev</code> o terminalin yazdıklarını ekler.',
   '<strong>Çalışmaya devam ederler.</strong> Ayarlar, başlangıç sayfası ya da karşılaştırma görünümü açıkken bir terminal programını ve geçmişini korur; <code>vim</code>, <code>htop</code> ya da bir geliştirme sunucusu tam bıraktığın gibidir. ⌘F (Windows ve Linux’ta Ctrl+Shift+F) ya da sekmelerin sonundaki büyüteç geçmişte arar. ⌘-tık (Ctrl+tık) bir bağlantıyı tarayıcıda açar. ⌘⇧] ve ⌘⇧[ (Ctrl+PageDown ve Ctrl+PageUp) bir sonraki ve önceki terminale geçer. Hâlâ bir şey çalıştıran bir terminali kapatmak önce sorar ve programın adını söyler.',
  ]),
  ('tryn', 'Birkaç yolla dene', [
   'Bir görevi hangi ajanın ya da modelin en iyi yapacağından emin değil misin? Yeni worktree penceresinde <em>N yolla dene</em> kutusunu işaretle ve iki ila dört deneme seç — Claude Code, Codex ve Gemini CLI, ya da aynı model üç kez. Her biri aynı temelden kendi worktree’sini alır (<code>login-a</code>, <code>login-b</code>…), hazırlık her birinde çalışır ve aynı ilk istem hepsine gider. Her deneme bütçeden düşer ve pencere bunu söyler.',
   'Denemeler kenar çubuğunda bir arada durur. Yan yana karşılaştırmak için girişlerine tıkla: durum, değişen dosyalar ve satırlar, maliyet, turlar ve süre, hızlı bir diff ve kontrol komutun — örneğin Ayarlar › Worktree hazırlığı’ndaki <code>pnpm test</code> — istediğinde her birinde çalışır. <em>Bunu tut</em> diğerlerini listeledikten sonra kaldırır, kazanana soneksiz dal adını verebilir ve doğrudan Geçerli yap’a ya da bir pull request’e geçebilir.',
  ]),
  ('workspaces', 'Birden fazla depoyla çalışmak: çalışma alanları', [
    'Bir <em>çalışma alanı</em>, uygulamanın birlikte açık tuttuğu adlandırılmış bir klasör kümesidir. Bir gateway, bir web konsolu ve bir not klasörü çoğu zaman tek bir işin parçasıdır ve birindeki bir sorunun yanıtı genellikle diğerindedir — çalışma alanı, uygulamaya bunların birbirine ait olduğunu söyleme yolundur.',
    '<img src="{img}workspace.png" alt="İki depolu bir çalışma alanı: kenar çubuğu worktree’leri depoya göre gruplar" loading="lazy">',
    '<strong>Bir tane oluşturmak.</strong> Biri zaten açıkken ikinci bir depo aç; uygulama nereye gideceğini sorar: üzerinde çalıştığına ekle, ikisiyle yeni bir çalışma alanı başlat ya da kendi başına aç. Escape “kendi başına” demektir. Başlangıç sayfasından <em>Yeni çalışma alanı</em> ile de bir tane başlatabilir, sonra üst bardaki çalışma alanları düğmesinden klasör ekleyip çıkarabilirsin. Bir klasörü çalışma alanından çıkarmak hiçbir şeyi silmez — yalnızca küme değişir.',
    '<strong>VS Code’dan.</strong> Ekibin zaten bir <code>.code-workspace</code> dosyası tutuyorsa <em>Çalışma alanı dosyası aç…</em> onu okur: aynı klasörler, aynı sırada, VS Code’un adlandırdığı gibi. Dosyadaki yorumlar ve sondaki virgüller sorun değil. Git deposu olmayan klasörler korunur — yalnızca worktree’leri olmaz — ve kaybolmuş bir klasör sessizce atılmak yerine bildirilir. <em>Dosyaya kaydet</em> onu geri yazar ve uygulamanın kullanmadığı kısımlara dokunmaz; böylece aynı dosya iki araçta da çalışmaya devam eder.',
    '<strong>Kenar çubuğu ne gösterir.</strong> Depoya göre gruplanmış worktree’ler, her grup katlanabilir; filtre dal adıyla da depo adıyla da eşleşir, böylece nerede yaşadığını hatırlamadan bir dalı bulabilirsin. Katlanmış bir grup içinde neyin çalıştığını yine gösterir ve bir oturum beklerken yine söyler. Tek depoda hiç grup görünmez.',
    '<strong>Ajanlar ne görebilir.</strong> Bir oturum yine worktree’sinin <em>içinde</em> çalışır — git ve her göreli yol oraya aittir — ama çalışma alanının diğer klasörlerini de okuyabilir, böylece “bu çağrı nerede bitiyor?” sorusu iki taraftan da yanıtlanabilir. Yalnızca okuyan bir oturumun her yerde yalnızca okumaya izni vardır. Grupların üstünde bir de <em>Çalışma alanı genelinde</em> satırı var: tek bir worktree’ye ait olmayan oturumlar için. Bütün yığını kapsayan soruları onlara sor. Dalları, değişiklikleri ve terminalleri yok, çünkü bunlar bir worktree’ye aittir.',
    '<strong>Ayarlar.</strong> Artık üç düzey var: Genel, çalışma alanı ve tek bir depo. Varsayılan ajan, izin ön ayarı ve temel dal genellikle içindeki her deponun değil yığının bir özelliğidir; o yüzden onları çalışma alanında bir kez ayarla, farklı bir şeye ihtiyaç duyan depo yine geçersiz kılabilir. Ayarlar’daki kapsam seçici düzeyi seçer ve geçersiz kılmayan bir bölüm değerlerinin nereden geldiğini söyler.',
    'Uygulama her çalışma alanını ayrı hatırlar: birine geri döndüğünde bıraktığın depoya, worktree’ye ve panel düzenine düşersin.',
  ]),
  ('current', 'Bir worktree\'yi varsayılan worktree\'de test etmek', [
    'Bir değişikliği denemenin yeri deponun kendi klasörüdür — <em>varsayılan worktree</em> — çünkü <code>node_modules</code>, <code>.env</code>, derleme önbelleği ve çalışan geliştirme sunucusu zaten oradadır. İş ise diğer worktree\'lerde yapılır. <strong>Geçerli yap</strong> bunlardan birini varsayılan worktree\'ye getirir: commit\'leri, henüz commit etmediği değişiklikleri ve yeni dosyaları, varsayılan worktree\'nin dalının üzerine. O andan itibaren başlık her ekranda varsayılan worktree\'nin ne çalıştırdığını söyler — <code>VARSAYILAN · feat-a + feat-b · 1 düzenleme</code> — ve kenar çubuğu <em>varsayılan</em> ve <em>geçerli</em> worktree\'leri işaretler.',
    '<img src="{img}current.png" alt="Başlıktaki şerit, açık: varsayılan worktree\'nin nereden geldiği, iki geçerli worktree ve sonra yapılabilecekler" loading="lazy">',
    '<strong>Değiştir</strong> yerine başka bir worktree koyar. <strong>Ekle</strong> iki değişikliği birlikte denemek için bir tane daha üstüne ekler; ikisi aynı satırlara dokunduğunda yükleme varsayılan worktree\'de bir çakışmada durur ve her dosya için varsayılan tarafı korur, geleni alır ya da düzenleyip çözüldü olarak işaretlersin — sonra <em>Devam et</em> ya da önceki duruma dönmek için <em>İptal et</em>.',
    '<strong>Test sırasında yapılan düzeltmeler eve döner.</strong> Denerken sen — ya da varsayılan worktree\'deki bir ajan — bir şeyi düzeltirsen, <em>Düzenlemeleri geri gönder</em> onu ait olduğu worktree\'ye, orada gözden geçirip commit etmen için commit edilmemiş değişiklikler olarak geri verir; <em>Geri al</em> bir sonraki adıma kadar bunu geri alır. Birden çok geçerli worktree\'ye ya da hiçbirine ait olmayan bir dosya tahmin edilmez, sorulur. Değiştir, Ekle, Yenile ve Bitir önce düzenlemeleri geri gönderir; böylece varsayılan worktree\'de yapılan hiçbir şey kaybolmaz. <em>Düzenlemeleri geri gönder</em>, <em>Bitir</em> ve <em>Bu turu geri al</em> dosyaları bir checkout’un yazacağı gibi yazar — Git LFS, git-crypt ve Windows satır sonları dahil; deponun ihtiyaç duyduğu bir filtre eksikse (örneğin <code>git-lfs</code> kurulu değilse), işaretçi dosyalar bırakmak yerine git’in mesajıyla durur.',
    '<strong>Bitir</strong> varsayılan worktree\'yi tam olarak eskisi gibi geri verir: dalını ve hazırlanmış ya da hazırlanmamış kendi değişikliklerini. Her adım önce kısa bir önizleme açar: ne geliyor, ne kenara alınıyor, hangi dosyalar çakışır ve şu anda neyin engel olduğu, çıkış yoluyla birlikte. Bunları bir worktree\'nin <code>···</code> menüsünde, kenar çubuğunda sağ tıkla, başlık şeridinde ve ⌘⇧D / ⌘⇧E ile bulursun.',
    'Ayarlar › Git, ajanı çalışmaya devam ettiğinde geçerli bir worktree\'yi kendiliğinden yenileyebilir ve her yüklemeden sonra bir komutu — örneğin <code>pnpm-lock.yaml</code> değiştiğinde <code>pnpm install</code> — varsayılan worktree\'nin terminalinde, görebileceğin yerde çalıştırabilir. Kendi <code>git stash</code>\'ine asla dokunulmaz. git 2.40 veya daha yenisi gerekir.',
  ]),
  ('find', 'Hızlı gezinmek ve neye mal olduğu', [
   '<strong>⌘K</strong> komut paletini açar: uygulamadaki her eylem — kısayoluyla ya da şu an neden çalışamadığıyla — artı çalışma alanındaki tüm worktree’lerin, oturumların, Ayarlar sayfaları ve son depoların. Eylemler için <code>&gt;</code>, worktree’ler için <code>@</code>, oturumlar için <code>#</code> ile başla; gerisini ok tuşları ve Enter halleder.',
   '<strong>Neye mal oldu.</strong> Ayarlar › Bütçe’de bir <em>Kullanım raporu</em> var: ajana göre bölünmüş günlük bir çubuk ve her deponun ve her dalın ne harcadığı; son 7, 30 ya da 90 gün veya seçtiğin tarihler için, <em>CSV olarak dışa aktar</em> ile. Rakamlar bütçenin kendi rakamlarıdır, bu yüzden harcama göstergesiyle her zaman tutar.',
  ]),
  ('providers', 'Ajanlar ve sağlayıcılar', [
    '<p>ygd-editor hiçbir yapay zekâ servisiyle kendisi konuşmaz. Zaten sahip olduğun komut satırı araçlarını — <a href="https://docs.anthropic.com/en/docs/claude-code">Claude Code</a>, <a href="https://github.com/openai/codex">Codex</a>, <a href="https://github.com/google-gemini/gemini-cli">Gemini CLI</a> — kendi hesaplarınla çalıştırır; yani kullanım, faturalama ve veri koşulları tam olarak o sağlayıcılarla anlaştığın koşullardır.</p>'
    '<p>Ayarlar › Yapay zekâ sağlayıcıları her sağlayıcıyı kendi hesabınla bağlar: <em>Bağla</em> sağlayıcının giriş sayfasını tarayıcında açar, kart sonra hesabı, planı ve <em>Hesap değiştir</em> / <em>Bağlantıyı kes</em> / <em>Bağlantıyı test et</em> seçeneklerini gösterir. Codex ve Gemini CLI’yi uygulama ilk seçtiğinde indirir — kart sürümü ve boyutu söyler, ilerlemeyi gösterir ve <em>İndirmeyi kaldır</em> onu yeniden siler; kendi kopyan kuruluysa uygulama onu kullanır. Claude Code’un lisansı birlikte dağıtılmasına izin vermez, bu yüzden kartı <em>Claude Code kur</em> seçeneğini sunar: Anthropic’in resmî yükleyicisini kartın terminalinde, ev klasörüne, yönetici parolası olmadan çalıştırır. Varsayılan ajan ve model ile izin ön ayarı depo başına farklı olabilir.</p>',
    '<p>Kart ayrıca kurulu CLI bu sürümün denendiği sürümlerden daha yeni ya da daha eskiyse bunu söyler. Oturumlar yine çalışır; not, eksik bir raporun nedenini açıklamak için oradadır. Codex bağlantısını kaybedip yeniden denediğinde döküm hata yerine kısa bir <em>Yeniden bağlanıyor…</em> notu gösterir.</p>',
  ]),
  ('permissions', 'İzinler', [
    '<p>Ajanlar önceden onaylamadığın şeyleri yapmadan önce sorar. Ayarlar › İzinler’de üç ön ayar var — <em>katı</em> (yalnızca okuma), <em>dengeli</em> (dosya okuma ve düzenleme, geri kalan her şey için sorma) ve <em>yolo</em> (ayrıca komut çalıştırma, web kullanma ve push) — ayrıca okuma, düzenleme, komut çalıştırma, web erişimi, push ve silme için tekil anahtarlar. Ön ayar ne olursa olsun, sen açmadığın sürece bir ajan asla sormadan silemez.</p>'
    '<p>Bir istek geldiğinde <em>Onayla</em> ve <em>Reddet</em> bir kez yanıtlar; <em>Her zaman izin ver</em> o aracı o worktree için hatırlar ve kural worktree ile birlikte gider.</p>',
    '<p>Bir ajan aynı anda birkaç şey istediğinde istekler oturum kartında ve gelen kutusunda sıraya girer — <em>1 / 3</em> — ve sen onları sırayla yanıtlarsın. Ayarlar › İzinler › <em>İzin verilen kurallar</em> her “Her zaman izin ver”i worktree’ye göre, eklendiği tarihle listeler; <em>Geri al</em> hemen, çalışan bir oturumda da etkili olur. <em>Şu süreden sonra otomatik reddet</em> (dakika, varsayılan olarak kapalı) kimsenin yanıtlamadığı bir isteği reddeder ve ajana nedenini söyler. Codex ve Gemini CLI soru soramaz; bu yüzden ajan çubukları, anahtarlarının onlara verdiği sandbox modunu gösterir; ona tıklamak Ayarlar › İzinler’i açar.</p>',
  ]),
  ('notifications', 'Bildirimler, gelen kutusu ve bütçe', [
    '<p>Ayarlar › Bildirimler uygulamanın sana ne zaman haber vereceğini seçer: bir oturum beklerken, biri bittiğinde ve bir pull request değiştiğinde — kontroller tamamlandı, onaylandı, değişiklik istendi, birleştirildi. Pull request’ler her worktree için arka planda izlenir; böylece bakmadığın bir worktree için bile yaklaşık beş dakika içinde haberin olur; bu şekilde fark edilen bir birleştirme, sen yanıtlayana kadar worktree’yi kaldırma önerisini korur. Bildirimler yalnızca pencere önde değilken görünür, birine tıklamak oturuma atlar ve dock ya da görev çubuğu rozeti bekleyen oturumları sayabilir.</p>',
    '<p>Başlıktaki gelen kutusunun iki sekmesi var. <em>Girdi bekliyor</em> seni bekleyen oturumlardır. <em>Etkinlik</em> uygulamanın sana söylediği her şeydir — biten turlar, pull request değişiklikleri, git’in tam çıktısıyla hatalar, kaçırmış olabileceğin uyarılar — ve bir satıra tıklamak seni onun oturumuna ya da worktree’sine götürür. Okunmamış satırlar sayılır, <em>Tümünü okundu say</em> onları temizler ve en son 200 satır yeniden başlatmalar arasında saklanır.</p>',
    '<p>Sol panelin altındaki bütçe çubuğu, tüm oturumlardaki bugünkü harcamadır. Bir ajan kendi maliyetini bildirdiğinde rakam odur; bildirmezse token’ları modelin liste fiyatından hesaplanır, Ayarlar › Bütçe’deki ücretler ise yalnızca liste fiyatı olmayan modeller içindir. Kullanım penceresi ve bir oturumun maliyet ipucu hangisi olduğunu söyler. Ayarlar › Bütçe ayrıca günlük ve oturum başına bir limit ile bir uyarı eşiği belirler; <em>Limitte oturumları duraklat</em> açıkken günlük limite ulaşmak hâlâ süren turları da durdurur ve bir uyarı kaç tane olduğunu söyler.</p>',
  ]),
  ('settings', 'Ayarlar', [
    '<p>Ayarlar (⌘,) konuya göre gruplanmıştır. Görünüm temayı, vurgu rengini, yoğunluğu ve yazı tiplerini belirler; Dil, arayüzü İngilizce, İspanyolca, İtalyanca, Lehçe, Fransızca, Almanca ve Türkçe arasında değiştirir. Birkaç bölümde <em>depo başına</em> rozeti var: üstte bir depo seçiliyken bunları yalnızca o depo için geçersiz kılabilirsin. Tarihler, saatler, sayılar ve maliyetler sistemin dilini değil, seçtiğin dili izler.</p>'
    '<p>Her şey, ev dizinindeki uygulama klasöründe bulunan <code>settings.json</code> dosyasına otomatik kaydedilir; <em>settings.json dosyasını aç</em> ham dosyayı doğrulamayla düzenler ve üst bar en son ne zaman yazıldığını gösterir. Dosya kendi <a href="https://mhguitarte.github.io/ygd-editor/settings.schema.json">şemasını</a> belirtir; böylece VS Code gibi bir editör, dosyayı elle düzenlerken tamamlar ve denetler. Her kayıt önceki dosyayı <code>settings.json.bak</code> olarak saklar; dosya bozulursa uygulama o kopyayla çalışır ve sana söyler. Uygulamanın eski bir sürümü, daha yeni bir sürümün yazdığı bir dosyanın üzerine asla yazmaz: varsayılanlarla çalışır ve sen yeniden güncelleyene kadar ayarları kaydetmeyi reddeder. Çalışma alanları, gelen kutusu ve oturum listeleri de aynı şekilde saklanır.</p>',
    '<p>Üstteki <em>Ayarlarda ara</em>, herhangi bir satırı adından ya da ne yaptığından bulur: “bütçe limit” yaz, Bütçe imleç Günlük limit’teyken açılır; ⌘K de ayarları bulur. Değiştirdiğin bir satırda bir nokta ve kendi <em>Sıfırla</em> düğmesi görünür. Sayı alanları uygulamanın kullanamayacağı bir değeri reddeder, nedenini söyler ve kaydedilmiş olanı korur.</p>',
    '<img src="{img}settings.png" alt="Ayarlar › Görünüm" loading="lazy">',
  ]),
  ('layout', 'Küçük pencereler ve klavye', [
   '<strong>Küçük pencereler.</strong> Pencere 900 × 680’e kadar küçülür; böylece uygulama 13 ya da 14 inçlik bir dizüstünde bir editörün yanına sığar. Yaklaşık 1.180 pikselden dar olduğunda oturumlar paneli ince bir şeride katlanır, yaklaşık 1.000’den dar olduğunda worktree listesi de. Paneli ortanın üstünde açmak için şeride tıkla; Escape ya da yanına bir tık onu kaldırır. Kayıtlı düzenine dokunulmaz: pencereyi genişlet, paneller eskisi gibi geri gelir.',
   '<strong>Klavyeden.</strong> Her liste — worktree’ler, oturumlar, terminal sekmeleri, Ayarlar bölümleri, son depolar — tek bir Tab durağıdır. ↑ ve ↓ (terminal sekmelerinde ← ve →), Home ve End liste içinde gezinir, Enter ya da Boşluk bir satırı seçer, Menü tuşu ya da Shift+F10 satırın menüsünü açar, F2 de bir terminal sekmesini yeniden adlandırır.',
   '<strong>Soruları uygulamanın kendisi sorar.</strong> Evet gerektiren her şey — değişiklikleri atmak, bir stash’i silmek, bir pull request’i birleştirmek — uygulamanın kendi penceresinde, senin dilinde ve eylemin adı düğmede yazılı olarak sorulur; Escape hayır demektir. Klonlama, Oturumu devret ve Uzak depolar, içlerine yazdıklarını atmadan önce sorar.',
  ]),
  ('updates', 'Güncellemeler', [
    '<p>Açılıştan kısa süre sonra ve açık kaldığı sürece her altı saatte bir, uygulama bu sitenin sürümlerine bakar ve yeni bir sürüm olduğunda sana söyler. Tek tık onu indirir; Ayarlar › Hakkında ve güncellemeler › <em>Güncellemeleri otomatik indir</em> açıksa bulunur bulunmaz indirilir. Sen seçene kadar hiçbir şey kurulmaz: şimdi <em>Yeniden başlat ve güncelle</em>, <em>Daha sonra yeniden başlat</em> — o zaman çıkışta kurulur — ya da <em>İptal et</em>.</p>',
    '<p>Bir güncelleme yalnızca sürümün imzalı sağlama toplamları onu listeliyorsa kurulur; bu, uygulamanın içindeki sertifikaya karşı denetlenir. Listelemiyorsa uygulama güncellemenin proje tarafından imzalanmadığını söyler ve hiçbir şey kurmaz. Ayarlar › Hakkında ve güncellemeler’de ayrıca denetimleri kapatan <em>Güncellemeleri öner</em> ve son kontrolün saatiyle <em>Güncellemeleri kontrol et</em> var.</p>',
    '<p>Güncellemeden sonraki ilk açılış hangi sürümde olduğunu söyler ve oradaki <em>Yenilikler</em> sürüm notlarını uygulamanın içinde açar. Ayarlar › Hakkında ve güncellemeler ve komut paleti de onları açar.</p>',
  ]),
  ('shortcuts', 'Klavye kısayolları', [
    '<table><tr><td>⌘O</td><td>Depo aç</td></tr><tr><td>⇧⌘C</td><td>Depo klonla</td></tr><tr><td>⌘N</td><td>Yeni worktree</td></tr><tr><td>⌘K</td><td>Komut paleti</td></tr><tr><td>⌘,</td><td>Ayarlar</td></tr><tr><td>⌘↵</td><td>İstemi gönder</td></tr><tr><td>⌘F</td><td>Terminalde ara</td></tr><tr><td>⌘⇧] ⌘⇧[</td><td>Sonraki / önceki terminal</td></tr><tr><td>⇧N</td><td>Sonraki görülmemiş dosya</td></tr></table>'
    '<p>Windows ve Linux’ta ⌘’yi Ctrl olarak oku — terminal hariç: orada arama Ctrl+Shift+F’dir, Ctrl+PageDown / Ctrl+PageUp da terminaller arasında geçer. Kısayolların çoğu Ayarlar › Klavye kısayolları altında değiştirilebilir.</p>',
  ]),
  ('trouble', 'Bir şeyler ters gittiğinde', [
    '<p><strong>macOS uygulamayı doğrulayamadığını söylüyor (Çöp Sepeti’ne Taşı / Bitti).</strong> Bitti’ye tıkla, sonra Sistem Ayarları › Gizlilik ve Güvenlik › Güvenlik’e kadar in › <em>Yine de Aç</em>, ve parolanla onayla. macOS 14 veya daha eskisinde sağ tık › Aç tek adımda yapar. Hâlâ reddediyorsa Terminal’de: <code>xattr -d com.apple.quarantine /Applications/ygd-editor.app</code>. Uygulamanın <em>hasarlı</em> olduğunu söylüyorsa indirme bozulmuştur: yeniden indir ve <code>SHA256SUMS.txt</code> ile karşılaştır.</p>'
    '<p><strong>Uyarıdan tamamen kaçınmak.</strong> Terminal’den kur: <code>curl -fsSL https://mhguitarte.github.io/ygd-editor/install.sh | bash</code>. İndirilen dosyayı macOS’un yapacağı gibi denetler ve uygulamayı Uygulamalar klasörüne koyar; indirme sayfasına bak.</p>'
    '<p><strong>Windows yükleyiciyi engelliyor.</strong> SmartScreen › Ek bilgi › Yine de çalıştır. Yayımcı <em>ygd-editor release signing</em> olmalı.</p>'
    '<p><strong>AppImage başlamıyor.</strong> <code>--appimage-extract-and-run</code> ile çalıştır ya da <code>libfuse2</code> kur.</p>'
    '<p><strong>Bir sağlayıcı “Kurulu değil” gösteriyor.</strong> Codex ve Gemini CLI istek üzerine indirilir: karttaki <em>İndir</em>’e tıkla; indirme başarısız olursa kart nedenini söyler (çevrimdışı ya da sağlama toplamıyla eşleşmeyip atılan bir dosya). Claude Code için kartındaki <em>Claude Code kur</em>’a tıkla; kendin kurduysan bir terminal aç, <code>claude --version</code> komutunun çalıştığını kontrol et, sonra Ayarlar › Yapay zekâ sağlayıcıları › Yeniden tara.</p>'
    '<p><strong>Git hataları.</strong> Uygulama sık görülenleri tek cümleyle açıklar — kimlik bilgileri, ilerlemiş bir uzak depo, bir kilit dosyası, kirli bir çalışma ağacı, çakışmalar — ve tam çıktıyı worktree terminalinde tutar.</p>'
    '<p><strong>Güncelleme görünmüyor.</strong> Ayarlar › Hakkında ve güncellemeler › Güncellemeleri öner’i kontrol et, sonra Güncellemeleri kontrol et; uygulamanın github.com’a erişebilmesi gerekir.</p>'
    '<p><strong>Bir güncelleme proje tarafından imzalanmadığı için reddedildi.</strong> Hiçbir şey kurulmadı. Yükleyiciyi <a href="{prefix}releases.html">Tüm sürümler</a> sayfasından indir ve <a href="{prefix}index.html#genuine">İndirdiğim dosya gerçek mi?</a> bölümünün anlattığı gibi kontrol et.</p>'
    '<p><strong>Eski bir sürüme döndükten sonra ayarlar kaydedilmiyor.</strong> Eski uygulama, yeni sürümün yazdığı dosyalara dokunmaz, varsayılanlarla çalışır ve hangi dosya olduğunu söyler. Yeniden güncelle, her şey bıraktığın yerde olur.</p>'
    '<p><strong>Bir sorunu bildirmek.</strong> Ayarlar › Tanılama bir hata raporunun ihtiyaç duyduklarını gösterir: uygulamanın, git’in ve her ajan CLI’ının sürümleri, ajanların aldığı PATH, çalışan ajan süreçleri ve filtreleyebileceğin canlı bir günlük. <em>Günlük düzeyleri</em> ne kadar kayıt tutulacağını belirler — <code>info, git=debug</code> git’i ayrıntılı kaydeder. <em>Paketi hazırla…</em> hepsini bir zip’te toplar ve <em>Zip’i kaydet…</em>’ten önce okuyabilmen için her dosyayı listeler: token’lar ve API anahtarları maskelenir, ajanlara ve terminallere yazdıkların dışarıda bırakılır, ev klasörün <code>~</code> olarak görünür. Ne yaptığını, ne beklediğini ve ne olduğunu anlatarak onu <a href="https://github.com/{repo}/issues">bir issue’ya</a> ekle.</p>',
  ]),
  ('uninstall', 'Kaldırma', [
    '<strong>Kaldırmadan önce</strong> — ikisi de isteğe bağlı. Varsayılan worktree’de <em>geçerli</em> bir worktree varsa <em>Bitir</em>’e tıkla; böylece varsayılan worktree kendi dalını ve değişikliklerini geri alır. Bir sağlayıcıdan çıkış yapmak için Ayarlar › Yapay zekâ sağlayıcıları’nda kartındaki <em>Bağlantıyı kes</em>’i kullan: oturumlar uygulamanın değil Claude Code, Codex ve Gemini CLI’ın, bu yüzden uygulamayı kaldırmak onları kapatmaz. Sonra ygd-editor’dan çık.',
    '<strong>macOS.</strong> <strong>ygd-editor</strong>’ü Uygulamalar klasöründen Çöp Sepeti’ne sürükle — Terminal kurulumu onu oraya koyduysa <code>~/Applications</code>’dan.',
    '<strong>Windows.</strong> Ayarlar › Uygulamalar › Yüklü uygulamalar › ygd-editor › <em>Kaldır</em> ya da Denetim Masası › Programlar ve Özellikler.',
    '<strong>Linux.</strong> AppImage dosyasını sil. Debian / Ubuntu paketi için: <code>sudo apt remove ygd-editor</code>.',
    '<strong>Geride kalanlar.</strong> Ayarların, çalışma alanların, oturum geçmişin ve Codex ile Gemini CLI indirmeleri ev dizinindeki <code>.ygd-editor</code> klasöründe durur ve kaldırma işlemi bunları silmez; yeniden kurduğunda kaldığın yerden devam edersin. Bunları da uygulamanın önbellekleriyle birlikte silmek için kaldırdıktan sonra şunu çalıştır:',
    '<p>macOS:</p><pre>rm -rf ~/.ygd-editor ~/Library/Application\\ Support/ygd-editor ~/Library/Caches/ygd-editor-updater ~/Library/Caches/com.mhguitarte.ygd-editor* ~/Library/HTTPStorages/com.mhguitarte.ygd-editor ~/Library/Preferences/com.mhguitarte.ygd-editor.plist</pre>',
    '<p>Windows (PowerShell):</p><pre>Remove-Item -Recurse -Force -ErrorAction SilentlyContinue "$env:USERPROFILE\\.ygd-editor", "$env:APPDATA\\ygd-editor", "$env:LOCALAPPDATA\\ygd-editor-updater"</pre>',
    '<p>Linux:</p><pre>rm -rf ~/.ygd-editor ~/.config/ygd-editor ~/.cache/ygd-editor-updater</pre>',
    '<strong>Asla dokunulmayanlar.</strong> Depoların ve oluşturduğun worktree’ler sıradan git klasörleridir ve oldukları yerde kalır; <code>git worktree remove &lt;klasör&gt;</code> birini kaldırır. Claude Code’u uygulama senin için kurduysa ev dizininde kalır — nasıl kaldırılacağını <a href="https://docs.anthropic.com/en/docs/claude-code">Anthropic’in belgeleri</a> anlatır.',
  ]),
  ('privacy', 'Gizlilik ve güvenlik', [
    '<p>Her şey bilgisayarında çalışır. Uygulamanın kendisi internete iki şey için bağlanır: güncellemeler için bu sitenin sürümlerine bakmak ve günde bir kez models.dev’den modellerin ve fiyatlarının herkese açık listesini almak. Ajanlar sağlayıcılarıyla senin hesaplarınla konuşur; git uzak depolarınla senin kimlik bilgilerinle konuşur. Uygulamanın sakladığı sağlayıcı token’ları işletim sisteminin anahtar zincirinde tutulur. Arayüz sandbox içinde çalışır, bir yol adı geçen her istek gerçekten açtığın depolara karşı kontrol edilir ve hiçbir komut asla bir kabuk dizesinden oluşturulmaz. Tanılama paketi senin seçtiğin yere kaydedilir ve hiçbir yere gönderilmez.</p>'
    '<p>Bir indirmenin gerçekten bize ait olduğunu kontrol etmek için indirme sayfasındaki <a href="{prefix}index.html#genuine">İndirdiğim dosya gerçek mi?</a> bölümüne bak.</p>',
  ]),
 ],
 # sürümler sayfası ve ortak küçük dizeler
 'dl_version': 'sürüm {v}',
 'genuine_details': 'teknik ayrıntılar',
 'lang_label': 'Dil',
 'title_releases': 'ygd-editor — tüm sürümler',
 'r_h1': 'Tüm sürümler',
 'r_lead': 'ygd-editor’ün yayınlanmış her sürümü. Önce her sistem için en yenisi, sonra sistem sistem tüm geçmiş. İndirme sayfası her zaman en yeni tam sürümü sunar; bu liste belirli bir sürüme ihtiyacı olanlar için.',
 'r_latest_h': 'Her sistem için en yenisi',
 'r_all_h': 'Her sürüm, sisteme göre',
 'r_systems': {'mac': 'macOS', 'win': 'Windows', 'linux': 'Linux'},
 'r_loading': 'Sürümler yükleniyor…',
 'r_error': 'Sürüm listesi okunamadı ({err}).',
 'r_github': 'GitHub’daki sürümler',
 'r_none': 'Henüz yayınlanmış sürüm yok.',
 'r_notes': 'Neler değişti',
 'r_checksums': 'Sağlama toplamları',
 'r_updates': 'Kurulu uygulamalar kendilerini en yeni tam sürüme günceller; belirli bir sürüm istemiyorsan buradaki hiçbir şeyi elle indirmen gerekmez.',
}
